# Preparación del dataset para modelado inmobiliario

Este notebook continúa el EDA. El dataset original se conserva sin modificaciones y todas las decisiones de preparación se aplican sobre una copia de trabajo.

## 1. Crear la copia de trabajo y eliminar columnas iniciales

Partimos de `secondary_market_date_transformado.csv`, que fue utilizado como fuente del EDA. Antes de eliminar `date_posted`, reconstruimos `periodo` con la misma regla usada durante el EDA para conservar la dimensión temporal. En esta primera etapa eliminamos únicamente las columnas seleccionadas: identificador, fecha original, precio total derivado del objetivo y variables que no continuaremos usando en esta versión del dataset.

La eliminación se realiza sobre `df_modelado`, una copia independiente. El archivo fuente no se sobrescribe.

In [1]:
from pathlib import Path
import pandas as pd
from IPython.display import display

RUTA_ORIGEN = Path("data_sets_transformados/secondary_market_date_transformado.csv")
RUTA_SALIDA = Path("data_sets_transformados/secondary_market_modelado_base.csv")

columnas_eliminar = [
    "id",
    "date_posted",
    "price_rub",
    "building_year",
    "okrug",
    "metro_line"
]

df_original = pd.read_csv(RUTA_ORIGEN, parse_dates=["date_posted"])
df_modelado = df_original.copy()
df_modelado["periodo"] = df_modelado["date_posted"].dt.to_period("M").astype(str)

columnas_faltantes = sorted(set(columnas_eliminar) - set(df_modelado.columns))
if columnas_faltantes:
    raise KeyError(f"No se encontraron las columnas esperadas: {columnas_faltantes}")

df_modelado = df_modelado.drop(columns=columnas_eliminar)
df_modelado.to_csv(RUTA_SALIDA, index=False)

print(f"Dataset original: {df_original.shape[0]:,} filas x {df_original.shape[1]} columnas")
print(f"Dataset de modelado: {df_modelado.shape[0]:,} filas x {df_modelado.shape[1]} columnas")
print(f"Columnas eliminadas: {columnas_eliminar}")
print(f"Copia guardada en: {RUTA_SALIDA}")
display(df_modelado.head())

Dataset original: 50,000 filas x 29 columnas
Dataset de modelado: 50,000 filas x 24 columnas
Columnas eliminadas: ['id', 'date_posted', 'price_rub', 'building_year', 'okrug', 'metro_line']
Copia guardada en: data_sets_transformados\secondary_market_modelado_base.csv

,district,lat,lon,total_area,living_area,kitchen_area,rooms,floor,total_floors,building_type,...,metro_distance_min,metro_distance_type,to_center_km,price_per_sqm,mortgage_rate_at_listing,seller_type,date_posted_year,date_posted_month,building_age,periodo
0,Begovoy,55.79533,37.55519,71.0,46.5,6.1,2,19,25,khrushchev,...,18,transport,6.17,221700,23.5,agency,2024,11,55,2024-11
1,Sokolniki,55.79695,37.68875,79.6,52.8,10.8,3,2,25,modern_panel,...,7,walk,6.40,247300,19.5,owner,2025,8,9,2025-08
2,Sosenskoye,55.54901,37.43118,74.0,42.2,8.9,2,6,9,monolith,...,102,transport,25.70,116400,12.0,owner,2022,5,6,2022-05
3,Sviblovo,55.86462,37.61471,52.3,34.0,6.0,1,5,22,monolith,...,9,walk,12.32,282400,23.5,agency,2025,4,13,2025-04
4,Begovoy,55.79429,37.54631,62.2,38.3,13.1,2,12,12,brick,...,10,walk,6.47,300300,15.5,agency,2023,7,21,2023-07

### Interpretación

La cantidad de filas debe mantenerse igual: esta etapa solo elimina columnas de la copia de trabajo. `price_per_sqm` continúa siendo la variable objetivo y `periodo` se conserva para decidir más adelante cómo realizar la evaluación temporal.

## 2. One-hot encoding sin colinealidad entre dummies

Convertimos las variables categóricas en indicadores numéricos. Usamos `drop_first=True` para conservar una categoría de referencia por variable y evitar la trampa de las variables ficticias cuando el modelo incluya intercepto.

`periodo` no se convierte a dummies: se conserva como clave temporal para ordenar y separar entrenamiento y prueba cronológicamente.

In [2]:
RUTA_ENTRADA_ONE_HOT = Path("data_sets_transformados/secondary_market_modelado_base.csv")
RUTA_SALIDA_ONE_HOT = Path("data_sets_transformados/secondary_market_modelado_one_hot.csv")

df_modelado = pd.read_csv(RUTA_ENTRADA_ONE_HOT)
columnas_categoricas = [
    columna
    for columna in df_modelado.select_dtypes(include=["object", "string", "category", "bool"]).columns
    if columna != "periodo"
]

categorias_por_variable = df_modelado[columnas_categoricas].nunique(dropna=False)
df_modelado_one_hot = pd.get_dummies(
    df_modelado,
    columns=columnas_categoricas,
    drop_first=True,
    dtype=int
)

# Verificamos que cada variable categórica haya generado una categoría menos.
dummies_por_variable = {
    columna: [nombre for nombre in df_modelado_one_hot.columns if nombre.startswith(f"{columna}_")]
    for columna in columnas_categoricas
}
validacion_dummies = pd.DataFrame({
    "variable": columnas_categoricas,
    "categorias_originales": [categorias_por_variable[columna] for columna in columnas_categoricas],
    "dummies_generadas": [len(dummies_por_variable[columna]) for columna in columnas_categoricas],
})
validacion_dummies["cumple_drop_first"] = (
    validacion_dummies["dummies_generadas"] == validacion_dummies["categorias_originales"] - 1
)

if not validacion_dummies["cumple_drop_first"].all():
    raise AssertionError("Alguna variable categórica no respetó drop_first=True")

df_modelado_one_hot.to_csv(RUTA_SALIDA_ONE_HOT, index=False)

print(f"Variables categóricas codificadas: {columnas_categoricas}")
print(f"Dataset antes del one-hot: {df_modelado.shape[0]:,} filas x {df_modelado.shape[1]} columnas")
print(f"Dataset después del one-hot: {df_modelado_one_hot.shape[0]:,} filas x {df_modelado_one_hot.shape[1]} columnas")
print("Periodo conservado sin one-hot:", "periodo" in df_modelado_one_hot.columns)
print(f"Archivo guardado en: {RUTA_SALIDA_ONE_HOT}")
display(validacion_dummies)
display(df_modelado_one_hot.head())

Variables categóricas codificadas: ['district', 'building_type', 'has_balcony', 'renovation', 'metro_station', 'metro_distance_type', 'seller_type']
Dataset antes del one-hot: 50,000 filas x 24 columnas
Dataset después del one-hot: 50,000 filas x 259 columnas
Periodo conservado sin one-hot: True
Archivo guardado en: data_sets_transformados\secondary_market_modelado_one_hot.csv

,variable,categorias_originales,dummies_generadas,cumple_drop_first
0,district,129,128,True
1,building_type,6,5,True
2,has_balcony,2,1,True
3,renovation,4,3,True
4,metro_station,104,103,True
5,metro_distance_type,2,1,True
6,seller_type,2,1,True

,lat,lon,total_area,living_area,kitchen_area,rooms,floor,total_floors,ceiling_height,metro_distance_min,...,metro_station_Ulitsa Podbelskogo,metro_station_Universitet,metro_station_VDNKh,metro_station_Voykovskaya,metro_station_Vystavochnaya,metro_station_Yasenevo,metro_station_Yugo-Zapadnaya,metro_station_Yuzhnaya,metro_distance_type_walk,seller_type_owner
0,55.79533,37.55519,71.0,46.5,6.1,2,19,25,2.5,18,...,0,0,0,0,0,0,0,0,0,0
1,55.79695,37.68875,79.6,52.8,10.8,3,2,25,2.5,7,...,0,0,0,0,0,0,0,0,1,1
2,55.54901,37.43118,74.0,42.2,8.9,2,6,9,3.0,102,...,0,0,0,0,0,0,0,0,0,1
3,55.86462,37.61471,52.3,34.0,6.0,1,5,22,2.5,9,...,0,0,0,0,0,0,0,0,1,0
4,55.79429,37.54631,62.2,38.3,13.1,2,12,12,2.5,10,...,0,0,0,0,0,0,0,0,1,0

### Interpretación

Cada variable categórica queda representada por una categoría menos que las originales. La categoría omitida funciona como referencia y evita dependencia lineal perfecta entre las dummies y el intercepto. Esto evita la colinealidad propia del one-hot completo; no garantiza que no existan otras relaciones fuertes entre variables numéricas o derivadas, que deberán revisarse en una etapa posterior.

## 3. Regresión lineal OLS y registro en MLflow

Ajustamos una regresión lineal con `statsmodels.OLS` sobre el dataset one-hot. La separación es temporal: se entrena con períodos anteriores a `2025-01` y se evalúa desde `2025-01` en adelante. `periodo` se usa para separar los conjuntos, pero no entra como predictor.

La corrida registra métricas de entrenamiento y prueba, criterios del ajuste OLS, diagnósticos de residuos, coeficientes, residuos de prueba y el resumen completo del modelo.

In [3]:
import mlflow
import statsmodels.api as sm
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from statsmodels.stats.stattools import durbin_watson, jarque_bera, omni_normtest

RUTA_OLS = Path("data_sets_transformados/secondary_market_modelado_one_hot.csv")
CORTE_TEMPORAL = "2025-01"
df_ols = pd.read_csv(RUTA_OLS)
df_ols = df_ols.sort_values("periodo").reset_index(drop=True)

df_train_ols = df_ols[df_ols["periodo"] < CORTE_TEMPORAL].copy()
df_test_ols = df_ols[df_ols["periodo"] >= CORTE_TEMPORAL].copy()
if df_train_ols.empty or df_test_ols.empty:
    raise ValueError("El corte temporal no produjo conjuntos de entrenamiento y prueba válidos")

columnas_excluir_ols = ["price_per_sqm", "periodo"]
X_train_ols = df_train_ols.drop(columns=columnas_excluir_ols)
X_test_ols = df_test_ols.drop(columns=columnas_excluir_ols)
y_train_ols = df_train_ols["price_per_sqm"]
y_test_ols = df_test_ols["price_per_sqm"]

X_train_ols_sm = sm.add_constant(X_train_ols, has_constant="add")
X_test_ols_sm = sm.add_constant(X_test_ols, has_constant="add")
modelo_ols_temporal = sm.OLS(y_train_ols, X_train_ols_sm)
resultados_ols_temporal = modelo_ols_temporal.fit()
predicciones_train_ols = resultados_ols_temporal.predict(X_train_ols_sm)
predicciones_test_ols = resultados_ols_temporal.predict(X_test_ols_sm)

def calcular_metricas_regresion(y_real, predicciones, prefijo):
    errores_porcentuales = (y_real - predicciones) / y_real
    return {
        f"mae_{prefijo}": float(mean_absolute_error(y_real, predicciones)),
        f"rmse_{prefijo}": float(mean_squared_error(y_real, predicciones) ** 0.5),
        f"r2_{prefijo}": float(r2_score(y_real, predicciones)),
        f"mape_{prefijo}": float(errores_porcentuales.abs().mean() * 100)
    }

metricas_ols_temporal = {
    **calcular_metricas_regresion(y_train_ols, predicciones_train_ols, "train"),
    **calcular_metricas_regresion(y_test_ols, predicciones_test_ols, "test"),
    "r2_ols": float(resultados_ols_temporal.rsquared),
    "r2_ajustado_ols": float(resultados_ols_temporal.rsquared_adj),
    "aic_ols": float(resultados_ols_temporal.aic),
    "bic_ols": float(resultados_ols_temporal.bic),
    "f_statistic_ols": float(resultados_ols_temporal.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_temporal.f_pvalue),
}

omnibus_ols, prob_omnibus_ols = omni_normtest(resultados_ols_temporal.resid)
jarque_bera_ols, prob_jb_ols, skew_ols, kurtosis_ols = jarque_bera(resultados_ols_temporal.resid)
metricas_ols_temporal.update({
    "omnibus_ols": float(omnibus_ols),
    "prob_omnibus_ols": float(prob_omnibus_ols),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_temporal.resid)),
    "jarque_bera_ols": float(jarque_bera_ols),
    "prob_jb_ols": float(prob_jb_ols),
    "skew_ols": float(skew_ols),
    "kurtosis_ols": float(kurtosis_ols),
    "condition_number_ols": float(resultados_ols_temporal.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_temporal.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_temporal.pvalues > 0.05).sum())
})

coeficientes_ols_temporal = pd.DataFrame({
    "variable": resultados_ols_temporal.params.index,
    "coeficiente": resultados_ols_temporal.params.to_numpy(),
    "p_value": resultados_ols_temporal.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_temporal.pvalues.to_numpy() <= 0.05
})
residuos_test_ols = pd.DataFrame({
    "periodo": df_test_ols["periodo"].to_numpy(),
    "real": y_test_ols.to_numpy(),
    "prediccion": predicciones_test_ols.to_numpy(),
    "residuo": (y_test_ols.to_numpy() - predicciones_test_ols.to_numpy())
})

tabla_metricas_ols_temporal = pd.DataFrame({"metrica": list(metricas_ols_temporal), "valor": list(metricas_ols_temporal.values())})
display(tabla_metricas_ols_temporal)
print(resultados_ols_temporal.summary())

mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_modelado_one_hot"):
    mlflow.log_params({
        "dataset": str(RUTA_OLS),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "periodo_entrenamiento_desde": str(df_train_ols["periodo"].min()),
        "periodo_entrenamiento_hasta": str(df_train_ols["periodo"].max()),
        "periodo_prueba_desde": str(df_test_ols["periodo"].min()),
        "periodo_prueba_hasta": str(df_test_ols["periodo"].max()),
        "filas_entrenamiento": len(df_train_ols),
        "filas_prueba": len(df_test_ols),
        "n_predictores": X_train_ols.shape[1],
        "tipo_modelo": "statsmodels_OLS"
    })
    mlflow.log_metrics(metricas_ols_temporal)
    mlflow.log_table(tabla_metricas_ols_temporal, artifact_file="metricas/metricas_ols_temporal.json")
    mlflow.log_table(coeficientes_ols_temporal, artifact_file="modelo/coeficientes_ols_temporal.json")
    mlflow.log_table(residuos_test_ols, artifact_file="diagnostico/residuos_test_ols.json")
    mlflow.log_text(resultados_ols_temporal.summary().as_text(), "modelo/resumen_ols_temporal.txt")

print("OLS temporal registrado en MLflow: experimento 'Inmobiliario - OLS Temporal'")

2026/10/12 23:07:46 INFO mlflow.agent.hint: Load the `instrumenting-with-mlflow-tracing` skill at C:\Users\Rodrigo\Documents\Facultad\Analisis de datos\Parcial\.venv\Lib\site-packages\mlflow\assistant\skills\instrumenting-with-mlflow-tracing\SKILL.md before writing any tracing code; it ships with this MLflow install. Set MLFLOW_DISABLE_AGENT_HINT=1 to silence this.

                               metrica         valor
0                            mae_train  2.314073e+04
1                           rmse_train  3.353420e+04
2                             r2_train  9.082387e-01
3                           mape_train  1.491517e+01
4                             mae_test  3.708559e+04
5                            rmse_test  4.513263e+04
6                              r2_test  8.598280e-01
7                            mape_test  2.317410e+01
8                               r2_ols  9.082387e-01
9                      r2_ajustado_ols  9.076402e-01
10                             aic_ols  9.395587e+05
11                             bic_ols  9.417744e+05
12                     f_statistic_ols  1.517413e+03
13                prob_f_statistic_ols  0.000000e+00
14                         omnibus_ols  1.318839e+04
15                    prob_omnibus_ols  0.000000e+00
16                   durbin_watson_ols  1.944385e+00
17                     jarque_bera_ols  2.142910e+05
18                         prob_jb_ols  0.000000e+00
19                            skew_ols  1.166093e+00
20                        kurtosis_ols  1.414649e+01
21                condition_number_ols  1.148398e+07
22     coeficientes_significativos_005  1.710000e+02
23  coeficientes_no_significativos_005  8.700000e+01

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1517.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:48   Log-Likelihood:            -4.6952e+05
No. Observations:               39658   AIC:                         9.396e+05
Df Residuals:                   39400   BIC:                         9.418e+05
Df Model:                         257
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -3.122e+07   9.57e+05    -32.617      0.000   -3.31e+07   -2.93e+07
lat                                      -4.028e+04   1.41e+04     -2.850      0.004    -6.8e+04   -1.26e+04
lon                                      -4053.6118   9506.919     -0.426      0.670   -2.27e+04    1.46e+04
total_area                                   7.7949     41.122      0.190      0.850     -72.805      88.395
living_area                                 10.9616     56.674      0.193      0.847    -100.121     122.044
kitchen_area                               114.6354     70.172      1.634      0.102     -22.904     252.175
rooms                                     -265.3757    375.350     -0.707      0.480   -1001.071     470.320
floor                                      134.5400     37.936      3.547      0.000      60.185     208.894
total_floors                                39.1876     32.034      1.223      0.221     -23.600     101.975
ceiling_height                            8507.6479    921.067      9.237      0.000    6702.334    1.03e+04
metro_distance_min                        -419.2336     10.357    -40.478      0.000    -439.534    -398.934
to_center_km                             -1476.3044    137.327    -10.750      0.000   -1745.468   -1207.141
mortgage_rate_at_listing                   -94.6311     52.614     -1.799      0.072    -197.757       8.494
date_posted_year                          1.672e+04    190.755     87.645      0.000    1.63e+04    1.71e+04
date_posted_month                         1239.8278     49.125     25.238      0.000    1143.541    1336.115
building_age                                10.8298     17.092      0.634      0.526     -22.671      44.331
district_Akademichesky                    3.957e+04   3204.011     12.351      0.000    3.33e+04    4.59e+04
district_Alekseevsky                     -1033.1018   2922.370     -0.354      0.724   -6761.018    4694.815
district_Altufyevsky                     -4.013e+04   3227.572    -12.434      0.000   -4.65e+04   -3.38e+04
district_Arbat                             2.67e+05   3046.181     87.638      0.000    2.61e+05    2.73e+05
district_Babushkinsky                    -3.168e+04   3313.526     -9.561      0.000   -3.82e+04   -2.52e+04
district_Basmanny                         1.401e+05   3121.379     44.886      0.000    1.34e+05    1.46e+05
district_Begovoy                          3.272e+04   2718.683     12.036      0.000    2.74e+04    3.81e+04
district_Beskudnikovsky                  -3.826e+04   3095.785    -12.358      0.000   -4.43e+04   -3.22e+04
district_Bibirevo                        -3.637e+04   3226.291    -11.273      0.000   -4.27e+04      -3e+04
district_Biryulyovo Vostochnoye          -5.691e+04   4599.987    -12.372      0.000   -6.59e+04   -4.79e+04
district_Biryulyovo Zapadnoye            -5.591e+04   4404.778    -12.694      0.000   -6.45e+04   -4.73e+04
district_Bogorodskoye                    -3.802e+04   3315.647    -11.466      0.000   -4.45e+04   -3.15e+04
district_Brateyevo                       -5.594e+04   4288.662    -13.044      0.000   -6.43e+04   -4.75e+04
district_Butyrsky                        -1.075e+04   2807.562     -3.827      0.000   -1.62e+04   -5242.422
district_Chertanovo Severnoye            -4.107e+04   3649.135    -11.256      0.000   -4.82e+04   -3.39e+04
district_Chertanovo Tsentralnoye         -5.302e+04   3840.312    -13.806      0.000   -6.05e+04   -4.55e+04
district_Chertanovo Yuzhnoye             -4.626e+04   4369.934    -10.586      0.000   -5.48e+04   -3.77e+04
district_Cheryomushki                     4.442e+04   3428.891     12.955      0.000    3.77e+04    5.11e+04
district_Danilovsky                        281.2943   3324.278      0.085      0.933   -6234.372    6796.960
district_Desyonovskoye                   -5.714e+04   5414.670    -10.553      0.000   -6.78e+04   -4.65e+04
district_Dmitrovsky                      -4.215e+04   3159.381    -13.342      0.000   -4.83e+04    -3.6e+04
district_Donskoy                          1.602e+04   3225.617      4.966      0.000    9696.125    2.23e+04
district_Dorogomilovo                     1.347e+05   2955.993     45.584      0.000    1.29e+05    1.41e+05
district_Fili-Davydkovo                   3.961e+04   2952.162     13.418      0.000    3.38e+04    4.54e+04
district_Filimonkovskoye                 -7.284e+04   5061.514    -14.392      0.000   -8.28e+04   -6.29e+04
district_Filyovsky Park                   5.578e+04   2921.000     19.095      0.000    5.01e+04    6.15e+04
district_Gagarinsky                       8.101e+04   3165.458     25.592      0.000    7.48e+04    8.72e+04
district_Golovinsky                      -3.279e+04   2901.695    -11.299      0.000   -3.85e+04   -2.71e+04
district_Golyanovo                       -5.066e+04   3947.676    -12.833      0.000   -5.84e+04   -4.29e+04
district_Ivanovskoye                      -4.75e+04   4074.400    -11.658      0.000   -5.55e+04   -3.95e+04
district_Izmaylovo                       -2.141e+04   3651.882     -5.864      0.000   -2.86e+04   -1.43e+04
district_Khamovniki                       2.913e+05   3030.672     96.109      0.000    2.85e+05    2.97e+05
district_Khoroshyovo-Mnyovniki            2.254e+04   2874.555      7.842      0.000    1.69e+04    2.82e+04
district_Khoroshyovsky                    4.085e+04   2788.858     14.647      0.000    3.54e+04    4.63e+04
district_Khovrino                        -4.058e+04   3147.234    -12.893      0.000   -4.67e+04   -3.44e+04
district_Kievsky                          1.738e+04   1.19e+04      1.461      0.144   -5932.278    4.07e+04
district_Klyonovskoye                    -2.385e+04   1.01e+04     -2.363      0.018   -4.36e+04   -4065.614
district_Kokoshkino                      -6.376e+04   5218.555    -12.218      0.000    -7.4e+04   -5.35e+04
district_Konkovo                          2714.0430   3634.654      0.747      0.455   -4409.968    9838.053
district_Koptevo                         -2.806e+04   2918.107     -9.617      0.000   -3.38e+04   -2.23e+04
district_Kosino-Ukhtomsky                -5.461e+04   4430.014    -12.328      0.000   -6.33e+04   -4.59e+04
district_Kotlovka                          1.22e+04   3399.940      3.587      0.000    5533.138    1.89e+04
district_Krasnopakhorskoye               -5.903e+04   7334.159     -8.049      0.000   -7.34e+04   -4.47e+04
district_Krasnoselsky                     1.267e+05   3121.446     40.580      0.000    1.21e+05    1.33e+05
district_Krylatskoye                      5.418e+04   3136.879     17.272      0.000     4.8e+04    6.03e+04
district_Kuntsevo                         1.671e+04   3145.376      5.313      0.000    1.05e+04    2.29e+04
district_Kurkino                          2.115e+04   3717.405      5.690      0.000    1.39e+04    2.84e+04
district_Levoberezhny                    -2.289e+04   3100.404     -7.382      0.000    -2.9e+04   -1.68e+04
district_Lianozovo                       -3.729e+04   3424.109    -10.891      0.000    -4.4e+04   -3.06e+04
district_Lomonosovsky                     7.421e+04   3204.607     23.158      0.000    6.79e+04    8.05e+04
district_Losinoostrovsky                 -3.155e+04   3542.817     -8.907      0.000   -3.85e+04   -2.46e+04
district_Marfino                         -3.568e+04   2883.166    -12.375      0.000   -4.13e+04      -3e+04
district_Marushkinskoye                  -6.396e+04   5634.453    -11.352      0.000    -7.5e+04   -5.29e+04
district_Maryina Roshcha                   154.7461   2981.390      0.052      0.959   -5688.851    5998.343
district_Meshchansky                      1.563e+05   2996.963     52.155      0.000     1.5e+05    1.62e+05
district_Metrogorodok                    -4.624e+04   3613.359    -12.798      0.000   -5.33e+04   -3.92e+04
district_Mikhaylovo-Yartsevskoye         -4.636e+04   8229.818     -5.634      0.000   -6.25e+04   -3.02e+04
district_Mitino                          -1.315e+04   3765.408     -3.492      0.000   -2.05e+04   -5768.030
district_Molzhaninovsky                    -3.1e+04   4442.826     -6.978      0.000   -3.97e+04   -2.23e+04
district_Moskovsky                       -5.732e+04   4732.491    -12.113      0.000   -6.66e+04    -4.8e+04
district_Moskvorechye-Saburovo           -4.295e+04   3809.970    -11.272      0.000   -5.04e+04   -3.55e+04
district_Mosrentgen                      -7.001e+04   4084.045    -17.143      0.000    -7.8e+04    -6.2e+04
district_Mozhaysky                        1737.1049   3273.069      0.531      0.596   -4678.189    8152.399
district_Nagatino-Sadovniki              -2.634e+04   3526.639     -7.469      0.000   -3.33e+04   -1.94e+04
district_Nagatinsky Zaton                -2.096e+04   3602.467     -5.817      0.000    -2.8e+04   -1.39e+04
district_Nagorny                         -1.777e+04   3532.586     -5.032      0.000   -2.47e+04   -1.09e+04
district_Novo-Peredelkino                -2.616e+04   4052.333     -6.457      0.000   -3.41e+04   -1.82e+04
district_Novofyodorovskoye                -213.0072   1.12e+04     -0.019      0.985   -2.21e+04    2.17e+04
district_Novogireyevo                    -3.946e+04   3968.951     -9.943      0.000   -4.72e+04   -3.17e+04
district_Novokosino                      -4.021e+04   4482.852     -8.971      0.000    -4.9e+04   -3.14e+04
district_Obruchevsky                      2.204e+04   3478.939      6.337      0.000    1.52e+04    2.89e+04
district_Ochakovo-Matveyevskoye            773.5218   3301.432      0.234      0.815   -5697.365    7244.409
district_Orekhovo-Borisovo Severnoye      -5.42e+04   4247.574    -12.759      0.000   -6.25e+04   -4.59e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.228e+04   4371.277    -11.960      0.000   -6.08e+04   -4.37e+04
district_Ostankinsky                     -1619.6956   2942.028     -0.551      0.582   -7386.141    4146.750
district_Otradnoye                       -3.236e+04   3070.364    -10.541      0.000   -3.84e+04   -2.63e+04
district_Perovo                          -2.609e+04   3979.390     -6.555      0.000   -3.39e+04   -1.83e+04
district_Pervomayskoye                    -3.83e+04   8436.941     -4.540      0.000   -5.48e+04   -2.18e+04
district_Pokrovskoye-Streshnevo           -797.3035   2915.705     -0.273      0.785   -6512.156    4917.549
district_Preobrazhenskoye                -1.067e+04   3430.068     -3.111      0.002   -1.74e+04   -3948.594
district_Presnensky                       2.449e+05   2982.754     82.115      0.000    2.39e+05    2.51e+05
district_Prospekt Vernadskogo             7.426e+04   3386.999     21.924      0.000    6.76e+04    8.09e+04
district_Ramenki                          7.434e+04   3102.353     23.963      0.000    6.83e+04    8.04e+04
district_Rogovskoye                       4697.3142   1.16e+04      0.406      0.685    -1.8e+04    2.74e+04
district_Rostokino                       -3.715e+04   3018.976    -12.305      0.000   -4.31e+04   -3.12e+04
district_Ryazanovskoye                   -6.052e+04   6196.834     -9.767      0.000   -7.27e+04   -4.84e+04
district_Savyolovsky                      1.612e+04   2826.583      5.704      0.000    1.06e+04    2.17e+04
district_Severnoye Butovo                -2.411e+04   4455.438     -5.412      0.000   -3.28e+04   -1.54e+04
district_Severnoye Izmaylovo              -3.23e+04   4027.862     -8.019      0.000   -4.02e+04   -2.44e+04
district_Severnoye Medvedkovo            -2.914e+04   3352.133     -8.692      0.000   -3.57e+04   -2.26e+04
district_Severnoye Tushino               -1.546e+04   3133.731     -4.934      0.000   -2.16e+04   -9319.788
district_Severny                         -3.781e+04   3804.334     -9.940      0.000   -4.53e+04   -3.04e+04
district_Shchapovskoye                   -5.901e+04   7950.484     -7.422      0.000   -7.46e+04   -4.34e+04
district_Shcherbinka                     -5.828e+04   5732.769    -10.166      0.000   -6.95e+04    -4.7e+04
district_Shchukino                        4.233e+04   2991.914     14.147      0.000    3.65e+04    4.82e+04
district_Sokol                            3.134e+04   2757.579     11.363      0.000    2.59e+04    3.67e+04
district_Sokolinaya Gora                 -4.283e+04   3411.980    -12.554      0.000   -4.95e+04   -3.61e+04
district_Sokolniki                        1832.9683   3228.899      0.568      0.570   -4495.752    8161.688
district_Solntsevo                       -2.034e+04   3888.898     -5.230      0.000    -2.8e+04   -1.27e+04
district_Sosenskoye                      -5.612e+04   4954.237    -11.328      0.000   -6.58e+04   -4.64e+04
district_Strogino                         6.239e+04   3493.473     17.860      0.000    5.55e+04    6.92e+04
district_Sviblovo                        -3.138e+04   3166.999     -9.909      0.000   -3.76e+04   -2.52e+04
district_Tagansky                         1.271e+05   3238.341     39.246      0.000    1.21e+05    1.33e+05
district_Timiryazevsky                   -3528.4000   2724.445     -1.295      0.195   -8868.379    1811.579
district_Troitsk                         -5.858e+04   6668.647     -8.784      0.000   -7.17e+04   -4.55e+04
district_Troparyovo-Nikulino              5.282e+04   3658.530     14.438      0.000    4.57e+04       6e+04
district_Tsaritsyno                      -5.236e+04   4149.878    -12.617      0.000   -6.05e+04   -4.42e+04
district_Tverskoy                         2.691e+05   2974.472     90.482      0.000    2.63e+05    2.75e+05
district_Tyoply Stan                     -5461.3950   3923.844     -1.392      0.164   -1.32e+04    2229.434
district_Veshnyaki                       -6.195e+04   4096.742    -15.123      0.000      -7e+04   -5.39e+04
district_Vnukovo                         -2.172e+04   4782.460     -4.542      0.000   -3.11e+04   -1.24e+04
district_Vnukovskoye                     -5.859e+04   4423.089    -13.246      0.000   -6.73e+04   -4.99e+04
district_Voronovskoye                    -1.821e+04   1.01e+04     -1.801      0.072    -3.8e+04    1606.738
district_Voskresenskoye                  -6.751e+04   4769.019    -14.155      0.000   -7.69e+04   -5.82e+04
district_Vostochnoye Izmaylovo           -3.922e+04   4090.928     -9.588      0.000   -4.72e+04   -3.12e+04
district_Vostochny                       -5.422e+04   4510.270    -12.022      0.000   -6.31e+04   -4.54e+04
district_Voykovsky                       -1.357e+04   2831.886     -4.793      0.000   -1.91e+04   -8022.947
district_Yakimanka                        2.431e+05   3150.312     77.162      0.000    2.37e+05    2.49e+05
district_Yaroslavsky                     -3.489e+04   3635.018     -9.599      0.000    -4.2e+04   -2.78e+04
district_Yasenevo                         2.979e+04   4228.965      7.045      0.000    2.15e+04    3.81e+04
district_Yuzhnoye Butovo                  -2.41e+04   4995.497     -4.825      0.000   -3.39e+04   -1.43e+04
district_Yuzhnoye Medvedkovo             -3.865e+04   3301.750    -11.706      0.000   -4.51e+04   -3.22e+04
district_Yuzhnoye Tushino                -6449.3894   3072.424     -2.099      0.036   -1.25e+04    -427.364
district_Zamoskvorechye                   1.832e+05   3130.158     58.521      0.000    1.77e+05    1.89e+05
district_Zapadnoye Degunino               -4.45e+04   2998.799    -14.838      0.000   -5.04e+04   -3.86e+04
district_Zelenograd                      -2.107e+04   6288.637     -3.350      0.001   -3.34e+04   -8743.162
district_Zyablikovo                      -5.156e+04   4532.560    -11.376      0.000   -6.04e+04   -4.27e+04
district_Zyuzino                          2292.0691   3537.254      0.648      0.517   -4641.034    9225.172
building_type_khrushchev                 -3.796e+04    647.207    -58.655      0.000   -3.92e+04   -3.67e+04
building_type_modern_panel               -9203.5460    781.461    -11.777      0.000   -1.07e+04   -7671.864
building_type_monolith                    9676.4734    780.875     12.392      0.000    8145.940    1.12e+04
building_type_panel                       -2.45e+04    550.729    -44.480      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.098e+04   1044.605     29.660      0.000    2.89e+04     3.3e+04
has_balcony_True                          5333.8683    391.371     13.629      0.000    4566.772    6100.964
renovation_designer                         6.4e+04    602.638    106.207      0.000    6.28e+04    6.52e+04
renovation_euro                            2.78e+04    408.856     67.999      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.881e+04    464.147    -40.528      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              4746.8831   2737.113      1.734      0.083    -617.925    1.01e+04
metro_station_Bagrationovskaya           -1205.2962   2688.897     -0.448      0.654   -6475.599    4065.006
metro_station_Begovaya                    8576.1441   2656.451      3.228      0.001    3369.435    1.38e+04
metro_station_Belorusskaya                 929.1266   2684.455      0.346      0.729   -4332.471    6190.724
metro_station_Borovitskaya                 636.7696   2747.947      0.232      0.817   -4749.274    6022.813
metro_station_Chekhovskaya                8819.1097   2719.136      3.243      0.001    3489.537    1.41e+04
metro_station_Chistye Prudy               1797.6410   2678.712      0.671      0.502   -3452.700    7047.982
metro_station_Chkalovskaya                3756.9961   2760.281      1.361      0.173   -1653.221    9167.213
metro_station_Delovoy Tsentr              2544.8886   2748.181      0.926      0.354   -2841.612    7931.389
metro_station_Dinamo                      5737.6628   2512.625      2.284      0.022     812.857    1.07e+04
metro_station_Dostoevskaya                1495.1748   2651.123      0.564      0.573   -3701.091    6691.441
metro_station_Dubrovka                    2288.8960   2791.252      0.820      0.412   -3182.024    7759.816
metro_station_Elektrozavodskaya           1274.7510   2705.578      0.471      0.638   -4028.247    6577.749
metro_station_Fili                       -1261.8259   2670.359     -0.473      0.637   -6495.794    3972.142
metro_station_Filyovsky Park              4723.5876   2570.879      1.837      0.066    -315.398    9762.573
metro_station_Frunzenskaya                1.151e+04   2715.960      4.238      0.000    6188.122    1.68e+04
metro_station_Kakhovskaya                 -906.0820   2488.900     -0.364      0.716   -5784.386    3972.221
metro_station_Kantemirovskaya            -2817.6344   2489.056     -1.132      0.258   -7696.245    2060.976
metro_station_Kievskaya                   3243.2981   2696.250      1.203      0.229   -2041.418    8528.014
metro_station_Kitay-Gorod                 1312.1634   2896.032      0.453      0.650   -4364.129    6988.456

🏃 View run ols_temporal_modelado_one_hot at: http://127.0.0.1:5000/#/experiments/4/runs/c46c10ae37fc435cbe692c40eb3dad5c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
OLS temporal registrado en MLflow: experimento 'Inmobiliario - OLS Temporal'

### Interpretación

Las métricas de prueba son las que deben utilizarse para valorar la capacidad predictiva fuera de muestra. El R², AIC, BIC y los diagnósticos describen el ajuste OLS; no convierten por sí solos al modelo en definitivo. La corrida de MLflow permite comparar este resultado temporal con futuras versiones del dataset y del modelo.

## 4. Filtrado de predictores con p-value >= 0,9

Usamos los p-values del OLS temporal anterior para identificar predictores sin evidencia estadística suficiente bajo este ajuste. Se eliminan únicamente columnas predictoras con `p-value >= 0,9`; nunca se elimina la constante, el objetivo ni `periodo`.

El archivo one-hot original se conserva. Esta sección crea una copia filtrada, vuelve a ajustar OLS con el mismo corte temporal y registra una nueva corrida para comparar sus métricas con la anterior.

In [4]:
UMBRAL_PVALUE = 0.90
RUTA_SALIDA_PVALUE = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_090.csv")

variables_eliminar_pvalue = sorted(
    coeficientes_ols_temporal.loc[
        (coeficientes_ols_temporal["p_value"] >= UMBRAL_PVALUE)
        & (~coeficientes_ols_temporal["variable"].isin(["const", "price_per_sqm", "periodo"])),
        "variable"
    ].tolist()
)

df_ols_filtrado = df_ols.drop(columns=variables_eliminar_pvalue)
df_ols_filtrado.to_csv(RUTA_SALIDA_PVALUE, index=False)

df_train_filtrado = df_ols_filtrado[df_ols_filtrado["periodo"] < CORTE_TEMPORAL].copy()
df_test_filtrado = df_ols_filtrado[df_ols_filtrado["periodo"] >= CORTE_TEMPORAL].copy()
X_train_filtrado = df_train_filtrado.drop(columns=["price_per_sqm", "periodo"])
X_test_filtrado = df_test_filtrado.drop(columns=["price_per_sqm", "periodo"])
y_train_filtrado = df_train_filtrado["price_per_sqm"]
y_test_filtrado = df_test_filtrado["price_per_sqm"]

X_train_filtrado_sm = sm.add_constant(X_train_filtrado, has_constant="add")
X_test_filtrado_sm = sm.add_constant(X_test_filtrado, has_constant="add")
modelo_ols_filtrado = sm.OLS(y_train_filtrado, X_train_filtrado_sm)
resultados_ols_filtrado = modelo_ols_filtrado.fit()
predicciones_train_filtrado = resultados_ols_filtrado.predict(X_train_filtrado_sm)
predicciones_test_filtrado = resultados_ols_filtrado.predict(X_test_filtrado_sm)

metricas_ols_filtrado = {
    **calcular_metricas_regresion(y_train_filtrado, predicciones_train_filtrado, "train"),
    **calcular_metricas_regresion(y_test_filtrado, predicciones_test_filtrado, "test"),
    "r2_ols": float(resultados_ols_filtrado.rsquared),
    "r2_ajustado_ols": float(resultados_ols_filtrado.rsquared_adj),
    "aic_ols": float(resultados_ols_filtrado.aic),
    "bic_ols": float(resultados_ols_filtrado.bic),
    "f_statistic_ols": float(resultados_ols_filtrado.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_filtrado.f_pvalue)
}
omnibus_filtrado, prob_omnibus_filtrado = omni_normtest(resultados_ols_filtrado.resid)
jarque_bera_filtrado, prob_jb_filtrado, skew_filtrado, kurtosis_filtrado = jarque_bera(resultados_ols_filtrado.resid)
metricas_ols_filtrado.update({
    "omnibus_ols": float(omnibus_filtrado),
    "prob_omnibus_ols": float(prob_omnibus_filtrado),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_filtrado.resid)),
    "jarque_bera_ols": float(jarque_bera_filtrado),
    "prob_jb_ols": float(prob_jb_filtrado),
    "skew_ols": float(skew_filtrado),
    "kurtosis_ols": float(kurtosis_filtrado),
    "condition_number_ols": float(resultados_ols_filtrado.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_filtrado.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_filtrado.pvalues > 0.05).sum())
})

coeficientes_ols_filtrado = pd.DataFrame({
    "variable": resultados_ols_filtrado.params.index,
    "coeficiente": resultados_ols_filtrado.params.to_numpy(),
    "p_value": resultados_ols_filtrado.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_filtrado.pvalues.to_numpy() <= 0.05
})
residuos_test_filtrado = pd.DataFrame({
    "periodo": df_test_filtrado["periodo"].to_numpy(),
    "real": y_test_filtrado.to_numpy(),
    "prediccion": predicciones_test_filtrado.to_numpy(),
    "residuo": (y_test_filtrado.to_numpy() - predicciones_test_filtrado.to_numpy())
})

comparacion_ols = pd.DataFrame([
    {"modelo": "OLS anterior", **metricas_ols_temporal},
    {"modelo": "OLS p-value filtrado", **metricas_ols_filtrado}
])
delta_metricas = {
    f"delta_{metrica}": metricas_ols_filtrado[metrica] - metricas_ols_temporal[metrica]
    for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]
}
tabla_variables_eliminadas = coeficientes_ols_temporal[
    coeficientes_ols_temporal["variable"].isin(variables_eliminar_pvalue)
].sort_values("p_value", ascending=False)

display(tabla_variables_eliminadas)
display(comparacion_ols[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
print(resultados_ols_filtrado.summary())

RUN_OLS_ANTERIOR_ID = "8632cd73b7b84347bd6cd3ee0b2cfe4e"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_pvalue_filtrado_090"):
    mlflow.set_tag("run_anterior_id", RUN_OLS_ANTERIOR_ID)
    mlflow.log_params({
        "dataset": str(RUTA_SALIDA_PVALUE),
        "dataset_origen": str(RUTA_OLS),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "umbral_pvalue_eliminacion": UMBRAL_PVALUE,
        "n_variables_eliminadas_pvalue": len(variables_eliminar_pvalue),
        "n_predictores": X_train_filtrado.shape[1],
        "filas_entrenamiento": len(df_train_filtrado),
        "filas_prueba": len(df_test_filtrado),
        "tipo_modelo": "statsmodels_OLS_pvalue_filtrado"
    })
    mlflow.log_metrics({**metricas_ols_filtrado, **delta_metricas})
    mlflow.log_table(tabla_variables_eliminadas, artifact_file="seleccion/variables_eliminadas_pvalue_090.json")
    mlflow.log_table(comparacion_ols, artifact_file="comparacion/comparacion_ols.json")
    mlflow.log_table(coeficientes_ols_filtrado, artifact_file="modelo/coeficientes_ols_filtrado.json")
    mlflow.log_table(residuos_test_filtrado, artifact_file="diagnostico/residuos_test_filtrado.json")
    mlflow.log_text(resultados_ols_filtrado.summary().as_text(), "modelo/resumen_ols_filtrado.txt")

print(f"Variables eliminadas por p-value >= {UMBRAL_PVALUE}: {len(variables_eliminar_pvalue)}")
print(f"Archivo filtrado guardado en: {RUTA_SALIDA_PVALUE}")
print("OLS filtrado registrado en MLflow para comparación")

                           variable  coeficiente   p_value  significativa_0_05
83       district_Novofyodorovskoye  -213.007177  0.984772               False
69         district_Maryina Roshcha   154.746066  0.958605               False
194       metro_station_Park Pobedy  -155.820254  0.953916               False
245       metro_station_Ugreshskaya   160.066982  0.953830               False
34              district_Danilovsky   281.294278  0.932565               False
238        metro_station_Troparyovo   218.831280  0.931241               False
205     metro_station_Profsoyuznaya  -226.715496  0.926320               False
239          metro_station_Trubnaya  -248.214532  0.925719               False
246  metro_station_Ulitsa 1905 Goda   307.355430  0.908387               False

                 modelo      mae_test     rmse_test   r2_test  mape_test
0          OLS anterior  37085.586046  45132.632765  0.859828  23.174104
1  OLS p-value filtrado  37085.141086  45132.235880  0.859830  23.174184

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1573.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:50   Log-Likelihood:            -4.6952e+05
No. Observations:               39658   AIC:                         9.395e+05
Df Residuals:                   39409   BIC:                         9.417e+05
Df Model:                         248
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -3.122e+07   7.46e+05    -41.873      0.000   -3.27e+07   -2.98e+07
lat                                      -4.058e+04   1.08e+04     -3.767      0.000   -6.17e+04   -1.95e+04
lon                                      -3696.2902   8089.727     -0.457      0.648   -1.96e+04    1.22e+04
total_area                                   7.8489     41.112      0.191      0.849     -72.731      88.429
living_area                                 10.9808     56.659      0.194      0.846    -100.072     122.034
kitchen_area                               114.4237     70.158      1.631      0.103     -23.088     251.936
rooms                                     -266.1954    375.264     -0.709      0.478   -1001.723     469.332
floor                                      134.4375     37.924      3.545      0.000      60.105     208.770
total_floors                                39.2402     32.026      1.225      0.220     -23.531     102.012
ceiling_height                            8506.8819    920.913      9.237      0.000    6701.869    1.03e+04
metro_distance_min                        -419.4108      9.983    -42.012      0.000    -438.978    -399.844
to_center_km                             -1479.7540    112.786    -13.120      0.000   -1700.818   -1258.690
mortgage_rate_at_listing                   -94.7443     52.597     -1.801      0.072    -197.836       8.348
date_posted_year                          1.672e+04    190.710     87.667      0.000    1.63e+04    1.71e+04
date_posted_month                         1239.7762     49.115     25.242      0.000    1143.510    1336.042
building_age                                10.7635     17.088      0.630      0.529     -22.729      44.256
district_Akademichesky                    3.939e+04   2271.346     17.342      0.000    3.49e+04    4.38e+04
district_Alekseevsky                     -1178.8504   2320.167     -0.508      0.611   -5726.434    3368.733
district_Altufyevsky                     -4.019e+04   2993.113    -13.429      0.000   -4.61e+04   -3.43e+04
district_Arbat                            2.668e+05   2368.016    112.670      0.000    2.62e+05    2.71e+05
district_Babushkinsky                    -3.179e+04   2959.866    -10.739      0.000   -3.76e+04    -2.6e+04
district_Basmanny                         1.399e+05   2335.703     59.908      0.000    1.35e+05    1.45e+05
district_Begovoy                          3.261e+04   2224.060     14.661      0.000    2.82e+04     3.7e+04
district_Beskudnikovsky                  -3.832e+04   2853.175    -13.431      0.000   -4.39e+04   -3.27e+04
district_Bibirevo                        -3.644e+04   2974.241    -12.252      0.000   -4.23e+04   -3.06e+04
district_Biryulyovo Vostochnoye          -5.709e+04   3076.421    -18.556      0.000   -6.31e+04   -5.11e+04
district_Biryulyovo Zapadnoye            -5.608e+04   2913.128    -19.251      0.000   -6.18e+04   -5.04e+04
district_Bogorodskoye                    -3.817e+04   2727.032    -13.996      0.000   -4.35e+04   -3.28e+04
district_Brateyevo                       -5.614e+04   3212.933    -17.473      0.000   -6.24e+04   -4.98e+04
district_Butyrsky                        -1.086e+04   2350.574     -4.621      0.000   -1.55e+04   -6254.280
district_Chertanovo Severnoye            -4.124e+04   2542.815    -16.217      0.000   -4.62e+04   -3.63e+04
district_Chertanovo Tsentralnoye         -5.317e+04   2594.975    -20.490      0.000   -5.83e+04   -4.81e+04
district_Chertanovo Yuzhnoye             -4.641e+04   2974.366    -15.604      0.000   -5.22e+04   -4.06e+04
district_Cheryomushki                     4.424e+04   2432.163     18.191      0.000    3.95e+04     4.9e+04
district_Desyonovskoye                   -5.721e+04   2593.261    -22.063      0.000   -6.23e+04   -5.21e+04
district_Dmitrovsky                       -4.22e+04   2935.882    -14.374      0.000    -4.8e+04   -3.64e+04
district_Donskoy                          1.585e+04   2410.336      6.574      0.000    1.11e+04    2.06e+04
district_Dorogomilovo                     1.346e+05   2313.330     58.188      0.000     1.3e+05    1.39e+05
district_Fili-Davydkovo                   3.952e+04   2288.050     17.274      0.000     3.5e+04     4.4e+04
district_Filimonkovskoye                 -7.288e+04   2294.591    -31.761      0.000   -7.74e+04   -6.84e+04
district_Filyovsky Park                   5.568e+04   2296.142     24.249      0.000    5.12e+04    6.02e+04
district_Gagarinsky                       8.085e+04   2348.130     34.432      0.000    7.62e+04    8.55e+04
district_Golovinsky                      -3.284e+04   2614.503    -12.560      0.000    -3.8e+04   -2.77e+04
district_Golyanovo                       -5.083e+04   3383.454    -15.023      0.000   -5.75e+04   -4.42e+04
district_Ivanovskoye                     -4.769e+04   3375.775    -14.128      0.000   -5.43e+04   -4.11e+04
district_Izmaylovo                       -2.159e+04   2990.596     -7.220      0.000   -2.75e+04   -1.57e+04
district_Khamovniki                       2.911e+05   2329.237    124.988      0.000    2.87e+05    2.96e+05
district_Khoroshyovo-Mnyovniki            2.246e+04   2400.284      9.359      0.000    1.78e+04    2.72e+04
district_Khoroshyovsky                    4.075e+04   2313.790     17.610      0.000    3.62e+04    4.53e+04
district_Khovrino                        -4.061e+04   2907.978    -13.964      0.000   -4.63e+04   -3.49e+04
district_Kievsky                          1.769e+04   3171.190      5.577      0.000    1.15e+04    2.39e+04
district_Klyonovskoye                    -2.389e+04   4748.426     -5.032      0.000   -3.32e+04   -1.46e+04
district_Kokoshkino                       -6.37e+04   2553.632    -24.944      0.000   -6.87e+04   -5.87e+04
district_Konkovo                          2599.7352   2268.751      1.146      0.252   -1847.072    7046.542
district_Koptevo                         -2.813e+04   2634.415    -10.678      0.000   -3.33e+04    -2.3e+04
district_Kosino-Ukhtomsky                -5.482e+04   3642.949    -15.048      0.000    -6.2e+04   -4.77e+04
district_Kotlovka                         1.203e+04   2400.249      5.013      0.000    7328.154    1.67e+04
district_Krasnopakhorskoye               -5.901e+04   2548.207    -23.158      0.000    -6.4e+04    -5.4e+04
district_Krasnoselsky                     1.265e+05   2421.782     52.232      0.000    1.22e+05    1.31e+05
district_Krylatskoye                      5.413e+04   2464.972     21.958      0.000    4.93e+04     5.9e+04
district_Kuntsevo                         1.664e+04   2372.862      7.013      0.000     1.2e+04    2.13e+04
district_Kurkino                          2.119e+04   3372.378      6.283      0.000    1.46e+04    2.78e+04
district_Levoberezhny                    -2.291e+04   2829.863     -8.097      0.000   -2.85e+04   -1.74e+04
district_Lianozovo                       -3.734e+04   3223.107    -11.586      0.000   -4.37e+04    -3.1e+04
district_Lomonosovsky                     7.406e+04   2318.573     31.942      0.000    6.95e+04    7.86e+04
district_Losinoostrovsky                 -3.166e+04   3183.548     -9.946      0.000   -3.79e+04   -2.54e+04
district_Marfino                         -3.578e+04   2522.429    -14.184      0.000   -4.07e+04   -3.08e+04
district_Marushkinskoye                  -6.392e+04   2258.836    -28.300      0.000   -6.84e+04   -5.95e+04
district_Meshchansky                      1.561e+05   2285.705     68.310      0.000    1.52e+05    1.61e+05
district_Metrogorodok                     -4.64e+04   3059.915    -15.163      0.000   -5.24e+04   -4.04e+04
district_Mikhaylovo-Yartsevskoye         -4.631e+04   2454.500    -18.866      0.000   -5.11e+04   -4.15e+04
district_Mitino                          -1.312e+04   3298.084     -3.979      0.000   -1.96e+04   -6660.169
district_Molzhaninovsky                  -3.094e+04   4155.539     -7.445      0.000   -3.91e+04   -2.28e+04
district_Moskovsky                       -5.735e+04   2298.046    -24.955      0.000   -6.19e+04   -5.28e+04
district_Moskvorechye-Saburovo           -4.312e+04   2690.297    -16.028      0.000   -4.84e+04   -3.78e+04
district_Mosrentgen                      -7.011e+04   2515.650    -27.869      0.000    -7.5e+04   -6.52e+04
district_Mozhaysky                        1677.9705   2394.530      0.701      0.483   -3015.366    6371.307
district_Nagatino-Sadovniki              -2.652e+04   2595.311    -10.218      0.000   -3.16e+04   -2.14e+04
district_Nagatinsky Zaton                -2.113e+04   2640.124     -8.002      0.000   -2.63e+04    -1.6e+04
district_Nagorny                         -1.794e+04   2562.015     -7.003      0.000    -2.3e+04   -1.29e+04
district_Novo-Peredelkino                -2.618e+04   2330.622    -11.234      0.000   -3.07e+04   -2.16e+04
district_Novogireyevo                    -3.966e+04   3224.061    -12.302      0.000    -4.6e+04   -3.33e+04
district_Novokosino                      -4.041e+04   3773.593    -10.710      0.000   -4.78e+04    -3.3e+04
district_Obruchevsky                      2.189e+04   2385.918      9.177      0.000    1.72e+04    2.66e+04
district_Ochakovo-Matveyevskoye            685.9152   2282.655      0.300      0.764   -3788.144    5159.974
district_Orekhovo-Borisovo Severnoye     -5.438e+04   3062.255    -17.759      0.000   -6.04e+04   -4.84e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.247e+04   3116.648    -16.834      0.000   -5.86e+04   -4.64e+04
district_Ostankinsky                     -1748.4634   2466.760     -0.709      0.478   -6583.373    3086.447
district_Otradnoye                       -3.245e+04   2758.024    -11.766      0.000   -3.79e+04    -2.7e+04
district_Perovo                          -2.629e+04   3252.366     -8.082      0.000   -3.27e+04   -1.99e+04
district_Pervomayskoye                   -3.817e+04   2477.419    -15.408      0.000    -4.3e+04   -3.33e+04
district_Pokrovskoye-Streshnevo           -833.3778   2552.047     -0.327      0.744   -5835.451    4168.696
district_Preobrazhenskoye                -1.084e+04   2778.408     -3.902      0.000   -1.63e+04   -5395.442
district_Presnensky                       2.448e+05   2371.877    103.213      0.000     2.4e+05    2.49e+05
district_Prospekt Vernadskogo             7.415e+04   2297.928     32.267      0.000    6.96e+04    7.87e+04
district_Ramenki                          7.422e+04   2273.698     32.645      0.000    6.98e+04    7.87e+04
district_Rogovskoye                       4866.3000   3002.626      1.621      0.105   -1018.919    1.08e+04
district_Rostokino                       -3.727e+04   2567.677    -14.517      0.000   -4.23e+04   -3.22e+04
district_Ryazanovskoye                   -6.062e+04   3065.514    -19.773      0.000   -6.66e+04   -5.46e+04
district_Savyolovsky                      1.599e+04   2303.730      6.942      0.000    1.15e+04    2.05e+04
district_Severnoye Butovo                -2.425e+04   2735.425     -8.865      0.000   -2.96e+04   -1.89e+04
district_Severnoye Izmaylovo             -3.247e+04   3454.214     -9.401      0.000   -3.92e+04   -2.57e+04
district_Severnoye Medvedkovo            -2.921e+04   3077.590     -9.493      0.000   -3.52e+04   -2.32e+04
district_Severnoye Tushino               -1.547e+04   2813.285     -5.500      0.000    -2.1e+04   -9959.029
district_Severny                         -3.784e+04   3641.745    -10.391      0.000    -4.5e+04   -3.07e+04
district_Shchapovskoye                   -5.908e+04   3909.668    -15.112      0.000   -6.67e+04   -5.14e+04
district_Shcherbinka                      -5.84e+04   3176.369    -18.384      0.000   -6.46e+04   -5.22e+04
district_Shchukino                        4.227e+04   2628.981     16.079      0.000    3.71e+04    4.74e+04
district_Sokol                            3.126e+04   2406.364     12.989      0.000    2.65e+04     3.6e+04
district_Sokolinaya Gora                 -4.301e+04   2679.509    -16.052      0.000   -4.83e+04   -3.78e+04
district_Sokolniki                        1665.3445   2569.527      0.648      0.517   -3370.990    6701.679
district_Solntsevo                       -2.037e+04   2188.401     -9.309      0.000   -2.47e+04   -1.61e+04
district_Sosenskoye                      -5.619e+04   2349.851    -23.910      0.000   -6.08e+04   -5.16e+04
district_Strogino                         6.237e+04   3067.944     20.329      0.000    5.64e+04    6.84e+04
district_Sviblovo                        -3.149e+04   2782.378    -11.319      0.000   -3.69e+04    -2.6e+04
district_Tagansky                         1.269e+05   2427.370     52.282      0.000    1.22e+05    1.32e+05
district_Timiryazevsky                   -3633.9445   2300.675     -1.580      0.114   -8143.322     875.433
district_Troitsk                         -5.857e+04   2412.213    -24.281      0.000   -6.33e+04   -5.38e+04
district_Troparyovo-Nikulino              5.281e+04   2364.127     22.338      0.000    4.82e+04    5.74e+04
district_Tsaritsyno                      -5.254e+04   2891.222    -18.172      0.000   -5.82e+04   -4.69e+04
district_Tverskoy                          2.69e+05   2295.834    117.154      0.000    2.64e+05    2.73e+05
district_Tyoply Stan                     -5544.0095   2300.788     -2.410      0.016   -1.01e+04   -1034.409
district_Veshnyaki                       -6.216e+04   3315.674    -18.747      0.000   -6.87e+04   -5.57e+04
district_Vnukovo                          -2.17e+04   2367.430     -9.168      0.000   -2.63e+04   -1.71e+04
district_Vnukovskoye                     -5.859e+04   2328.544    -25.163      0.000   -6.32e+04    -5.4e+04
district_Voronovskoye                    -1.814e+04   3085.013     -5.879      0.000   -2.42e+04   -1.21e+04
district_Voskresenskoye                  -6.757e+04   2342.772    -28.843      0.000   -7.22e+04    -6.3e+04
district_Vostochnoye Izmaylovo           -3.941e+04   3471.572    -11.351      0.000   -4.62e+04   -3.26e+04
district_Vostochny                       -5.439e+04   3974.854    -13.685      0.000   -6.22e+04   -4.66e+04
district_Voykovsky                       -1.365e+04   2505.923     -5.445      0.000   -1.86e+04   -8733.633
district_Yakimanka                        2.429e+05   2406.386    100.947      0.000    2.38e+05    2.48e+05
district_Yaroslavsky                       -3.5e+04   3278.598    -10.676      0.000   -4.14e+04   -2.86e+04
district_Yasenevo                         2.967e+04   2687.274     11.042      0.000    2.44e+04    3.49e+04
district_Yuzhnoye Butovo                 -2.422e+04   2806.543     -8.630      0.000   -2.97e+04   -1.87e+04
district_Yuzhnoye Medvedkovo             -3.874e+04   2996.145    -12.930      0.000   -4.46e+04   -3.29e+04
district_Yuzhnoye Tushino                -6470.3914   2722.292     -2.377      0.017   -1.18e+04   -1134.633
district_Zamoskvorechye                    1.83e+05   2335.252     78.364      0.000    1.78e+05    1.88e+05
district_Zapadnoye Degunino              -4.455e+04   2747.534    -16.215      0.000   -4.99e+04   -3.92e+04
district_Zelenograd                      -2.087e+04   5376.850     -3.882      0.000   -3.14e+04   -1.03e+04
district_Zyablikovo                      -5.175e+04   3328.071    -15.551      0.000   -5.83e+04   -4.52e+04
district_Zyuzino                          2123.7811   2448.383      0.867      0.386   -2675.108    6922.671
building_type_khrushchev                 -3.796e+04    647.086    -58.662      0.000   -3.92e+04   -3.67e+04
building_type_modern_panel               -9204.6308    781.274    -11.782      0.000   -1.07e+04   -7673.316
building_type_monolith                    9674.3607    780.665     12.392      0.000    8144.239    1.12e+04
building_type_panel                      -2.449e+04    550.620    -44.486      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.099e+04   1044.411     29.667      0.000    2.89e+04     3.3e+04
has_balcony_True                          5333.9098    391.304     13.631      0.000    4566.944    6100.876
renovation_designer                       6.401e+04    602.489    106.234      0.000    6.28e+04    6.52e+04
renovation_euro                            2.78e+04    408.772     68.013      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.881e+04    464.041    -40.539      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              4750.2022   2093.020      2.270      0.023     647.832    8852.573
metro_station_Bagrationovskaya           -1207.6404   2016.999     -0.599      0.549   -5161.007    2745.726
metro_station_Begovaya                    8570.6963   1976.271      4.337      0.000    4697.158    1.24e+04
metro_station_Belorusskaya                 929.3554   2020.808      0.460      0.646   -3031.477    4890.187
metro_station_Borovitskaya                 640.9296   2105.261      0.304      0.761   -3485.432    4767.291
metro_station_Chekhovskaya                8823.2050   2068.970      4.265      0.000    4767.974    1.29e+04
metro_station_Chistye Prudy               1800.6156   2014.833      0.894      0.371   -2148.506    5749.738
metro_station_Chkalovskaya                3760.7159   2120.483      1.774      0.076    -395.483    7916.914
metro_station_Delovoy Tsentr              2542.3898   2096.765      1.213      0.225   -1567.321    6652.101
metro_station_Dinamo                      5733.0625   1779.426      3.222      0.001    2245.344    9220.781
metro_station_Dostoevskaya                1497.5387   1979.003      0.757      0.449   -2381.355    5376.433
metro_station_Dubrovka                    2294.9788   2153.330      1.066      0.287   -1925.600    6515.558
metro_station_Elektrozavodskaya           1277.7253   2047.193      0.624      0.533   -2734.823    5290.274
metro_station_Fili                       -1262.2250   1993.607     -0.633      0.527   -5169.743    2645.293
metro_station_Filyovsky Park              4723.2226   1853.131      2.549      0.011    1091.041    8355.405
metro_station_Frunzenskaya                1.151e+04   2056.227      5.599      0.000    7482.212    1.55e+04
metro_station_Kakhovskaya                 -902.4880   1718.049     -0.525      0.599   -4269.905    2464.929
metro_station_Kantemirovskaya            -2820.5090   1719.569     -1.640      0.101   -6190.905     549.887
metro_station_Kievskaya                   3244.1819   2034.565      1.595      0.111    -743.615    7231.979
metro_station_Kitay-Gorod                 1313.8208   2293.619      0.573      0.567   -3181.728    5809.370
metro_station_Komsomolskaya               2.147e+04   2018.429     10.637      0.000    1.75e+04    2.54e+04
metro_station_Kozhukhovskaya              -720.0577   2130.890     -0.338      0.735   -4896.653    3456.537
metro_station_Krasnopresnenskaya          2.261e+04   1952.913     11.579      0.000    1.88e+04    2.64e+04

🏃 View run ols_temporal_pvalue_filtrado_090 at: http://127.0.0.1:5000/#/experiments/4/runs/04b678f6c4474626be4a11c497e37497
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Variables eliminadas por p-value >= 0.9: 9
Archivo filtrado guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_090.csv
OLS filtrado registrado en MLflow para comparación

### Interpretación

El nuevo modelo debe compararse principalmente por MAE, RMSE, R² y MAPE en el conjunto temporal de prueba. El filtrado por p-value reduce la cantidad de predictores, pero solo conviene conservarlo si mantiene o mejora el desempeño fuera de muestra y no deteriora la estabilidad del modelo.

## 5. Filtrado progresivo de predictores con p-value >= 0,7

Partimos del dataset y del modelo que ya fueron filtrados con `p-value >= 0,9`. Sobre ese resultado eliminamos los predictores restantes cuyo p-value sea mayor o igual a `0,7`, conservando siempre la constante, `price_per_sqm` y `periodo`.

El nuevo modelo utiliza el mismo corte temporal y se registra en el mismo experimento MLflow para compararlo con la versión de `p-value >= 0,9`.

In [5]:
UMBRAL_PVALUE_070 = 0.70
RUTA_SALIDA_PVALUE_070 = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_070.csv")

variables_eliminar_pvalue_070 = sorted(
    coeficientes_ols_filtrado.loc[
        (coeficientes_ols_filtrado["p_value"] >= UMBRAL_PVALUE_070)
        & (~coeficientes_ols_filtrado["variable"].isin(["const", "price_per_sqm", "periodo"])),
        "variable"
    ].tolist()
)

df_ols_filtrado_070 = df_ols_filtrado.drop(columns=variables_eliminar_pvalue_070)
df_ols_filtrado_070.to_csv(RUTA_SALIDA_PVALUE_070, index=False)

df_train_070 = df_ols_filtrado_070[df_ols_filtrado_070["periodo"] < CORTE_TEMPORAL].copy()
df_test_070 = df_ols_filtrado_070[df_ols_filtrado_070["periodo"] >= CORTE_TEMPORAL].copy()
X_train_070 = df_train_070.drop(columns=["price_per_sqm", "periodo"])
X_test_070 = df_test_070.drop(columns=["price_per_sqm", "periodo"])
y_train_070 = df_train_070["price_per_sqm"]
y_test_070 = df_test_070["price_per_sqm"]

X_train_070_sm = sm.add_constant(X_train_070, has_constant="add")
X_test_070_sm = sm.add_constant(X_test_070, has_constant="add")
modelo_ols_070 = sm.OLS(y_train_070, X_train_070_sm)
resultados_ols_070 = modelo_ols_070.fit()
predicciones_train_070 = resultados_ols_070.predict(X_train_070_sm)
predicciones_test_070 = resultados_ols_070.predict(X_test_070_sm)

metricas_ols_070 = {
    **calcular_metricas_regresion(y_train_070, predicciones_train_070, "train"),
    **calcular_metricas_regresion(y_test_070, predicciones_test_070, "test"),
    "r2_ols": float(resultados_ols_070.rsquared),
    "r2_ajustado_ols": float(resultados_ols_070.rsquared_adj),
    "aic_ols": float(resultados_ols_070.aic),
    "bic_ols": float(resultados_ols_070.bic),
    "f_statistic_ols": float(resultados_ols_070.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_070.f_pvalue)
}
omnibus_070, prob_omnibus_070 = omni_normtest(resultados_ols_070.resid)
jarque_bera_070, prob_jb_070, skew_070, kurtosis_070 = jarque_bera(resultados_ols_070.resid)
metricas_ols_070.update({
    "omnibus_ols": float(omnibus_070),
    "prob_omnibus_ols": float(prob_omnibus_070),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_070.resid)),
    "jarque_bera_ols": float(jarque_bera_070),
    "prob_jb_ols": float(prob_jb_070),
    "skew_ols": float(skew_070),
    "kurtosis_ols": float(kurtosis_070),
    "condition_number_ols": float(resultados_ols_070.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_070.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_070.pvalues > 0.05).sum())
})

coeficientes_ols_070 = pd.DataFrame({
    "variable": resultados_ols_070.params.index,
    "coeficiente": resultados_ols_070.params.to_numpy(),
    "p_value": resultados_ols_070.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_070.pvalues.to_numpy() <= 0.05
})
residuos_test_070 = pd.DataFrame({
    "periodo": df_test_070["periodo"].to_numpy(),
    "real": y_test_070.to_numpy(),
    "prediccion": predicciones_test_070.to_numpy(),
    "residuo": (y_test_070.to_numpy() - predicciones_test_070.to_numpy())
})

comparacion_ols_070 = pd.DataFrame([
    {"modelo": "OLS p-value 0.90", **metricas_ols_filtrado},
    {"modelo": "OLS p-value 0.70", **metricas_ols_070}
])
delta_metricas_070 = {
    f"delta_{metrica}": metricas_ols_070[metrica] - metricas_ols_filtrado[metrica]
    for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]
}
tabla_variables_eliminadas_070 = coeficientes_ols_filtrado[
    coeficientes_ols_filtrado["variable"].isin(variables_eliminar_pvalue_070)
].sort_values("p_value", ascending=False)

display(tabla_variables_eliminadas_070)
display(comparacion_ols_070[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
print(resultados_ols_070.summary())

RUN_OLS_P90_ID = "45a11b38934a495eb7a148c8fa9d3f92"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_pvalue_filtrado_070"):
    mlflow.set_tag("run_anterior_id", RUN_OLS_P90_ID)
    mlflow.log_params({
        "dataset": str(RUTA_SALIDA_PVALUE_070),
        "dataset_origen": str(RUTA_SALIDA_PVALUE),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "umbral_pvalue_eliminacion": UMBRAL_PVALUE_070,
        "n_variables_eliminadas_pvalue": len(variables_eliminar_pvalue_070),
        "n_predictores": X_train_070.shape[1],
        "filas_entrenamiento": len(df_train_070),
        "filas_prueba": len(df_test_070),
        "tipo_modelo": "statsmodels_OLS_pvalue_filtrado_070"
    })
    mlflow.log_metrics({**metricas_ols_070, **delta_metricas_070})
    mlflow.log_table(tabla_variables_eliminadas_070, artifact_file="seleccion/variables_eliminadas_pvalue_070.json")
    mlflow.log_table(comparacion_ols_070, artifact_file="comparacion/comparacion_ols_070.json")
    mlflow.log_table(coeficientes_ols_070, artifact_file="modelo/coeficientes_ols_070.json")
    mlflow.log_table(residuos_test_070, artifact_file="diagnostico/residuos_test_070.json")
    mlflow.log_text(resultados_ols_070.summary().as_text(), "modelo/resumen_ols_070.txt")

print(f"Variables eliminadas por p-value >= {UMBRAL_PVALUE_070}: {len(variables_eliminar_pvalue_070)}")
print(f"Archivo filtrado guardado en: {RUTA_SALIDA_PVALUE_070}")
print("OLS filtrado 0.70 registrado en MLflow para comparación")

,variable,coeficiente,p_value,significativa_0_05
3,total_area,7.848934,0.848591,False
4,living_area,10.980802,0.846329,False
84,district_Ochakovo-Matveyevskoye,685.915188,0.763805,False
154,metro_station_Borovitskaya,640.929623,0.760793,False
91,district_Pokrovskoye-Streshnevo,-833.377776,0.744008,False
171,metro_station_Kozhukhovskaya,-720.057679,0.735430,False
223,metro_station_Sretensky Bulvar,736.784795,0.727455,False

             modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS p-value 0.90  37085.141086  45132.235880  0.859830  23.174184
1  OLS p-value 0.70  37085.870554  45133.296237  0.859824  23.174562

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1619.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:52   Log-Likelihood:            -4.6952e+05
No. Observations:               39658   AIC:                         9.395e+05
Df Residuals:                   39416   BIC:                         9.416e+05
Df Model:                         241
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                     -3.11e+07   6.98e+05    -44.547      0.000   -3.25e+07   -2.97e+07
lat                                      -4.283e+04   9272.279     -4.619      0.000    -6.1e+04   -2.47e+04
lon                                      -3464.4685   7789.569     -0.445      0.656   -1.87e+04    1.18e+04
kitchen_area                               113.8598     70.148      1.623      0.105     -23.633     251.352
rooms                                      -43.9523    195.983     -0.224      0.823    -428.084     340.179
floor                                      134.3075     37.916      3.542      0.000      59.992     208.623
total_floors                                39.3224     32.021      1.228      0.219     -23.439     102.084
ceiling_height                            8508.2959    920.798      9.240      0.000    6703.509    1.03e+04
metro_distance_min                        -419.5170      9.921    -42.286      0.000    -438.962    -400.072
to_center_km                             -1493.0956    108.765    -13.728      0.000   -1706.278   -1279.913
mortgage_rate_at_listing                   -95.2637     52.589     -1.811      0.070    -198.339       7.812
date_posted_year                          1.672e+04    190.677     87.686      0.000    1.63e+04    1.71e+04
date_posted_month                         1239.4715     49.108     25.240      0.000    1143.219    1335.725
building_age                                10.8422     17.086      0.635      0.526     -22.646      44.331
district_Akademichesky                    3.922e+04   2191.180     17.901      0.000    3.49e+04    4.35e+04
district_Alekseevsky                     -1066.2197   2228.346     -0.478      0.632   -5433.832    3301.393
district_Altufyevsky                     -3.978e+04   2742.185    -14.507      0.000   -4.52e+04   -3.44e+04
district_Arbat                            2.667e+05   2268.352    117.587      0.000    2.62e+05    2.71e+05
district_Babushkinsky                    -3.147e+04   2813.934    -11.185      0.000    -3.7e+04    -2.6e+04
district_Basmanny                         1.399e+05   2278.221     61.410      0.000    1.35e+05    1.44e+05
district_Begovoy                          3.267e+04   2086.899     15.654      0.000    2.86e+04    3.68e+04
district_Beskudnikovsky                  -3.795e+04   2600.438    -14.594      0.000    -4.3e+04   -3.29e+04
district_Bibirevo                        -3.605e+04   2745.478    -13.132      0.000   -4.14e+04   -3.07e+04
district_Biryulyovo Vostochnoye          -5.738e+04   3017.796    -19.013      0.000   -6.33e+04   -5.15e+04
district_Biryulyovo Zapadnoye            -5.635e+04   2857.819    -19.717      0.000   -6.19e+04   -5.07e+04
district_Bogorodskoye                    -3.803e+04   2672.576    -14.231      0.000   -4.33e+04   -3.28e+04
district_Brateyevo                       -5.637e+04   3179.143    -17.732      0.000   -6.26e+04   -5.01e+04
district_Butyrsky                        -1.073e+04   2210.985     -4.852      0.000   -1.51e+04   -6394.995
district_Chertanovo Severnoye            -4.144e+04   2488.406    -16.655      0.000   -4.63e+04   -3.66e+04
district_Chertanovo Tsentralnoye         -5.338e+04   2541.807    -20.999      0.000   -5.84e+04   -4.84e+04
district_Chertanovo Yuzhnoye             -4.666e+04   2925.514    -15.948      0.000   -5.24e+04   -4.09e+04
district_Cheryomushki                     4.406e+04   2359.754     18.670      0.000    3.94e+04    4.87e+04
district_Desyonovskoye                   -5.745e+04   2535.091    -22.660      0.000   -6.24e+04   -5.25e+04
district_Dmitrovsky                      -4.181e+04   2660.431    -15.716      0.000    -4.7e+04   -3.66e+04
district_Donskoy                          1.569e+04   2338.646      6.711      0.000    1.11e+04    2.03e+04
district_Dorogomilovo                     1.345e+05   2201.840     61.103      0.000     1.3e+05    1.39e+05
district_Fili-Davydkovo                   3.952e+04   2140.902     18.459      0.000    3.53e+04    4.37e+04
district_Filimonkovskoye                 -7.304e+04   2242.686    -32.569      0.000   -7.74e+04   -6.86e+04
district_Filyovsky Park                   5.569e+04   2149.485     25.909      0.000    5.15e+04    5.99e+04
district_Gagarinsky                       8.071e+04   2264.851     35.635      0.000    7.63e+04    8.51e+04
district_Golovinsky                      -3.254e+04   2351.984    -13.837      0.000   -3.72e+04   -2.79e+04
district_Golyanovo                       -5.065e+04   3356.618    -15.091      0.000   -5.72e+04   -4.41e+04
district_Ivanovskoye                     -4.767e+04   3373.814    -14.129      0.000   -5.43e+04   -4.11e+04
district_Izmaylovo                       -2.151e+04   2972.515     -7.237      0.000   -2.73e+04   -1.57e+04
district_Khamovniki                        2.91e+05   2229.600    130.528      0.000    2.87e+05    2.95e+05
district_Khoroshyovo-Mnyovniki            2.259e+04   2219.936     10.174      0.000    1.82e+04    2.69e+04
district_Khoroshyovsky                    4.079e+04   2167.018     18.823      0.000    3.65e+04     4.5e+04
district_Khovrino                         -4.02e+04   2587.152    -15.539      0.000   -4.53e+04   -3.51e+04
district_Kievsky                          1.788e+04   3063.325      5.838      0.000    1.19e+04    2.39e+04
district_Klyonovskoye                    -2.434e+04   4543.262     -5.357      0.000   -3.32e+04   -1.54e+04
district_Kokoshkino                      -6.357e+04   2374.136    -26.778      0.000   -6.82e+04   -5.89e+04
district_Konkovo                          2411.8193   2196.106      1.098      0.272   -1892.601    6716.239
district_Koptevo                         -2.785e+04   2394.051    -11.635      0.000   -3.25e+04   -2.32e+04
district_Kosino-Ukhtomsky                -5.488e+04   3638.279    -15.085      0.000    -6.2e+04   -4.78e+04
district_Kotlovka                         1.185e+04   2336.952      5.070      0.000    7267.947    1.64e+04
district_Krasnopakhorskoye               -5.921e+04   2506.744    -23.622      0.000   -6.41e+04   -5.43e+04
district_Krasnoselsky                     1.265e+05   2356.345     53.685      0.000    1.22e+05    1.31e+05
district_Krylatskoye                      5.424e+04   2269.024     23.906      0.000    4.98e+04    5.87e+04
district_Kuntsevo                         1.667e+04   2221.249      7.506      0.000    1.23e+04     2.1e+04
district_Kurkino                          2.171e+04   2939.013      7.387      0.000    1.59e+04    2.75e+04
district_Levoberezhny                    -2.255e+04   2510.229     -8.982      0.000   -2.75e+04   -1.76e+04
district_Lianozovo                       -3.689e+04   2947.600    -12.515      0.000   -4.27e+04   -3.11e+04
district_Lomonosovsky                     7.392e+04   2229.416     33.157      0.000    6.96e+04    7.83e+04
district_Losinoostrovsky                 -3.134e+04   3052.463    -10.266      0.000   -3.73e+04   -2.54e+04
district_Marfino                         -3.554e+04   2349.067    -15.129      0.000   -4.01e+04   -3.09e+04
district_Marushkinskoye                  -6.392e+04   2166.571    -29.501      0.000   -6.82e+04   -5.97e+04
district_Meshchansky                      1.561e+05   2204.640     70.820      0.000    1.52e+05     1.6e+05
district_Metrogorodok                    -4.623e+04   3015.946    -15.329      0.000   -5.21e+04   -4.03e+04
district_Mikhaylovo-Yartsevskoye         -4.649e+04   2422.458    -19.193      0.000   -5.12e+04   -4.17e+04
district_Mitino                           -1.27e+04   2937.009     -4.326      0.000   -1.85e+04   -6948.292
district_Molzhaninovsky                   -3.02e+04   3638.562     -8.299      0.000   -3.73e+04   -2.31e+04
district_Moskovsky                       -5.742e+04   2227.041    -25.784      0.000   -6.18e+04   -5.31e+04
district_Moskvorechye-Saburovo           -4.336e+04   2645.544    -16.389      0.000   -4.85e+04   -3.82e+04
district_Mosrentgen                      -7.029e+04   2456.420    -28.616      0.000   -7.51e+04   -6.55e+04
district_Mozhaysky                        1698.9850   2239.783      0.759      0.448   -2691.043    6089.013
district_Nagatino-Sadovniki              -2.674e+04   2549.181    -10.488      0.000   -3.17e+04   -2.17e+04
district_Nagatinsky Zaton                -2.134e+04   2602.768     -8.200      0.000   -2.64e+04   -1.62e+04
district_Nagorny                         -1.813e+04   2505.895     -7.235      0.000    -2.3e+04   -1.32e+04
district_Novo-Peredelkino                -2.618e+04   2203.345    -11.881      0.000   -3.05e+04   -2.19e+04
district_Novogireyevo                    -3.968e+04   3221.547    -12.318      0.000    -4.6e+04   -3.34e+04
district_Novokosino                      -4.041e+04   3771.852    -10.713      0.000   -4.78e+04    -3.3e+04
district_Obruchevsky                      2.173e+04   2313.798      9.390      0.000    1.72e+04    2.63e+04
district_Orekhovo-Borisovo Severnoye     -5.463e+04   3019.925    -18.090      0.000   -6.05e+04   -4.87e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.271e+04   3069.679    -17.172      0.000   -5.87e+04   -4.67e+04
district_Ostankinsky                     -1572.7387   2345.904     -0.670      0.503   -6170.768    3025.290
district_Otradnoye                       -3.214e+04   2569.439    -12.507      0.000   -3.72e+04   -2.71e+04
district_Perovo                          -2.634e+04   3247.654     -8.110      0.000   -3.27e+04      -2e+04
district_Pervomayskoye                   -3.819e+04   2435.642    -15.678      0.000    -4.3e+04   -3.34e+04
district_Preobrazhenskoye                -1.078e+04   2742.474     -3.929      0.000   -1.62e+04   -5400.101
district_Presnensky                       2.448e+05   2264.879    108.070      0.000     2.4e+05    2.49e+05
district_Prospekt Vernadskogo               7.4e+04   2202.695     33.597      0.000    6.97e+04    7.83e+04
district_Ramenki                          7.414e+04   2164.048     34.258      0.000    6.99e+04    7.84e+04
district_Rogovskoye                       4685.5675   2972.750      1.576      0.115   -1141.095    1.05e+04
district_Rostokino                       -3.706e+04   2443.706    -15.166      0.000   -4.19e+04   -3.23e+04
district_Ryazanovskoye                   -6.091e+04   2987.135    -20.389      0.000   -6.68e+04   -5.51e+04
district_Savyolovsky                      1.606e+04   2181.853      7.361      0.000    1.18e+04    2.03e+04
district_Severnoye Butovo                 -2.45e+04   2678.841     -9.147      0.000   -2.98e+04   -1.93e+04
district_Severnoye Izmaylovo             -3.231e+04   3432.789     -9.412      0.000    -3.9e+04   -2.56e+04
district_Severnoye Medvedkovo            -2.885e+04   2878.836    -10.021      0.000   -3.45e+04   -2.32e+04
district_Severnoye Tushino               -1.511e+04   2467.161     -6.123      0.000   -1.99e+04   -1.03e+04
district_Severny                         -3.727e+04   3308.343    -11.265      0.000   -4.38e+04   -3.08e+04
district_Shchapovskoye                   -5.947e+04   3771.933    -15.768      0.000   -6.69e+04   -5.21e+04
district_Shcherbinka                      -5.87e+04   3099.716    -18.937      0.000   -6.48e+04   -5.26e+04
district_Shchukino                        4.251e+04   2370.336     17.934      0.000    3.79e+04    4.72e+04
district_Sokol                            3.142e+04   2226.240     14.112      0.000    2.71e+04    3.58e+04
district_Sokolinaya Gora                   -4.3e+04   2657.253    -16.182      0.000   -4.82e+04   -3.78e+04
district_Sokolniki                        1712.0882   2515.263      0.681      0.496   -3217.888    6642.065
district_Solntsevo                       -2.045e+04   2083.283     -9.815      0.000   -2.45e+04   -1.64e+04
district_Sosenskoye                      -5.638e+04   2298.237    -24.533      0.000   -6.09e+04   -5.19e+04
district_Strogino                         6.265e+04   2815.031     22.256      0.000    5.71e+04    6.82e+04
district_Sviblovo                        -3.126e+04   2644.395    -11.820      0.000   -3.64e+04   -2.61e+04
district_Tagansky                         1.268e+05   2370.437     53.494      0.000    1.22e+05    1.31e+05
district_Timiryazevsky                   -3473.7556   2141.048     -1.622      0.105   -7670.262     722.750
district_Troitsk                         -5.875e+04   2375.256    -24.736      0.000   -6.34e+04   -5.41e+04
district_Troparyovo-Nikulino              5.266e+04   2271.686     23.180      0.000    4.82e+04    5.71e+04
district_Tsaritsyno                      -5.278e+04   2844.144    -18.556      0.000   -5.84e+04   -4.72e+04
district_Tverskoy                         2.689e+05   2198.933    122.306      0.000    2.65e+05    2.73e+05
district_Tyoply Stan                     -5721.2441   2232.814     -2.562      0.010   -1.01e+04   -1344.874
district_Veshnyaki                       -6.224e+04   3313.094    -18.785      0.000   -6.87e+04   -5.57e+04
district_Vnukovo                         -2.166e+04   2235.305     -9.688      0.000    -2.6e+04   -1.73e+04
district_Vnukovskoye                     -5.859e+04   2214.391    -26.457      0.000   -6.29e+04   -5.42e+04
district_Voronovskoye                     -1.84e+04   3010.913     -6.113      0.000   -2.43e+04   -1.25e+04
district_Voskresenskoye                  -6.775e+04   2288.926    -29.600      0.000   -7.22e+04   -6.33e+04
district_Vostochnoye Izmaylovo           -3.932e+04   3461.416    -11.358      0.000   -4.61e+04   -3.25e+04
district_Vostochny                       -5.422e+04   3954.836    -13.709      0.000    -6.2e+04   -4.65e+04
district_Voykovsky                       -1.342e+04   2279.273     -5.888      0.000   -1.79e+04   -8952.156
district_Yakimanka                        2.428e+05   2321.035    104.612      0.000    2.38e+05    2.47e+05
district_Yaroslavsky                     -3.468e+04   3154.019    -10.994      0.000   -4.09e+04   -2.85e+04
district_Yasenevo                         2.947e+04   2635.246     11.183      0.000    2.43e+04    3.46e+04
district_Yuzhnoye Butovo                 -2.448e+04   2747.282     -8.912      0.000   -2.99e+04   -1.91e+04
district_Yuzhnoye Medvedkovo             -3.839e+04   2818.295    -13.621      0.000   -4.39e+04   -3.29e+04
district_Yuzhnoye Tushino                -6135.5774   2407.980     -2.548      0.011   -1.09e+04   -1415.878
district_Zamoskvorechye                   1.829e+05   2256.944     81.031      0.000    1.78e+05    1.87e+05
district_Zapadnoye Degunino              -4.421e+04   2481.297    -17.817      0.000   -4.91e+04   -3.93e+04
district_Zelenograd                      -1.986e+04   4633.237     -4.286      0.000   -2.89e+04   -1.08e+04
district_Zyablikovo                      -5.199e+04   3282.892    -15.836      0.000   -5.84e+04   -4.56e+04
district_Zyuzino                          1927.0440   2385.280      0.808      0.419   -2748.163    6602.251
building_type_khrushchev                 -3.796e+04    646.985    -58.674      0.000   -3.92e+04   -3.67e+04
building_type_modern_panel               -9202.7901    781.193    -11.780      0.000   -1.07e+04   -7671.633
building_type_monolith                    9679.0616    780.482     12.401      0.000    8149.297    1.12e+04
building_type_panel                      -2.449e+04    550.546    -44.490      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.099e+04   1044.310     29.676      0.000    2.89e+04     3.3e+04
has_balcony_True                          5331.7718    391.223     13.628      0.000    4564.966    6098.578
renovation_designer                         6.4e+04    602.409    106.241      0.000    6.28e+04    6.52e+04
renovation_euro                            2.78e+04    408.719     68.019      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.881e+04    463.961    -40.545      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              4689.6797   2063.045      2.273      0.023     646.062    8733.297
metro_station_Bagrationovskaya           -1258.6346   1987.728     -0.633      0.527   -5154.630    2637.361
metro_station_Begovaya                    8493.2788   1945.618      4.365      0.000    4679.820    1.23e+04
metro_station_Belorusskaya                 871.9191   1989.799      0.438      0.661   -3028.135    4771.973
metro_station_Chekhovskaya                8757.2881   2038.622      4.296      0.000    4761.540    1.28e+04
metro_station_Chistye Prudy               1735.9088   1982.659      0.876      0.381   -2150.151    5621.969
metro_station_Chkalovskaya                3691.3680   2090.004      1.766      0.077    -405.091    7787.827
metro_station_Delovoy Tsentr              2493.2843   2068.449      1.205      0.228   -1560.926    6547.495
metro_station_Dinamo                      5662.6229   1745.263      3.245      0.001    2241.866    9083.380
metro_station_Dostoevskaya                1432.3077   1946.475      0.736      0.462   -2382.830    5247.445
metro_station_Dubrovka                    2243.6457   2123.999      1.056      0.291   -1919.445    6406.736
metro_station_Elektrozavodskaya           1208.5867   2015.724      0.600      0.549   -2742.282    5159.455
metro_station_Fili                       -1317.0743   1964.046     -0.671      0.502   -5166.652    2532.504
metro_station_Filyovsky Park              4676.3524   1822.288      2.566      0.010    1104.624    8248.081
metro_station_Frunzenskaya                1.145e+04   2026.824      5.650      0.000    7478.916    1.54e+04
metro_station_Kakhovskaya                 -962.3365   1686.439     -0.571      0.568   -4267.799    2343.126
metro_station_Kantemirovskaya            -2873.3851   1686.546     -1.704      0.088   -6179.057     432.286
metro_station_Kievskaya                   3180.9103   2004.376      1.587      0.113    -747.715    7109.536
metro_station_Kitay-Gorod                 1270.3457   2265.544      0.561      0.575   -3170.175    5710.867
metro_station_Komsomolskaya               2.139e+04   1986.437     10.770      0.000    1.75e+04    2.53e+04
metro_station_Krasnopresnenskaya          2.255e+04   1923.025     11.724      0.000    1.88e+04    2.63e+04
metro_station_Kropotkinskaya              7821.8795   2045.897      3.823      0.000    3811.871    1.18e+04
metro_station_Kurskaya                    2998.2537   2030.359      1.477      0.140    -981.298    6977.806
metro_station_Kutuzovskaya                2537.2162   1984.021      1.279      0.201   -1351.512    6425.945
metro_station_Kuznetsky Most              2471.9359   2088.269      1.184      0.237   -1621.122    6564.994
metro_station_Leninsky Prospekt           9394.0365   1764.943      5.323      0.000    5934.706    1.29e+04
metro_station_Lubyanka                    1700.8977   2058.616      0.826      0.409   -2334.039    5735.835

🏃 View run ols_temporal_pvalue_filtrado_070 at: http://127.0.0.1:5000/#/experiments/4/runs/f4917697d2c142c8a77cea946dd5e7e6
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Variables eliminadas por p-value >= 0.7: 7
Archivo filtrado guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_070.csv
OLS filtrado 0.70 registrado en MLflow para comparación

### Interpretación

Este segundo filtrado es más agresivo que el de `p-value >= 0,9`. La decisión debe basarse en la comparación temporal de MAE, RMSE, R² y MAPE, no únicamente en reducir la cantidad de columnas.

## 6. Eliminación explícita de `rooms`

El modelo con umbral `p-value >= 0,7` mostró que `rooms` quedó con un p-value de aproximadamente `0,823` después del re-ajuste. En esta sección eliminamos explícitamente esa variable, volvemos a ejecutar el mismo OLS temporal y registramos la nueva versión para compararla con el modelo anterior.

In [6]:
VARIABLE_ELIMINADA = "rooms"
RUTA_SALIDA_SIN_ROOMS = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_070_sin_rooms.csv")

if VARIABLE_ELIMINADA not in df_ols_filtrado_070.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA!r} no está disponible para eliminar")

df_ols_sin_rooms = df_ols_filtrado_070.drop(columns=[VARIABLE_ELIMINADA])
df_ols_sin_rooms.to_csv(RUTA_SALIDA_SIN_ROOMS, index=False)

df_train_sin_rooms = df_ols_sin_rooms[df_ols_sin_rooms["periodo"] < CORTE_TEMPORAL].copy()
df_test_sin_rooms = df_ols_sin_rooms[df_ols_sin_rooms["periodo"] >= CORTE_TEMPORAL].copy()
X_train_sin_rooms = df_train_sin_rooms.drop(columns=["price_per_sqm", "periodo"])
X_test_sin_rooms = df_test_sin_rooms.drop(columns=["price_per_sqm", "periodo"])
y_train_sin_rooms = df_train_sin_rooms["price_per_sqm"]
y_test_sin_rooms = df_test_sin_rooms["price_per_sqm"]

X_train_sin_rooms_sm = sm.add_constant(X_train_sin_rooms, has_constant="add")
X_test_sin_rooms_sm = sm.add_constant(X_test_sin_rooms, has_constant="add")
modelo_ols_sin_rooms = sm.OLS(y_train_sin_rooms, X_train_sin_rooms_sm)
resultados_ols_sin_rooms = modelo_ols_sin_rooms.fit()
predicciones_train_sin_rooms = resultados_ols_sin_rooms.predict(X_train_sin_rooms_sm)
predicciones_test_sin_rooms = resultados_ols_sin_rooms.predict(X_test_sin_rooms_sm)

metricas_ols_sin_rooms = {
    **calcular_metricas_regresion(y_train_sin_rooms, predicciones_train_sin_rooms, "train"),
    **calcular_metricas_regresion(y_test_sin_rooms, predicciones_test_sin_rooms, "test"),
    "r2_ols": float(resultados_ols_sin_rooms.rsquared),
    "r2_ajustado_ols": float(resultados_ols_sin_rooms.rsquared_adj),
    "aic_ols": float(resultados_ols_sin_rooms.aic),
    "bic_ols": float(resultados_ols_sin_rooms.bic),
    "f_statistic_ols": float(resultados_ols_sin_rooms.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_sin_rooms.f_pvalue)
}
omnibus_sin_rooms, prob_omnibus_sin_rooms = omni_normtest(resultados_ols_sin_rooms.resid)
jarque_bera_sin_rooms, prob_jb_sin_rooms, skew_sin_rooms, kurtosis_sin_rooms = jarque_bera(resultados_ols_sin_rooms.resid)
metricas_ols_sin_rooms.update({
    "omnibus_ols": float(omnibus_sin_rooms),
    "prob_omnibus_ols": float(prob_omnibus_sin_rooms),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_sin_rooms.resid)),
    "jarque_bera_ols": float(jarque_bera_sin_rooms),
    "prob_jb_ols": float(prob_jb_sin_rooms),
    "skew_ols": float(skew_sin_rooms),
    "kurtosis_ols": float(kurtosis_sin_rooms),
    "condition_number_ols": float(resultados_ols_sin_rooms.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_sin_rooms.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_sin_rooms.pvalues > 0.05).sum())
})

coeficientes_ols_sin_rooms = pd.DataFrame({
    "variable": resultados_ols_sin_rooms.params.index,
    "coeficiente": resultados_ols_sin_rooms.params.to_numpy(),
    "p_value": resultados_ols_sin_rooms.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_sin_rooms.pvalues.to_numpy() <= 0.05
})
residuos_test_sin_rooms = pd.DataFrame({
    "periodo": df_test_sin_rooms["periodo"].to_numpy(),
    "real": y_test_sin_rooms.to_numpy(),
    "prediccion": predicciones_test_sin_rooms.to_numpy(),
    "residuo": (y_test_sin_rooms.to_numpy() - predicciones_test_sin_rooms.to_numpy())
})
comparacion_ols_sin_rooms = pd.DataFrame([
    {"modelo": "OLS p-value 0.70", **metricas_ols_070},
    {"modelo": "OLS sin rooms", **metricas_ols_sin_rooms}
])
delta_metricas_sin_rooms = {
    f"delta_{metrica}": metricas_ols_sin_rooms[metrica] - metricas_ols_070[metrica]
    for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]
}

display(comparacion_ols_sin_rooms[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
print(resultados_ols_sin_rooms.summary())

RUN_OLS_P70_ID = "bc655f410d474a07b8ed1f153c4d084e"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_sin_rooms"):
    mlflow.set_tag("run_anterior_id", RUN_OLS_P70_ID)
    mlflow.log_params({
        "dataset": str(RUTA_SALIDA_SIN_ROOMS),
        "dataset_origen": str(RUTA_SALIDA_PVALUE_070),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "variable_eliminada": VARIABLE_ELIMINADA,
        "n_predictores": X_train_sin_rooms.shape[1],
        "filas_entrenamiento": len(df_train_sin_rooms),
        "filas_prueba": len(df_test_sin_rooms),
        "tipo_modelo": "statsmodels_OLS_sin_rooms"
    })
    mlflow.log_metrics({**metricas_ols_sin_rooms, **delta_metricas_sin_rooms})
    mlflow.log_table(comparacion_ols_sin_rooms, artifact_file="comparacion/comparacion_ols_sin_rooms.json")
    mlflow.log_table(coeficientes_ols_sin_rooms, artifact_file="modelo/coeficientes_ols_sin_rooms.json")
    mlflow.log_table(residuos_test_sin_rooms, artifact_file="diagnostico/residuos_test_sin_rooms.json")
    mlflow.log_text(resultados_ols_sin_rooms.summary().as_text(), "modelo/resumen_ols_sin_rooms.txt")

print(f"Archivo sin rooms guardado en: {RUTA_SALIDA_SIN_ROOMS}")
print("OLS sin rooms registrado en MLflow para comparación")

             modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS p-value 0.70  37085.870554  45133.296237  0.859824  23.174562
1     OLS sin rooms  37086.334875  45133.843386  0.859820  23.174916

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1626.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:54   Log-Likelihood:            -4.6952e+05
No. Observations:               39658   AIC:                         9.395e+05
Df Residuals:                   39417   BIC:                         9.416e+05
Df Model:                         240
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                     -3.11e+07   6.98e+05    -44.550      0.000   -3.25e+07   -2.97e+07
lat                                      -4.282e+04   9272.127     -4.618      0.000    -6.1e+04   -2.46e+04
lon                                      -3452.9740   7789.307     -0.443      0.658   -1.87e+04    1.18e+04
kitchen_area                               105.4975     59.417      1.776      0.076     -10.961     221.956
floor                                      134.2321     37.914      3.540      0.000      59.920     208.544
total_floors                                39.3796     32.019      1.230      0.219     -23.379     102.138
ceiling_height                            8508.2097    920.787      9.240      0.000    6703.445    1.03e+04
metro_distance_min                        -419.5114      9.921    -42.286      0.000    -438.956    -400.066
to_center_km                             -1492.9734    108.763    -13.727      0.000   -1706.151   -1279.796
mortgage_rate_at_listing                   -95.2937     52.588     -1.812      0.070    -198.368       7.780
date_posted_year                          1.672e+04    190.673     87.689      0.000    1.63e+04    1.71e+04
date_posted_month                         1239.4437     49.107     25.239      0.000    1143.192    1335.695
building_age                                10.8611     17.085      0.636      0.525     -22.626      44.349
district_Akademichesky                    3.922e+04   2191.153     17.901      0.000    3.49e+04    4.35e+04
district_Alekseevsky                     -1066.5153   2228.319     -0.479      0.632   -5434.075    3301.044
district_Altufyevsky                     -3.978e+04   2742.094    -14.506      0.000   -4.52e+04   -3.44e+04
district_Arbat                            2.667e+05   2268.324    117.589      0.000    2.62e+05    2.71e+05
district_Babushkinsky                    -3.147e+04   2813.894    -11.185      0.000    -3.7e+04    -2.6e+04
district_Basmanny                         1.399e+05   2278.194     61.411      0.000    1.35e+05    1.44e+05
district_Begovoy                          3.267e+04   2086.871     15.654      0.000    2.86e+04    3.68e+04
district_Beskudnikovsky                  -3.795e+04   2600.309    -14.593      0.000    -4.3e+04   -3.29e+04
district_Bibirevo                        -3.605e+04   2745.445    -13.132      0.000   -4.14e+04   -3.07e+04
district_Biryulyovo Vostochnoye          -5.738e+04   3017.760    -19.013      0.000   -6.33e+04   -5.15e+04
district_Biryulyovo Zapadnoye            -5.635e+04   2857.782    -19.717      0.000   -6.19e+04   -5.07e+04
district_Bogorodskoye                    -3.803e+04   2672.544    -14.231      0.000   -4.33e+04   -3.28e+04
district_Brateyevo                       -5.637e+04   3179.103    -17.733      0.000   -6.26e+04   -5.01e+04
district_Butyrsky                        -1.073e+04   2210.952     -4.852      0.000   -1.51e+04   -6393.919
district_Chertanovo Severnoye            -4.144e+04   2488.368    -16.654      0.000   -4.63e+04   -3.66e+04
district_Chertanovo Tsentralnoye         -5.337e+04   2541.770    -20.999      0.000   -5.84e+04   -4.84e+04
district_Chertanovo Yuzhnoye             -4.666e+04   2925.479    -15.948      0.000   -5.24e+04   -4.09e+04
district_Cheryomushki                     4.406e+04   2359.711     18.670      0.000    3.94e+04    4.87e+04
district_Desyonovskoye                   -5.744e+04   2535.048    -22.660      0.000   -6.24e+04   -5.25e+04
district_Dmitrovsky                      -4.181e+04   2660.397    -15.716      0.000    -4.7e+04   -3.66e+04
district_Donskoy                          1.569e+04   2338.618      6.711      0.000    1.11e+04    2.03e+04
district_Dorogomilovo                     1.345e+05   2201.803     61.104      0.000     1.3e+05    1.39e+05
district_Fili-Davydkovo                   3.952e+04   2140.875     18.459      0.000    3.53e+04    4.37e+04
district_Filimonkovskoye                 -7.304e+04   2242.603    -32.568      0.000   -7.74e+04   -6.86e+04
district_Filyovsky Park                   5.569e+04   2149.423     25.911      0.000    5.15e+04    5.99e+04
district_Gagarinsky                       8.071e+04   2264.818     35.636      0.000    7.63e+04    8.51e+04
district_Golovinsky                      -3.254e+04   2351.835    -13.835      0.000   -3.71e+04   -2.79e+04
district_Golyanovo                       -5.066e+04   3356.541    -15.092      0.000   -5.72e+04   -4.41e+04
district_Ivanovskoye                     -4.767e+04   3373.766    -14.129      0.000   -5.43e+04   -4.11e+04
district_Izmaylovo                       -2.152e+04   2972.432     -7.239      0.000   -2.73e+04   -1.57e+04
district_Khamovniki                        2.91e+05   2229.570    130.530      0.000    2.87e+05    2.95e+05
district_Khoroshyovo-Mnyovniki            2.258e+04   2219.882     10.174      0.000    1.82e+04    2.69e+04
district_Khoroshyovsky                    4.079e+04   2166.987     18.823      0.000    3.65e+04     4.5e+04
district_Khovrino                         -4.02e+04   2587.066    -15.538      0.000   -4.53e+04   -3.51e+04
district_Kievsky                          1.788e+04   3063.275      5.838      0.000    1.19e+04    2.39e+04
district_Klyonovskoye                    -2.434e+04   4543.184     -5.358      0.000   -3.32e+04   -1.54e+04
district_Kokoshkino                      -6.357e+04   2373.952    -26.777      0.000   -6.82e+04   -5.89e+04
district_Konkovo                          2410.6786   2196.073      1.098      0.272   -1893.678    6715.035
district_Koptevo                         -2.786e+04   2394.019    -11.635      0.000   -3.25e+04   -2.32e+04
district_Kosino-Ukhtomsky                -5.489e+04   3638.219    -15.086      0.000    -6.2e+04   -4.78e+04
district_Kotlovka                         1.184e+04   2336.845      5.068      0.000    7263.840    1.64e+04
district_Krasnopakhorskoye               -5.921e+04   2506.660    -23.621      0.000   -6.41e+04   -5.43e+04
district_Krasnoselsky                     1.265e+05   2356.248     53.688      0.000    1.22e+05    1.31e+05
district_Krylatskoye                      5.425e+04   2268.988     23.907      0.000    4.98e+04    5.87e+04
district_Kuntsevo                         1.667e+04   2221.216      7.506      0.000    1.23e+04     2.1e+04
district_Kurkino                          2.171e+04   2938.974      7.386      0.000    1.59e+04    2.75e+04
district_Levoberezhny                    -2.255e+04   2510.140     -8.984      0.000   -2.75e+04   -1.76e+04
district_Lianozovo                       -3.689e+04   2947.541    -12.516      0.000   -4.27e+04   -3.11e+04
district_Lomonosovsky                     7.393e+04   2229.270     33.161      0.000    6.96e+04    7.83e+04
district_Losinoostrovsky                 -3.134e+04   3052.392    -10.267      0.000   -3.73e+04   -2.54e+04
district_Marfino                         -3.554e+04   2349.018    -15.128      0.000   -4.01e+04   -3.09e+04
district_Marushkinskoye                  -6.391e+04   2166.510    -29.500      0.000   -6.82e+04   -5.97e+04
district_Meshchansky                      1.561e+05   2204.613     70.821      0.000    1.52e+05     1.6e+05
district_Metrogorodok                    -4.624e+04   3015.752    -15.332      0.000   -5.21e+04   -4.03e+04
district_Mikhaylovo-Yartsevskoye         -4.649e+04   2422.421    -19.192      0.000   -5.12e+04   -4.17e+04
district_Mitino                          -1.271e+04   2936.973     -4.326      0.000   -1.85e+04   -6948.893
district_Molzhaninovsky                   -3.02e+04   3638.496     -8.300      0.000   -3.73e+04   -2.31e+04
district_Moskovsky                       -5.742e+04   2227.012    -25.784      0.000   -6.18e+04   -5.31e+04
district_Moskvorechye-Saburovo           -4.336e+04   2645.500    -16.388      0.000   -4.85e+04   -3.82e+04
district_Mosrentgen                      -7.029e+04   2456.386    -28.616      0.000   -7.51e+04   -6.55e+04
district_Mozhaysky                        1700.0997   2239.750      0.759      0.448   -2689.865    6090.064
district_Nagatino-Sadovniki              -2.673e+04   2549.140    -10.488      0.000   -3.17e+04   -2.17e+04
district_Nagatinsky Zaton                -2.134e+04   2602.735     -8.201      0.000   -2.64e+04   -1.62e+04
district_Nagorny                         -1.813e+04   2505.861     -7.235      0.000    -2.3e+04   -1.32e+04
district_Novo-Peredelkino                -2.618e+04   2203.316    -11.881      0.000   -3.05e+04   -2.19e+04
district_Novogireyevo                    -3.969e+04   3221.434    -12.320      0.000    -4.6e+04   -3.34e+04
district_Novokosino                      -4.041e+04   3771.752    -10.714      0.000   -4.78e+04    -3.3e+04
district_Obruchevsky                      2.173e+04   2313.751      9.391      0.000    1.72e+04    2.63e+04
district_Orekhovo-Borisovo Severnoye     -5.463e+04   3019.857    -18.091      0.000   -6.06e+04   -4.87e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.271e+04   3069.639    -17.173      0.000   -5.87e+04   -4.67e+04
district_Ostankinsky                     -1571.2916   2345.867     -0.670      0.503   -6169.248    3026.665
district_Otradnoye                       -3.214e+04   2569.398    -12.507      0.000   -3.72e+04   -2.71e+04
district_Perovo                          -2.634e+04   3247.596     -8.111      0.000   -3.27e+04      -2e+04
district_Pervomayskoye                   -3.819e+04   2435.608    -15.678      0.000    -4.3e+04   -3.34e+04
district_Preobrazhenskoye                -1.078e+04   2742.432     -3.930      0.000   -1.62e+04   -5401.804
district_Presnensky                       2.448e+05   2264.848    108.071      0.000     2.4e+05    2.49e+05
district_Prospekt Vernadskogo             7.401e+04   2202.660     33.598      0.000    6.97e+04    7.83e+04
district_Ramenki                          7.414e+04   2163.954     34.262      0.000    6.99e+04    7.84e+04
district_Rogovskoye                       4682.4884   2972.683      1.575      0.115   -1144.042    1.05e+04
district_Rostokino                       -3.706e+04   2443.672    -15.166      0.000   -4.19e+04   -3.23e+04
district_Ryazanovskoye                   -6.091e+04   2987.097    -20.389      0.000   -6.68e+04   -5.51e+04
district_Savyolovsky                      1.606e+04   2181.789      7.363      0.000    1.18e+04    2.03e+04
district_Severnoye Butovo                -2.451e+04   2678.770     -9.149      0.000   -2.98e+04   -1.93e+04
district_Severnoye Izmaylovo             -3.231e+04   3432.725     -9.413      0.000    -3.9e+04   -2.56e+04
district_Severnoye Medvedkovo            -2.885e+04   2878.800    -10.021      0.000   -3.45e+04   -2.32e+04
district_Severnoye Tushino               -1.511e+04   2467.116     -6.123      0.000   -1.99e+04   -1.03e+04
district_Severny                         -3.727e+04   3308.273    -11.266      0.000   -4.38e+04   -3.08e+04
district_Shchapovskoye                   -5.947e+04   3771.887    -15.768      0.000   -6.69e+04   -5.21e+04
district_Shcherbinka                      -5.87e+04   3099.672    -18.938      0.000   -6.48e+04   -5.26e+04
district_Shchukino                        4.251e+04   2370.223     17.936      0.000    3.79e+04    4.72e+04
district_Sokol                            3.142e+04   2226.209     14.113      0.000    2.71e+04    3.58e+04
district_Sokolinaya Gora                   -4.3e+04   2657.220    -16.182      0.000   -4.82e+04   -3.78e+04
district_Sokolniki                        1714.1340   2515.216      0.682      0.496   -3215.751    6644.019
district_Solntsevo                       -2.044e+04   2083.168     -9.813      0.000   -2.45e+04   -1.64e+04
district_Sosenskoye                      -5.638e+04   2298.207    -24.533      0.000   -6.09e+04   -5.19e+04
district_Strogino                         6.266e+04   2814.965     22.258      0.000    5.71e+04    6.82e+04
district_Sviblovo                        -3.125e+04   2644.336    -11.819      0.000   -3.64e+04   -2.61e+04
district_Tagansky                         1.268e+05   2370.408     53.494      0.000    1.22e+05    1.31e+05
district_Timiryazevsky                   -3474.6810   2141.018     -1.623      0.105   -7671.129     721.767
district_Troitsk                         -5.875e+04   2375.226    -24.736      0.000   -6.34e+04   -5.41e+04
district_Troparyovo-Nikulino              5.266e+04   2271.658     23.180      0.000    4.82e+04    5.71e+04
district_Tsaritsyno                      -5.278e+04   2844.065    -18.558      0.000   -5.84e+04   -4.72e+04
district_Tverskoy                         2.689e+05   2198.906    122.307      0.000    2.65e+05    2.73e+05
district_Tyoply Stan                     -5721.6293   2232.787     -2.563      0.010   -1.01e+04   -1345.314
district_Veshnyaki                       -6.224e+04   3312.922    -18.788      0.000   -6.87e+04   -5.57e+04
district_Vnukovo                         -2.165e+04   2235.214     -9.687      0.000    -2.6e+04   -1.73e+04
district_Vnukovskoye                     -5.858e+04   2214.297    -26.457      0.000   -6.29e+04   -5.42e+04
district_Voronovskoye                     -1.84e+04   3010.876     -6.113      0.000   -2.43e+04   -1.25e+04
district_Voskresenskoye                  -6.775e+04   2288.803    -29.600      0.000   -7.22e+04   -6.33e+04
district_Vostochnoye Izmaylovo           -3.932e+04   3461.359    -11.359      0.000   -4.61e+04   -3.25e+04
district_Vostochny                       -5.422e+04   3954.731    -13.711      0.000    -6.2e+04   -4.65e+04
district_Voykovsky                       -1.342e+04   2279.245     -5.888      0.000   -1.79e+04   -8951.988
district_Yakimanka                        2.428e+05   2320.963    104.617      0.000    2.38e+05    2.47e+05
district_Yaroslavsky                     -3.468e+04   3153.952    -10.995      0.000   -4.09e+04   -2.85e+04
district_Yasenevo                         2.947e+04   2635.146     11.185      0.000    2.43e+04    3.46e+04
district_Yuzhnoye Butovo                 -2.448e+04   2747.242     -8.912      0.000   -2.99e+04   -1.91e+04
district_Yuzhnoye Medvedkovo             -3.839e+04   2818.260    -13.621      0.000   -4.39e+04   -3.29e+04
district_Yuzhnoye Tushino                -6136.2806   2407.949     -2.548      0.011   -1.09e+04   -1416.642
district_Zamoskvorechye                   1.829e+05   2256.916     81.032      0.000    1.78e+05    1.87e+05
district_Zapadnoye Degunino              -4.421e+04   2481.246    -17.817      0.000   -4.91e+04   -3.93e+04
district_Zelenograd                      -1.986e+04   4633.167     -4.287      0.000   -2.89e+04   -1.08e+04
district_Zyablikovo                      -5.199e+04   3282.841    -15.837      0.000   -5.84e+04   -4.56e+04
district_Zyuzino                          1926.6591   2385.251      0.808      0.419   -2748.490    6601.808
building_type_khrushchev                 -3.796e+04    646.952    -58.679      0.000   -3.92e+04   -3.67e+04
building_type_modern_panel               -9202.9572    781.183    -11.781      0.000   -1.07e+04   -7671.820
building_type_monolith                    9678.6892    780.471     12.401      0.000    8148.947    1.12e+04
building_type_panel                       -2.45e+04    550.499    -44.497      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.099e+04   1044.232     29.676      0.000    2.89e+04     3.3e+04
has_balcony_True                          5331.8036    391.218     13.629      0.000    4565.007    6098.600
renovation_designer                         6.4e+04    602.387    106.244      0.000    6.28e+04    6.52e+04
renovation_euro                            2.78e+04    408.706     68.023      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.881e+04    463.954    -40.546      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              4689.7027   2063.020      2.273      0.023     646.134    8733.272
metro_station_Bagrationovskaya           -1257.7567   1987.700     -0.633      0.527   -5153.698    2638.184
metro_station_Begovaya                    8490.9302   1945.567      4.364      0.000    4677.573    1.23e+04
metro_station_Belorusskaya                 869.5940   1989.748      0.437      0.662   -3030.360    4769.548
metro_station_Chekhovskaya                8757.0494   2038.597      4.296      0.000    4761.350    1.28e+04
metro_station_Chistye Prudy               1732.6159   1982.581      0.874      0.382   -2153.291    5618.522
metro_station_Chkalovskaya                3691.2217   2089.979      1.766      0.077    -405.188    7787.631
metro_station_Delovoy Tsentr              2487.7965   2068.279      1.203      0.229   -1566.081    6541.674
metro_station_Dinamo                      5662.7330   1745.242      3.245      0.001    2242.017    9083.449
metro_station_Dostoevskaya                1433.5002   1946.444      0.736      0.461   -2381.577    5248.577
metro_station_Dubrovka                    2240.4134   2123.925      1.055      0.292   -1922.531    6403.358
metro_station_Elektrozavodskaya           1208.2895   2015.700      0.599      0.549   -2742.531    5159.110
metro_station_Fili                       -1314.4401   1963.987     -0.669      0.503   -5163.903    2535.022
metro_station_Filyovsky Park              4679.4950   1822.212      2.568      0.010    1107.915    8251.075
metro_station_Frunzenskaya                1.145e+04   2026.769      5.649      0.000    7476.512    1.54e+04
metro_station_Kakhovskaya                 -968.1860   1686.217     -0.574      0.566   -4273.213    2336.841
metro_station_Kantemirovskaya            -2871.8049   1686.511     -1.703      0.089   -6177.408     433.798
metro_station_Kievskaya                   3182.1200   2004.345      1.588      0.112    -746.444    7110.684
metro_station_Kitay-Gorod                 1269.4932   2265.514      0.560      0.575   -3170.968    5709.955
metro_station_Komsomolskaya               2.139e+04   1986.401     10.769      0.000    1.75e+04    2.53e+04
metro_station_Krasnopresnenskaya          2.254e+04   1922.983     11.723      0.000    1.88e+04    2.63e+04
metro_station_Kropotkinskaya              7819.6870   2045.849      3.822      0.000    3809.773    1.18e+04
metro_station_Kurskaya                    2996.9872   2030.326      1.476      0.140    -982.501    6976.476
metro_station_Kutuzovskaya                2537.8723   1983.995      1.279      0.201   -1350.805    6426.550
metro_station_Kuznetsky Most              2472.0011   2088.244      1.184      0.237   -1621.008    6565.010
metro_station_Leninsky Prospekt           9394.5085   1764.920      5.323      0.000    5935.222    1.29e+04
metro_station_Lubyanka                    1698.9335   2058.573      0.825      0.409   -2335.918    5733.785
metro_station_Mayakovskaya                2257.1724   2182.345      1.034      0.301   -2020.277    6534.622

🏃 View run ols_temporal_sin_rooms at: http://127.0.0.1:5000/#/experiments/4/runs/364ebea47ba04427a404907bad78752e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Archivo sin rooms guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_070_sin_rooms.csv
OLS sin rooms registrado en MLflow para comparación

### Interpretación

La eliminación de `rooms` se evalúa comparando las métricas temporales de prueba contra el modelo `p-value >= 0,7`. La variable deja de participar en el modelo, pero el resto de los coeficientes y sus p-values pueden cambiar al volver a ajustar el OLS.

## 7. Filtrado de predictores con p-value >= 0,2 sobre el modelo sin `rooms`

Partimos del modelo que ya elimina `rooms` y quitamos los predictores restantes con `p-value >= 0,2`. Se conserva el mismo corte temporal y el archivo anterior permanece intacto para poder comparar las variantes.

In [7]:
UMBRAL_PVALUE_020 = 0.20
RUTA_SALIDA_PVALUE_020 = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_020_sin_rooms.csv")

variables_eliminar_pvalue_020 = sorted(
    coeficientes_ols_sin_rooms.loc[
        (coeficientes_ols_sin_rooms["p_value"] >= UMBRAL_PVALUE_020)
        & (~coeficientes_ols_sin_rooms["variable"].isin(["const", "price_per_sqm", "periodo"])),
        "variable"
    ].tolist()
)

df_ols_filtrado_020 = df_ols_sin_rooms.drop(columns=variables_eliminar_pvalue_020)
df_ols_filtrado_020.to_csv(RUTA_SALIDA_PVALUE_020, index=False)

df_train_020 = df_ols_filtrado_020[df_ols_filtrado_020["periodo"] < CORTE_TEMPORAL].copy()
df_test_020 = df_ols_filtrado_020[df_ols_filtrado_020["periodo"] >= CORTE_TEMPORAL].copy()
X_train_020 = df_train_020.drop(columns=["price_per_sqm", "periodo"])
X_test_020 = df_test_020.drop(columns=["price_per_sqm", "periodo"])
y_train_020 = df_train_020["price_per_sqm"]
y_test_020 = df_test_020["price_per_sqm"]

X_train_020_sm = sm.add_constant(X_train_020, has_constant="add")
X_test_020_sm = sm.add_constant(X_test_020, has_constant="add")
modelo_ols_020 = sm.OLS(y_train_020, X_train_020_sm)
resultados_ols_020 = modelo_ols_020.fit()
predicciones_train_020 = resultados_ols_020.predict(X_train_020_sm)
predicciones_test_020 = resultados_ols_020.predict(X_test_020_sm)

metricas_ols_020 = {
    **calcular_metricas_regresion(y_train_020, predicciones_train_020, "train"),
    **calcular_metricas_regresion(y_test_020, predicciones_test_020, "test"),
    "r2_ols": float(resultados_ols_020.rsquared),
    "r2_ajustado_ols": float(resultados_ols_020.rsquared_adj),
    "aic_ols": float(resultados_ols_020.aic),
    "bic_ols": float(resultados_ols_020.bic),
    "f_statistic_ols": float(resultados_ols_020.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_020.f_pvalue)
}
omnibus_020, prob_omnibus_020 = omni_normtest(resultados_ols_020.resid)
jarque_bera_020, prob_jb_020, skew_020, kurtosis_020 = jarque_bera(resultados_ols_020.resid)
metricas_ols_020.update({
    "omnibus_ols": float(omnibus_020),
    "prob_omnibus_ols": float(prob_omnibus_020),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_020.resid)),
    "jarque_bera_ols": float(jarque_bera_020),
    "prob_jb_ols": float(prob_jb_020),
    "skew_ols": float(skew_020),
    "kurtosis_ols": float(kurtosis_020),
    "condition_number_ols": float(resultados_ols_020.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_020.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_020.pvalues > 0.05).sum())
})

coeficientes_ols_020 = pd.DataFrame({
    "variable": resultados_ols_020.params.index,
    "coeficiente": resultados_ols_020.params.to_numpy(),
    "p_value": resultados_ols_020.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_020.pvalues.to_numpy() <= 0.05
})
residuos_test_020 = pd.DataFrame({
    "periodo": df_test_020["periodo"].to_numpy(),
    "real": y_test_020.to_numpy(),
    "prediccion": predicciones_test_020.to_numpy(),
    "residuo": (y_test_020.to_numpy() - predicciones_test_020.to_numpy())
})
comparacion_ols_020 = pd.DataFrame([
    {"modelo": "OLS sin rooms", **metricas_ols_sin_rooms},
    {"modelo": "OLS p-value 0.20 sin rooms", **metricas_ols_020}
])
delta_metricas_020 = {
    f"delta_{metrica}": metricas_ols_020[metrica] - metricas_ols_sin_rooms[metrica]
    for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]
}
tabla_variables_eliminadas_020 = coeficientes_ols_sin_rooms[
    coeficientes_ols_sin_rooms["variable"].isin(variables_eliminar_pvalue_020)
].sort_values("p_value", ascending=False)

display(tabla_variables_eliminadas_020)
display(comparacion_ols_020[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
print(resultados_ols_020.summary())

RUN_OLS_SIN_ROOMS_ID = "b31b9d738b2a4d23afe15d9690a3b9ce"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_pvalue_filtrado_020_sin_rooms"):
    mlflow.set_tag("run_anterior_id", RUN_OLS_SIN_ROOMS_ID)
    mlflow.log_params({
        "dataset": str(RUTA_SALIDA_PVALUE_020),
        "dataset_origen": str(RUTA_SALIDA_SIN_ROOMS),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "umbral_pvalue_eliminacion": UMBRAL_PVALUE_020,
        "n_variables_eliminadas_pvalue": len(variables_eliminar_pvalue_020),
        "n_predictores": X_train_020.shape[1],
        "filas_entrenamiento": len(df_train_020),
        "filas_prueba": len(df_test_020),
        "tipo_modelo": "statsmodels_OLS_pvalue_filtrado_020_sin_rooms"
    })
    mlflow.log_metrics({**metricas_ols_020, **delta_metricas_020})
    mlflow.log_table(tabla_variables_eliminadas_020, artifact_file="seleccion/variables_eliminadas_pvalue_020.json")
    mlflow.log_table(comparacion_ols_020, artifact_file="comparacion/comparacion_ols_020.json")
    mlflow.log_table(coeficientes_ols_020, artifact_file="modelo/coeficientes_ols_020.json")
    mlflow.log_table(residuos_test_020, artifact_file="diagnostico/residuos_test_020.json")
    mlflow.log_text(resultados_ols_020.summary().as_text(), "modelo/resumen_ols_020.txt")

print(f"Variables eliminadas por p-value >= {UMBRAL_PVALUE_020}: {len(variables_eliminar_pvalue_020)}")
print(f"Archivo filtrado guardado en: {RUTA_SALIDA_PVALUE_020}")
print("OLS filtrado 0.20 registrado en MLflow para comparación")

,variable,coeficiente,p_value,significativa_0_05
179,metro_station_Novoslobodskaya,703.655845,0.714917,False
148,metro_station_Belorusskaya,869.593966,0.662087,False
2,lon,-3452.973992,0.657554,False
14,district_Alekseevsky,-1066.515338,0.632213,False
205,metro_station_Sevastopolskaya,849.093646,0.615449,False
163,metro_station_Kitay-Gorod,1269.493225,0.575240,False
212,metro_station_Smolenskaya (F),1110.348128,0.569916,False
160,metro_station_Kakhovskaya,-968.186026,0.565852,False
156,metro_station_Elektrozavodskaya,1208.289504,0.548883,False
146,metro_station_Bagrationovskaya,-1257.756730,0.526888,False
12,building_age,10.861140,0.524975,False
157,metro_station_Fili,-1314.440123,0.503326,False
83,district_Ostankinsky,-1571.291559,0.502981,False
185,metro_station_Pechatniki,1435.890640,0.500201,False
105,district_Sokolniki,1714.133973,0.495556,False
154,metro_station_Dostoevskaya,1433.500188,0.461448,False
190,metro_station_Ploshchad Revolyutsii,-1525.567846,0.450106,False
73,district_Mozhaysky,1700.099729,0.447823,False
135,district_Zyuzino,1926.659055,0.419246,False
171,metro_station_Lubyanka,1698.933515,0.409208,False
150,metro_station_Chistye Prudy,1732.615900,0.382167,False
174,metro_station_Molodyozhnaya,1837.040527,0.326835,False
221,metro_station_Teatralnaya,1973.838306,0.325691,False
172,metro_station_Mayakovskaya,2257.172356,0.301008,False
211,metro_station_Smolenskaya (AP),2173.292356,0.300189,False
155,metro_station_Dubrovka,2240.413420,0.291502,False
215,metro_station_Sportivnaya,-2090.265549,0.290681,False
50,district_Konkovo,2410.678558,0.272332,False
240,seller_type_owner,-396.568240,0.266155,False
218,metro_station_Sukharevskaya,2455.469067,0.241435,False
169,metro_station_Kuznetsky Most,2472.001126,0.236511,False
152,metro_station_Delovoy Tsentr,2487.796545,0.229048,False
237,metro_station_Yugo-Zapadnaya,2004.657894,0.226543,False
5,total_floors,39.379606,0.218753,False
168,metro_station_Kutuzovskaya,2537.872293,0.200844,False

                       modelo      mae_test     rmse_test   r2_test  mape_test
0               OLS sin rooms  37086.334875  45133.843386  0.859820  23.174916
1  OLS p-value 0.20 sin rooms  37093.445411  45146.594650  0.859741  23.177022

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1904.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:56   Log-Likelihood:            -4.6953e+05
No. Observations:               39658   AIC:                         9.395e+05
Df Residuals:                   39452   BIC:                         9.412e+05
Df Model:                         205
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -3.088e+07   5.83e+05    -52.956      0.000    -3.2e+07   -2.97e+07
lat                                      -4.955e+04   7798.256     -6.354      0.000   -6.48e+04   -3.43e+04
kitchen_area                               103.6015     59.377      1.745      0.081     -12.778     219.981
floor                                      161.8604     30.638      5.283      0.000     101.809     221.912
ceiling_height                            8506.1328    920.199      9.244      0.000    6702.520    1.03e+04
metro_distance_min                        -419.6220      9.588    -43.764      0.000    -438.415    -400.829
to_center_km                             -1503.3781     72.777    -20.657      0.000   -1646.024   -1360.733
mortgage_rate_at_listing                   -95.5046     52.555     -1.817      0.069    -198.514       7.505
date_posted_year                          1.673e+04    189.807     88.143      0.000    1.64e+04    1.71e+04
date_posted_month                         1238.5311     49.076     25.237      0.000    1142.341    1334.721
district_Akademichesky                    3.814e+04   2021.148     18.872      0.000    3.42e+04    4.21e+04
district_Altufyevsky                     -3.925e+04   2399.462    -16.359      0.000    -4.4e+04   -3.45e+04
district_Arbat                            2.662e+05   2125.372    125.248      0.000    2.62e+05     2.7e+05
district_Babushkinsky                    -3.132e+04   2327.829    -13.454      0.000   -3.59e+04   -2.68e+04
district_Basmanny                         1.393e+05   2029.855     68.602      0.000    1.35e+05    1.43e+05
district_Begovoy                           3.26e+04   1975.125     16.507      0.000    2.87e+04    3.65e+04
district_Beskudnikovsky                  -3.742e+04   2401.623    -15.583      0.000   -4.21e+04   -3.27e+04
district_Bibirevo                        -3.564e+04   2385.091    -14.942      0.000   -4.03e+04    -3.1e+04
district_Biryulyovo Vostochnoye          -5.928e+04   2072.336    -28.606      0.000   -6.33e+04   -5.52e+04
district_Biryulyovo Zapadnoye            -5.819e+04   2128.245    -27.344      0.000   -6.24e+04    -5.4e+04
district_Bogorodskoye                    -3.847e+04   2121.714    -18.134      0.000   -4.26e+04   -3.43e+04
district_Brateyevo                       -5.817e+04   2068.172    -28.127      0.000   -6.22e+04   -5.41e+04
district_Butyrsky                        -1.071e+04   2074.521     -5.165      0.000   -1.48e+04   -6647.791
district_Chertanovo Severnoye              -4.3e+04   2112.645    -20.356      0.000   -4.71e+04   -3.89e+04
district_Chertanovo Tsentralnoye         -5.501e+04   2183.417    -25.194      0.000   -5.93e+04   -5.07e+04
district_Chertanovo Yuzhnoye             -4.826e+04   2503.176    -19.281      0.000   -5.32e+04   -4.34e+04
district_Cheryomushki                      4.29e+04   2187.539     19.612      0.000    3.86e+04    4.72e+04
district_Desyonovskoye                   -5.897e+04   2133.747    -27.637      0.000   -6.32e+04   -5.48e+04
district_Dmitrovsky                       -4.12e+04   2441.002    -16.880      0.000    -4.6e+04   -3.64e+04
district_Donskoy                          1.473e+04   2182.010      6.749      0.000    1.05e+04     1.9e+04
district_Dorogomilovo                     1.341e+05   2064.175     64.960      0.000     1.3e+05    1.38e+05
district_Fili-Davydkovo                   3.912e+04   1996.730     19.592      0.000    3.52e+04     4.3e+04
district_Filimonkovskoye                 -7.399e+04   2124.274    -34.830      0.000   -7.82e+04   -6.98e+04
district_Filyovsky Park                   5.537e+04   2006.702     27.594      0.000    5.14e+04    5.93e+04
district_Gagarinsky                        7.98e+04   2121.392     37.615      0.000    7.56e+04     8.4e+04
district_Golovinsky                      -3.207e+04   2222.684    -14.427      0.000   -3.64e+04   -2.77e+04
district_Golyanovo                       -5.136e+04   2254.586    -22.779      0.000   -5.58e+04   -4.69e+04
district_Ivanovskoye                     -4.875e+04   2079.666    -23.440      0.000   -5.28e+04   -4.47e+04
district_Izmaylovo                       -2.229e+04   2138.207    -10.423      0.000   -2.65e+04   -1.81e+04
district_Khamovniki                       2.903e+05   2088.139    139.019      0.000    2.86e+05    2.94e+05
district_Khoroshyovo-Mnyovniki            2.264e+04   2090.099     10.831      0.000    1.85e+04    2.67e+04
district_Khoroshyovsky                    4.066e+04   2051.398     19.822      0.000    3.66e+04    4.47e+04
district_Khovrino                         -3.95e+04   2402.747    -16.441      0.000   -4.42e+04   -3.48e+04
district_Kievsky                          1.842e+04   2791.480      6.597      0.000    1.29e+04    2.39e+04
district_Klyonovskoye                    -2.722e+04   2687.886    -10.128      0.000   -3.25e+04    -2.2e+04
district_Kokoshkino                      -6.317e+04   2131.128    -29.641      0.000   -6.73e+04    -5.9e+04
district_Koptevo                         -2.749e+04   2261.523    -12.158      0.000   -3.19e+04   -2.31e+04
district_Kosino-Ukhtomsky                -5.641e+04   1990.635    -28.338      0.000   -6.03e+04   -5.25e+04
district_Kotlovka                         1.053e+04   2103.889      5.003      0.000    6402.207    1.46e+04
district_Krasnopakhorskoye                -6.05e+04   2278.495    -26.554      0.000    -6.5e+04    -5.6e+04
district_Krasnoselsky                      1.26e+05   2157.629     58.380      0.000    1.22e+05     1.3e+05
district_Krylatskoye                      5.466e+04   2070.753     26.398      0.000    5.06e+04    5.87e+04
district_Kuntsevo                         1.665e+04   2060.928      8.079      0.000    1.26e+04    2.07e+04
district_Kurkino                          2.297e+04   2701.335      8.502      0.000    1.77e+04    2.83e+04
district_Levoberezhny                    -2.191e+04   2358.391     -9.289      0.000   -2.65e+04   -1.73e+04
district_Lianozovo                       -3.621e+04   2580.351    -14.032      0.000   -4.13e+04   -3.12e+04
district_Lomonosovsky                     7.296e+04   2091.445     34.883      0.000    6.89e+04    7.71e+04
district_Losinoostrovsky                 -3.118e+04   2341.679    -13.315      0.000   -3.58e+04   -2.66e+04
district_Marfino                          -3.54e+04   2159.155    -16.395      0.000   -3.96e+04   -3.12e+04
district_Marushkinskoye                  -6.415e+04   2061.615    -31.117      0.000   -6.82e+04   -6.01e+04
district_Meshchansky                      1.557e+05   2047.856     76.054      0.000    1.52e+05     1.6e+05
district_Metrogorodok                    -4.669e+04   2287.303    -20.412      0.000   -5.12e+04   -4.22e+04
district_Mikhaylovo-Yartsevskoye         -4.765e+04   2263.576    -21.052      0.000   -5.21e+04   -4.32e+04
district_Mitino                          -1.155e+04   2726.794     -4.234      0.000   -1.69e+04   -6200.531
district_Molzhaninovsky                  -2.857e+04   3261.400     -8.759      0.000    -3.5e+04   -2.22e+04
district_Moskovsky                       -5.805e+04   2141.971    -27.103      0.000   -6.23e+04   -5.39e+04
district_Moskvorechye-Saburovo            -4.49e+04   2080.845    -21.579      0.000    -4.9e+04   -4.08e+04
district_Mosrentgen                      -7.147e+04   2280.805    -31.335      0.000   -7.59e+04    -6.7e+04
district_Nagatino-Sadovniki              -2.811e+04   2194.625    -12.809      0.000   -3.24e+04   -2.38e+04
district_Nagatinsky Zaton                -2.273e+04   2070.696    -10.979      0.000   -2.68e+04   -1.87e+04
district_Nagorny                         -1.942e+04   2245.441     -8.647      0.000   -2.38e+04    -1.5e+04
district_Novo-Peredelkino                -2.632e+04   2065.297    -12.744      0.000   -3.04e+04   -2.23e+04
district_Novogireyevo                    -4.084e+04   2177.616    -18.756      0.000   -4.51e+04   -3.66e+04
district_Novokosino                      -4.183e+04   2047.271    -20.430      0.000   -4.58e+04   -3.78e+04
district_Obruchevsky                       2.06e+04   2139.553      9.630      0.000    1.64e+04    2.48e+04
district_Orekhovo-Borisovo Severnoye     -5.643e+04   2111.471    -26.724      0.000   -6.06e+04   -5.23e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.458e+04   2015.759    -27.075      0.000   -5.85e+04   -5.06e+04
district_Otradnoye                       -3.189e+04   2264.070    -14.087      0.000   -3.63e+04   -2.75e+04
district_Perovo                          -2.744e+04   2397.418    -11.447      0.000   -3.21e+04   -2.27e+04
district_Pervomayskoye                   -3.861e+04   2384.784    -16.191      0.000   -4.33e+04   -3.39e+04
district_Preobrazhenskoye                -1.135e+04   2278.225     -4.980      0.000   -1.58e+04   -6880.610
district_Presnensky                       2.443e+05   2138.272    114.259      0.000     2.4e+05    2.49e+05
district_Prospekt Vernadskogo             7.331e+04   2066.664     35.473      0.000    6.93e+04    7.74e+04
district_Ramenki                          7.347e+04   2034.066     36.119      0.000    6.95e+04    7.75e+04
district_Rogovskoye                       3398.3565   2805.216      1.211      0.226   -2099.934    8896.647
district_Rostokino                       -3.709e+04   2096.808    -17.690      0.000   -4.12e+04    -3.3e+04
district_Ryazanovskoye                   -6.282e+04   2254.916    -27.861      0.000   -6.72e+04   -5.84e+04
district_Savyolovsky                      1.597e+04   2065.714      7.730      0.000    1.19e+04       2e+04
district_Severnoye Butovo                -2.613e+04   2194.556    -11.906      0.000   -3.04e+04   -2.18e+04
district_Severnoye Izmaylovo               -3.3e+04   2328.866    -14.169      0.000   -3.76e+04   -2.84e+04
district_Severnoye Medvedkovo            -2.848e+04   2410.453    -11.815      0.000   -3.32e+04   -2.38e+04
district_Severnoye Tushino               -1.431e+04   2298.406     -6.225      0.000   -1.88e+04   -9802.427
district_Severny                         -3.631e+04   2818.084    -12.884      0.000   -4.18e+04   -3.08e+04
district_Shchapovskoye                   -6.195e+04   2421.197    -25.586      0.000   -6.67e+04   -5.72e+04
district_Shcherbinka                     -6.068e+04   2289.505    -26.502      0.000   -6.52e+04   -5.62e+04
district_Shchukino                        4.281e+04   2266.656     18.887      0.000    3.84e+04    4.73e+04
district_Sokol                             3.16e+04   2129.592     14.837      0.000    2.74e+04    3.58e+04
district_Sokolinaya Gora                 -4.376e+04   2053.416    -21.312      0.000   -4.78e+04   -3.97e+04
district_Solntsevo                       -2.093e+04   1968.219    -10.634      0.000   -2.48e+04   -1.71e+04
district_Sosenskoye                      -5.755e+04   2110.231    -27.272      0.000   -6.17e+04   -5.34e+04
district_Strogino                         6.327e+04   2669.512     23.702      0.000     5.8e+04    6.85e+04
district_Sviblovo                        -3.117e+04   2298.433    -13.559      0.000   -3.57e+04   -2.67e+04
district_Tagansky                          1.26e+05   2144.973     58.729      0.000    1.22e+05     1.3e+05
district_Timiryazevsky                   -3432.6370   2020.443     -1.699      0.089   -7392.753     527.479
district_Troitsk                         -5.972e+04   2223.498    -26.857      0.000   -6.41e+04   -5.54e+04
district_Troparyovo-Nikulino              5.195e+04   2128.680     24.405      0.000    4.78e+04    5.61e+04
district_Tsaritsyno                      -5.458e+04   2063.111    -26.453      0.000   -5.86e+04   -5.05e+04
district_Tverskoy                         2.686e+05   2064.414    130.092      0.000    2.65e+05    2.73e+05
district_Tyoply Stan                     -6805.8608   2068.408     -3.290      0.001   -1.09e+04   -2751.731
district_Veshnyaki                       -6.361e+04   2068.703    -30.750      0.000   -6.77e+04   -5.96e+04
district_Vnukovo                         -2.173e+04   2079.795    -10.447      0.000   -2.58e+04   -1.77e+04
district_Vnukovskoye                     -5.868e+04   2090.021    -28.075      0.000   -6.28e+04   -5.46e+04
district_Voronovskoye                    -2.012e+04   2537.794     -7.927      0.000   -2.51e+04   -1.51e+04
district_Voskresenskoye                  -6.885e+04   2137.746    -32.208      0.000    -7.3e+04   -6.47e+04
district_Vostochnoye Izmaylovo            -4.02e+04   2212.262    -18.172      0.000   -4.45e+04   -3.59e+04
district_Vostochny                       -5.507e+04   2331.229    -23.624      0.000   -5.96e+04   -5.05e+04
district_Voykovsky                       -1.312e+04   2175.625     -6.031      0.000   -1.74e+04   -8856.639
district_Yakimanka                         2.42e+05   2175.914    111.221      0.000    2.38e+05    2.46e+05
district_Yaroslavsky                     -3.471e+04   2443.012    -14.208      0.000   -3.95e+04   -2.99e+04
district_Yasenevo                         2.803e+04   2384.533     11.756      0.000    2.34e+04    3.27e+04
district_Yuzhnoye Butovo                 -2.611e+04   2217.841    -11.773      0.000   -3.05e+04   -2.18e+04
district_Yuzhnoye Medvedkovo             -3.812e+04   2370.264    -16.082      0.000   -4.28e+04   -3.35e+04
district_Yuzhnoye Tushino                -5421.8095   2251.507     -2.408      0.016   -9834.818   -1008.801
district_Zamoskvorechye                    1.82e+05   2091.707     87.017      0.000    1.78e+05    1.86e+05
district_Zapadnoye Degunino              -4.376e+04   2319.208    -18.869      0.000   -4.83e+04   -3.92e+04
district_Zelenograd                      -1.709e+04   4099.864     -4.167      0.000   -2.51e+04   -9049.410
district_Zyablikovo                       -5.39e+04   2131.757    -25.285      0.000   -5.81e+04   -4.97e+04
building_type_khrushchev                 -3.779e+04    595.281    -63.477      0.000    -3.9e+04   -3.66e+04
building_type_modern_panel               -9547.9266    551.911    -17.300      0.000   -1.06e+04   -8466.168
building_type_monolith                    9330.8622    551.979     16.904      0.000    8248.971    1.04e+04
building_type_panel                      -2.452e+04    550.222    -44.561      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.137e+04    872.416     35.959      0.000    2.97e+04    3.31e+04
has_balcony_True                          5327.0648    391.011     13.624      0.000    4560.675    6093.455
renovation_designer                       6.403e+04    602.022    106.358      0.000    6.29e+04    6.52e+04
renovation_euro                            2.78e+04    408.484     68.059      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.883e+04    463.649    -40.623      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              3919.7654   2002.928      1.957      0.050      -6.022    7845.553
metro_station_Begovaya                    7684.7324   1879.550      4.089      0.000    4000.768    1.14e+04
metro_station_Chekhovskaya                7951.8304   1976.554      4.023      0.000    4077.738    1.18e+04
metro_station_Chkalovskaya                2922.2882   2028.576      1.441      0.150   -1053.769    6898.345
metro_station_Dinamo                      4866.2076   1671.111      2.912      0.004    1590.790    8141.625
metro_station_Filyovsky Park              3964.7591   1751.611      2.263      0.024     531.560    7397.958
metro_station_Frunzenskaya                 1.07e+04   1965.898      5.441      0.000    6844.021    1.46e+04
metro_station_Kantemirovskaya            -3520.8889   1614.042     -2.181      0.029   -6684.450    -357.327
metro_station_Kievskaya                   2406.9163   1941.335      1.240      0.215   -1398.147    6211.979
metro_station_Komsomolskaya                2.06e+04   1920.235     10.730      0.000    1.68e+04    2.44e+04
metro_station_Krasnopresnenskaya          2.178e+04   1859.227     11.714      0.000    1.81e+04    2.54e+04
metro_station_Kropotkinskaya              7080.6185   1985.158      3.567      0.000    3189.661     1.1e+04
metro_station_Kurskaya                    2181.5416   1966.737      1.109      0.267   -1673.310    6036.393
metro_station_Leninsky Prospekt           8702.8424   1698.557      5.124      0.000    5373.630     1.2e+04
metro_station_Mendeleevskaya              4968.7141   1854.596      2.679      0.007    1333.661    8603.767
metro_station_Nagatinskaya                5037.1390   1839.326      2.739      0.006    1432.016    8642.262
metro_station_Nagornaya                   8065.1644   1548.341      5.209      0.000    5030.378    1.11e+04
metro_station_Novogireyevo                2510.5180   1726.498      1.454      0.146    -873.460    5894.496
metro_station_Novokuznetskaya             6563.8502   2029.125      3.235      0.001    2586.717    1.05e+04
metro_station_Novye Cheryomushki          2678.1242   1493.733      1.793      0.073    -249.628    5605.877
metro_station_Okhotny Ryad                2256.7961   1966.335      1.148      0.251   -1597.268    6110.860
metro_station_Oktyabrskaya                1.077e+04   1897.083      5.677      0.000    7051.132    1.45e+04
metro_station_Park Kultury                7090.7131   2002.692      3.541      0.000    3165.388     1.1e+04
metro_station_Partizanskaya               7677.7272   1911.549      4.016      0.000    3931.044    1.14e+04
metro_station_Perovo                      9362.3637   1788.091      5.236      0.000    5857.663    1.29e+04
metro_station_Pervomayskaya               2894.3681   1807.434      1.601      0.109    -648.247    6436.983
metro_station_Pionerskaya                 4677.4699   1809.418      2.585      0.010    1130.968    8223.972
metro_station_Ploshchad Ilyicha           4573.5395   2092.388      2.186      0.029     472.408    8674.671
metro_station_Polezhaevskaya              6713.5308   1790.544      3.749      0.000    3204.021    1.02e+04
metro_station_Polyanka                    6500.6676   1938.795      3.353      0.001    2700.583    1.03e+04
metro_station_Preobrazhenskaya Ploshchad   1.08e+04   1743.715      6.194      0.000    7382.509    1.42e+04
metro_station_Proletarskaya               7805.4003   2169.392      3.598      0.000    3553.340    1.21e+04
metro_station_Prospekt Mira               1.425e+04   1778.182      8.013      0.000    1.08e+04    1.77e+04
metro_station_Prospekt Vernadskogo        6710.2713   1668.966      4.021      0.000    3439.057    9981.486
metro_station_Pushkinskaya                6126.6299   1931.774      3.172      0.002    2340.306    9912.954
metro_station_Pyatnitskoye Shosse         4068.0204   1972.150      2.063      0.039     202.558    7933.482
metro_station_Rechnoy Vokzal             -3928.5460   1381.611     -2.843      0.004   -6636.536   -1220.556

🏃 View run ols_temporal_pvalue_filtrado_020_sin_rooms at: http://127.0.0.1:5000/#/experiments/4/runs/12514da87fe64b64b9a9b03a3d0f1961
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Variables eliminadas por p-value >= 0.2: 35
Archivo filtrado guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_020_sin_rooms.csv
OLS filtrado 0.20 registrado en MLflow para comparación

### Interpretación

Este filtro es más agresivo y se aplica sobre la versión que ya no contiene `rooms`. La decisión final debe considerar si la reducción de variables conserva o mejora el desempeño temporal de prueba y la estabilidad del modelo.

## 8. Variables ordenadas por p-value del modelo de la seccion 33 - mercado estandar

Esta seccion carga el dataset estandar de la seccion 32, vuelve a ajustar el OLS temporal solo para obtener sus coeficientes y muestra las variables ordenadas desde el p-value mas alto al mas bajo. Es una tabla de consulta; no genera una nueva corrida ni registra artefactos en MLflow.

In [1]:
RUTA_TABLA_PVALUES = Path("data_sets_transformados/secondary_market_modelado_seccion_33.csv")
CORTE_TEMPORAL_TABLA = "2025-01"
df_tabla_pvalues = pd.read_csv(RUTA_TABLA_PVALUES)
df_train_tabla_pvalues = df_tabla_pvalues[df_tabla_pvalues["periodo"] < CORTE_TEMPORAL_TABLA].copy()
X_train_tabla_pvalues = df_train_tabla_pvalues.drop(columns=["price_per_sqm", "periodo"])
y_train_tabla_pvalues = df_train_tabla_pvalues["price_per_sqm"]
X_train_tabla_pvalues_sm = sm.add_constant(X_train_tabla_pvalues, has_constant="add")
resultados_ols_tabla_pvalues = sm.OLS(y_train_tabla_pvalues, X_train_tabla_pvalues_sm).fit()

tabla_pvalues_sin_living_ordenada = pd.DataFrame({
    "variable": resultados_ols_tabla_pvalues.params.index,
    "p_value": resultados_ols_tabla_pvalues.pvalues.to_numpy()
})
tabla_pvalues_sin_living_ordenada = (
    tabla_pvalues_sin_living_ordenada[tabla_pvalues_sin_living_ordenada["variable"] != "const"]
    .sort_values("p_value", ascending=False)
    .reset_index(drop=True)
)
tabla_pvalues_sin_living_ordenada["p_value"] = tabla_pvalues_sin_living_ordenada["p_value"].round(5)

with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(tabla_pvalues_sin_living_ordenada)

                                variable  p_value
         metro_station_Elektrozavodskaya  0.99867
             metro_station_Profsoyuznaya  0.97709
             metro_station_Molodyozhnaya  0.93891
            metro_station_Serpukhovskaya  0.92788
                        district_Kievsky  0.90167
                metro_station_Pechatniki  0.88680
              metro_station_Borovitskaya  0.82076
             metro_station_Chistye Prudy  0.80874
              metro_station_Frunzenskaya  0.80734
            metro_station_Delovoy Tsentr  0.79559
               metro_station_Ugreshskaya  0.77824
                  metro_station_Yasenevo  0.77539
              metro_station_Belorusskaya  0.76965
                                     lon  0.75667
             metro_station_Sukharevskaya  0.72266
          metro_station_Sretensky Bulvar  0.71512
                  metro_station_Trubnaya  0.69976
            metro_station_Kuznetsky Most  0.68205
               metro_station_Park Pobedy  0.67852
               metro_station_Kitay-Gorod  0.67560
               metro_station_Sportivnaya  0.65810
               metro_station_Kakhovskaya  0.65320
                 metro_station_Rizhskaya  0.64139
              metro_station_Oktyabrskaya  0.61795
 metro_station_Ulitsa Akademika Yangelya  0.60691
                  metro_station_Kurskaya  0.60472
          metro_station_Smolenskaya (AP)  0.57690
               metro_station_Teatralnaya  0.56376
                              total_area  0.55124
     metro_station_Ploshchad Revolyutsii  0.54802
             metro_station_Vystavochnaya  0.54198
         district_Ochakovo-Matveyevskoye  0.54172
                    district_Alekseevsky  0.54036
         metro_station_Ploshchad Ilyicha  0.53251
                metro_station_Troparyovo  0.53130
                  metro_station_Dubrovka  0.53119
                      district_Mozhaysky  0.53027
                                   rooms  0.52897
          metro_station_Ulitsa 1905 Goda  0.51857
                district_Maryina Roshcha  0.51405
                 metro_station_Kievskaya  0.51021
           metro_station_Novoslobodskaya  0.50972
            metro_station_Rechnoy Vokzal  0.49657
              metro_station_Chkalovskaya  0.48997
              metro_station_Kutuzovskaya  0.48211
                  metro_station_Rimskaya  0.45252
                  metro_station_Lubyanka  0.44921
              metro_station_Mayakovskaya  0.43402
                             living_area  0.43269
            metro_station_Arbatskaya (F)  0.40292
              metro_station_Dostoevskaya  0.40230
           metro_station_Kantemirovskaya  0.39328
            metro_station_Kozhukhovskaya  0.37886
           metro_station_Smolenskaya (F)  0.35234
              metro_station_Park Kultury  0.34601
                      metro_station_Fili  0.33843
           metro_station_Novokuznetskaya  0.32812
           metro_station_Sevastopolskaya  0.31891
            metro_station_Studencheskaya  0.30667
        metro_station_Krasnopresnenskaya  0.28268
              metro_station_Okhotny Ryad  0.24390
          metro_station_Bagrationovskaya  0.21192
                metro_station_Taganskaya  0.20348
                        district_Konkovo  0.20186
         metro_station_Leninsky Prospekt  0.19591
                 metro_station_Tverskaya  0.19216
         district_Pokrovskoye-Streshnevo  0.18915
             metro_station_Shabolovskaya  0.17775
                     district_Rogovskoye  0.17369
                  metro_station_Polyanka  0.15536
                     district_Danilovsky  0.15433
             metro_station_Turgenevskaya  0.15313
                    district_Ostankinsky  0.13410
        metro_station_Shosse Entuziastov  0.12135
                        district_Zyuzino  0.11950
               metro_station_Universitet  0.11295
              metro_station_Chekhovskaya  0.11247
           metro_station_Tsvetnoy Bulvar  0.10231
             metro_station_Prospekt Mira  0.09367
                      district_Sokolniki  0.08880
            metro_station_Yugo-Zapadnaya  0.08768
            metro_station_Kropotkinskaya  0.08285
            metro_station_Tretyakovskaya  0.07604
             metro_station_Proletarskaya  0.06945
            metro_station_Filyovsky Park  0.06662
              metro_station_Novogireyevo  0.06579
             metro_station_Pervomayskaya  0.05914
              district_Novofyodorovskoye  0.05575
                  district_Timiryazevsky  0.05317
                    district_Tyoply Stan  0.05213
                            kitchen_area  0.04955
                                     lat  0.04756
                  metro_station_Yuzhnaya  0.04662
                       seller_type_owner  0.04459
                            building_age  0.03880
              metro_station_Pushkinskaya  0.03434
        metro_station_Novye Cheryomushki  0.02700
                    metro_station_Dinamo  0.02008
      metro_station_Prospekt Vernadskogo  0.01861
                     metro_station_VDNKh  0.01482
            metro_station_Polezhaevskaya  0.01402
                  metro_station_Begovaya  0.01247
            metro_station_Mendeleevskaya  0.01181
               metro_station_Pionerskaya  0.00814
              metro_station_Nagatinskaya  0.00719
             metro_station_Semyonovskaya  0.00634
                mortgage_rate_at_listing  0.00605
         metro_station_Slavyansky Bulvar  0.00544
           metro_station_Timiryazevskaya  0.00515
                  metro_station_Sviblovo  0.00402
           metro_station_Sapyornoye Pole  0.00398
            metro_station_Tekstilshchiki  0.00397
       metro_station_Pyatnitskoye Shosse  0.00332
               district_Preobrazhenskoye  0.00170
             metro_station_Komsomolskaya  0.00170
                            total_floors  0.00145
               metro_station_Tyoply Stan  0.00132
                  metro_station_Tulskaya  0.00129
               metro_station_Voykovskaya  0.00120
             metro_station_Partizanskaya  0.00044
                                   floor  0.00038
        metro_station_Ulitsa Podbelskogo  0.00006
                   district_Voronovskoye  0.00002
                 metro_station_Sokolniki  0.00001
               district_Yuzhnoye Tushino  0.00001
                         district_Mitino  0.00000
           metro_station_Shchyolkovskaya  0.00000
                  metro_station_Strogino  0.00000
                        district_Kurkino  0.00000
                 metro_station_Nagornaya  0.00000
                   district_Klyonovskoye  0.00000
                       district_Butyrsky  0.00000
                    metro_station_Perovo  0.00000
                        district_Nagorny  0.00000
metro_station_Preobrazhenskaya Ploshchad  0.00000
             metro_station_Shchukinskaya  0.00000
                      district_Voykovsky  0.00000
                       district_Kotlovka  0.00000
                     metro_station_Sokol  0.00000
                        district_Vnukovo  0.00000
               district_Nagatinsky Zaton  0.00000
                district_Yuzhnoye Butovo  0.00000
               district_Severnoye Butovo  0.00000
                    district_Savyolovsky  0.00000
                      district_Solntsevo  0.00000
                       district_Kuntsevo  0.00000
                  district_Pervomayskoye  0.00000
                         district_Perovo  0.00000
                     district_Zelenograd  0.00000
                        district_Donskoy  0.00000
              district_Severnoye Tushino  0.00000
                      district_Izmaylovo  0.00000
                    district_Obruchevsky  0.00000
        district_Mikhaylovo-Yartsevskoye  0.00000
             district_Nagatino-Sadovniki  0.00000
               district_Novo-Peredelkino  0.00000
          district_Khoroshyovo-Mnyovniki  0.00000
                       district_Yasenevo  0.00000
            district_Severnoye Izmaylovo  0.00000
                   district_Levoberezhny  0.00000
                          ceiling_height  0.00000
                  district_Shchapovskoye  0.00000
              district_Krasnopakhorskoye  0.00000
              building_type_modern_panel  0.00000
            district_Chertanovo Yuzhnoye  0.00000
                 district_Molzhaninovsky  0.00000
                            to_center_km  0.00000
                        district_Troitsk  0.00000
                   district_Novogireyevo  0.00000
                     district_Novokosino  0.00000
          district_Vostochnoye Izmaylovo  0.00000
           district_Chertanovo Severnoye  0.00000
                       district_Sviblovo  0.00000
                  district_Ryazanovskoye  0.00000
                  building_type_monolith  0.00000
                    district_Shcherbinka  0.00000
           district_Severnoye Medvedkovo  0.00000
                district_Losinoostrovsky  0.00000
                        district_Koptevo  0.00000
                   district_Babushkinsky  0.00000
          district_Moskvorechye-Saburovo  0.00000
                  district_Desyonovskoye  0.00000
                          district_Sokol  0.00000
                    district_Yaroslavsky  0.00000
                        has_balcony_True  0.00000
                     district_Sosenskoye  0.00000
                   district_Bogorodskoye  0.00000
                     district_Zyablikovo  0.00000
                  district_Akademichesky  0.00000
                 district_Marushkinskoye  0.00000
                     district_Golovinsky  0.00000
                        district_Begovoy  0.00000
                    district_Ivanovskoye  0.00000
                      district_Otradnoye  0.00000
                district_Sokolinaya Gora  0.00000
                   district_Cheryomushki  0.00000
     district_Orekhovo-Borisovo Yuzhnoye  0.00000
                        district_Severny  0.00000
                     district_Tsaritsyno  0.00000
                      district_Moskovsky  0.00000
         district_Biryulyovo Vostochnoye  0.00000
           district_Biryulyovo Zapadnoye  0.00000
                      district_Lianozovo  0.00000
                      district_Rostokino  0.00000
                     district_Kokoshkino  0.00000
                       district_Bibirevo  0.00000
    district_Orekhovo-Borisovo Severnoye  0.00000
                      district_Vostochny  0.00000
               district_Kosino-Ukhtomsky  0.00000
            district_Yuzhnoye Medvedkovo  0.00000
                 district_Fili-Davydkovo  0.00000
                      district_Shchukino  0.00000
                        district_Marfino  0.00000
        district_Chertanovo Tsentralnoye  0.00000
                      district_Golyanovo  0.00000
                      district_Brateyevo  0.00000
                   district_Metrogorodok  0.00000
                    district_Vnukovskoye  0.00000
                 district_Beskudnikovsky  0.00000
                  district_Khoroshyovsky  0.00000
            district_Troparyovo-Nikulino  0.00000
                    district_Altufyevsky  0.00000
                       district_Khovrino  0.00000
                 district_Voskresenskoye  0.00000
                district_Filimonkovskoye  0.00000
                     district_Dmitrovsky  0.00000
                      district_Veshnyaki  0.00000
                     district_Mosrentgen  0.00000
                    district_Krylatskoye  0.00000
             district_Zapadnoye Degunino  0.00000
                       district_Strogino  0.00000
                 district_Filyovsky Park  0.00000
           district_Prospekt Vernadskogo  0.00000
                   district_Lomonosovsky  0.00000
                    building_type_stalin  0.00000
                       date_posted_month  0.00000
                     district_Gagarinsky  0.00000
                        district_Ramenki  0.00000
                metro_distance_type_walk  0.00000
                        date_posted_year  0.00000
                      metro_distance_min  0.00000
                       district_Tagansky  0.00000
                renovation_no_renovation  0.00000
                    district_Meshchansky  0.00000
                     district_Presnensky  0.00000
                     building_type_panel  0.00000
                         renovation_euro  0.00000
                building_type_khrushchev  0.00000
                 district_Zamoskvorechye  0.00000
                      district_Yakimanka  0.00000
                       district_Tverskoy  0.00000
                     renovation_designer  0.00000
                   district_Krasnoselsky  0.00000
                   district_Dorogomilovo  0.00000
                       district_Basmanny  0.00000
                     district_Khamovniki  0.00000
                          district_Arbat  0.00000

### Interpretación

Las primeras filas son las variables con mayor p-value dentro del modelo sin `living_area` ni `lon`. Esta tabla sirve para revisar el orden y discutir variables, pero no elimina columnas ni modifica las corridas existentes.

## 9. OLS sin `living_area`

Partimos del modelo `ols_temporal_pvalue_filtrado_090` y eliminamos únicamente `living_area`. La variable `total_area` se conserva porque representa la superficie total. Se mantiene el mismo corte temporal para comparar las métricas de forma consistente.

In [9]:
# Configuración de esta variante del modelo.
VARIABLE_ELIMINADA_LIVING = "living_area"
RUTA_SALIDA_SIN_LIVING = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_090_sin_living_area.csv")

# Trabajamos sobre una copia del dataset p90 y no sobrescribimos el archivo anterior.
if VARIABLE_ELIMINADA_LIVING not in df_ols_filtrado.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_LIVING!r} no está disponible en el modelo p90")
df_ols_sin_living = df_ols_filtrado.drop(columns=[VARIABLE_ELIMINADA_LIVING]).copy()
df_ols_sin_living.to_csv(RUTA_SALIDA_SIN_LIVING, index=False)

# Separamos entrenamiento y prueba respetando el mismo corte temporal mensual.
df_train_sin_living = df_ols_sin_living[df_ols_sin_living["periodo"] < CORTE_TEMPORAL].copy()
df_test_sin_living = df_ols_sin_living[df_ols_sin_living["periodo"] >= CORTE_TEMPORAL].copy()
X_train_sin_living = df_train_sin_living.drop(columns=["price_per_sqm", "periodo"])
X_test_sin_living = df_test_sin_living.drop(columns=["price_per_sqm", "periodo"])
y_train_sin_living = df_train_sin_living["price_per_sqm"]
y_test_sin_living = df_test_sin_living["price_per_sqm"]

# Ajustamos OLS con constante explícita.
X_train_sin_living_sm = sm.add_constant(X_train_sin_living, has_constant="add")
X_test_sin_living_sm = sm.add_constant(X_test_sin_living, has_constant="add")
modelo_ols_sin_living = sm.OLS(y_train_sin_living, X_train_sin_living_sm)
resultados_ols_sin_living = modelo_ols_sin_living.fit()
predicciones_train_sin_living = resultados_ols_sin_living.predict(X_train_sin_living_sm)
predicciones_test_sin_living = resultados_ols_sin_living.predict(X_test_sin_living_sm)

# Calculamos las métricas predictivas y los diagnósticos OLS.
metricas_ols_sin_living = {
    **calcular_metricas_regresion(y_train_sin_living, predicciones_train_sin_living, "train"),
    **calcular_metricas_regresion(y_test_sin_living, predicciones_test_sin_living, "test"),
    "r2_ols": float(resultados_ols_sin_living.rsquared),
    "r2_ajustado_ols": float(resultados_ols_sin_living.rsquared_adj),
    "aic_ols": float(resultados_ols_sin_living.aic),
    "bic_ols": float(resultados_ols_sin_living.bic),
    "f_statistic_ols": float(resultados_ols_sin_living.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_sin_living.f_pvalue)
}
omnibus_sin_living, prob_omnibus_sin_living = omni_normtest(resultados_ols_sin_living.resid)
jarque_bera_sin_living, prob_jb_sin_living, skew_sin_living, kurtosis_sin_living = jarque_bera(resultados_ols_sin_living.resid)
metricas_ols_sin_living.update({
    "omnibus_ols": float(omnibus_sin_living),
    "prob_omnibus_ols": float(prob_omnibus_sin_living),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_sin_living.resid)),
    "jarque_bera_ols": float(jarque_bera_sin_living),
    "prob_jb_ols": float(prob_jb_sin_living),
    "skew_ols": float(skew_sin_living),
    "kurtosis_ols": float(kurtosis_sin_living),
    "condition_number_ols": float(resultados_ols_sin_living.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_sin_living.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_sin_living.pvalues > 0.05).sum())
})

coeficientes_ols_sin_living = pd.DataFrame({
    "variable": resultados_ols_sin_living.params.index,
    "coeficiente": resultados_ols_sin_living.params.to_numpy(),
    "p_value": resultados_ols_sin_living.pvalues.to_numpy(),
    "significativa_0_05": resultados_ols_sin_living.pvalues.to_numpy() <= 0.05
})
residuos_test_sin_living = pd.DataFrame({
    "periodo": df_test_sin_living["periodo"].to_numpy(),
    "real": y_test_sin_living.to_numpy(),
    "prediccion": predicciones_test_sin_living.to_numpy(),
    "residuo": (y_test_sin_living.to_numpy() - predicciones_test_sin_living.to_numpy())
})

comparacion_ols_sin_living = pd.DataFrame([
    {"modelo": "OLS p-value 0.90", **metricas_ols_temporal},
    {"modelo": "OLS sin living_area", **metricas_ols_sin_living}
])
delta_metricas_sin_living = {
    f"delta_{metrica}": metricas_ols_sin_living[metrica] - metricas_ols_temporal[metrica]
    for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]
}

display(comparacion_ols_sin_living[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
print(resultados_ols_sin_living.summary())

# Registramos la nueva variante y sus artefactos en el mismo experimento.
RUN_OLS_P90_ID = "45a11b38934a495eb7a148c8fa9d3f92"
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_sin_living_area"):
    mlflow.set_tag("run_anterior_id", RUN_OLS_P90_ID)
    mlflow.log_params({
        "dataset": str(RUTA_SALIDA_SIN_LIVING),
        "dataset_origen": str(RUTA_OLS),
        "objetivo": "price_per_sqm",
        "corte_temporal": CORTE_TEMPORAL,
        "variable_eliminada": VARIABLE_ELIMINADA_LIVING,
        "n_predictores": X_train_sin_living.shape[1],
        "filas_entrenamiento": len(df_train_sin_living),
        "filas_prueba": len(df_test_sin_living),
        "tipo_modelo": "statsmodels_OLS_sin_living_area"
    })
    mlflow.log_metrics({**metricas_ols_sin_living, **delta_metricas_sin_living})
    mlflow.log_table(comparacion_ols_sin_living, artifact_file="comparacion/comparacion_ols_sin_living_area.json")
    mlflow.log_table(coeficientes_ols_sin_living, artifact_file="modelo/coeficientes_ols_sin_living_area.json")
    mlflow.log_table(residuos_test_sin_living, artifact_file="diagnostico/residuos_test_sin_living_area.json")
    mlflow.log_text(resultados_ols_sin_living.summary().as_text(), "modelo/resumen_ols_sin_living_area.txt")

print(f"Archivo sin living_area guardado en: {RUTA_SALIDA_SIN_LIVING}")
print("OLS sin living_area registrado en MLflow para comparación")

                modelo      mae_test     rmse_test   r2_test  mape_test
0     OLS p-value 0.90  37085.586046  45132.632765  0.859828  23.174104
1  OLS sin living_area  37084.571782  45132.405888  0.859829  23.173753

                            OLS Regression Results
==============================================================================
Dep. Variable:          price_per_sqm   R-squared:                       0.908
Model:                            OLS   Adj. R-squared:                  0.908
Method:                 Least Squares   F-statistic:                     1579.
Date:                Mon, 12 Oct 2026   Prob (F-statistic):               0.00
Time:                        23:07:59   Log-Likelihood:            -4.6952e+05
No. Observations:               39658   AIC:                         9.395e+05
Df Residuals:                   39410   BIC:                         9.417e+05
Df Model:                         247
Covariance Type:            nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
const                                    -3.122e+07   7.46e+05    -41.873      0.000   -3.27e+07   -2.98e+07
lat                                      -4.058e+04   1.08e+04     -3.767      0.000   -6.17e+04   -1.95e+04
lon                                      -3707.4093   8089.425     -0.458      0.647   -1.96e+04    1.21e+04
total_area                                  14.6627     21.309      0.688      0.491     -27.103      56.429
kitchen_area                               114.3819     70.157      1.630      0.103     -23.128     251.892
rooms                                     -265.3709    375.236     -0.707      0.479   -1000.842     470.100
floor                                      134.4138     37.924      3.544      0.000      60.083     208.745
total_floors                                39.2370     32.025      1.225      0.221     -23.534     102.008
ceiling_height                            8507.8064    920.890      9.239      0.000    6702.840    1.03e+04
metro_distance_min                        -419.4261      9.983    -42.015      0.000    -438.992    -399.860
to_center_km                             -1479.8421    112.784    -13.121      0.000   -1700.902   -1258.782
mortgage_rate_at_listing                   -94.7008     52.596     -1.801      0.072    -197.790       8.389
date_posted_year                          1.672e+04    190.707     87.667      0.000    1.63e+04    1.71e+04
date_posted_month                         1239.7978     49.114     25.243      0.000    1143.533    1336.063
building_age                                10.7588     17.087      0.630      0.529     -22.733      44.250
district_Akademichesky                    3.939e+04   2271.278     17.343      0.000    3.49e+04    4.38e+04
district_Alekseevsky                     -1177.5942   2320.129     -0.508      0.612   -5725.104    3369.916
district_Altufyevsky                      -4.02e+04   2993.028    -13.430      0.000   -4.61e+04   -3.43e+04
district_Arbat                            2.668e+05   2367.979    112.671      0.000    2.62e+05    2.71e+05
district_Babushkinsky                    -3.178e+04   2959.802    -10.739      0.000   -3.76e+04    -2.6e+04
district_Basmanny                         1.399e+05   2335.662     59.910      0.000    1.35e+05    1.45e+05
district_Begovoy                          3.261e+04   2223.994     14.663      0.000    2.83e+04     3.7e+04
district_Beskudnikovsky                  -3.832e+04   2853.133    -13.430      0.000   -4.39e+04   -3.27e+04
district_Bibirevo                        -3.644e+04   2974.135    -12.251      0.000   -4.23e+04   -3.06e+04
district_Biryulyovo Vostochnoye          -5.709e+04   3076.382    -18.556      0.000   -6.31e+04   -5.11e+04
district_Biryulyovo Zapadnoye            -5.608e+04   2913.022    -19.250      0.000   -6.18e+04   -5.04e+04
district_Bogorodskoye                    -3.817e+04   2726.998    -13.997      0.000   -4.35e+04   -3.28e+04
district_Brateyevo                       -5.614e+04   3212.880    -17.473      0.000   -6.24e+04   -4.98e+04
district_Butyrsky                        -1.086e+04   2350.489     -4.622      0.000   -1.55e+04   -6257.621
district_Chertanovo Severnoye            -4.123e+04   2542.737    -16.216      0.000   -4.62e+04   -3.63e+04
district_Chertanovo Tsentralnoye         -5.317e+04   2594.914    -20.490      0.000   -5.83e+04   -4.81e+04
district_Chertanovo Yuzhnoye             -4.641e+04   2974.275    -15.604      0.000   -5.22e+04   -4.06e+04
district_Cheryomushki                     4.424e+04   2432.124     18.190      0.000    3.95e+04     4.9e+04
district_Desyonovskoye                   -5.721e+04   2593.187    -22.062      0.000   -6.23e+04   -5.21e+04
district_Dmitrovsky                       -4.22e+04   2935.834    -14.375      0.000    -4.8e+04   -3.64e+04
district_Donskoy                          1.584e+04   2410.297      6.574      0.000    1.11e+04    2.06e+04
district_Dorogomilovo                     1.346e+05   2313.300     58.188      0.000     1.3e+05    1.39e+05
district_Fili-Davydkovo                   3.952e+04   2287.948     17.273      0.000     3.5e+04     4.4e+04
district_Filimonkovskoye                 -7.288e+04   2294.550    -31.761      0.000   -7.74e+04   -6.84e+04
district_Filyovsky Park                   5.568e+04   2296.109     24.250      0.000    5.12e+04    6.02e+04
district_Gagarinsky                       8.085e+04   2348.099     34.432      0.000    7.62e+04    8.55e+04
district_Golovinsky                      -3.284e+04   2614.471    -12.560      0.000    -3.8e+04   -2.77e+04
district_Golyanovo                       -5.082e+04   3383.326    -15.022      0.000   -5.75e+04   -4.42e+04
district_Ivanovskoye                     -4.769e+04   3375.689    -14.127      0.000   -5.43e+04   -4.11e+04
district_Izmaylovo                       -2.159e+04   2990.445     -7.218      0.000   -2.74e+04   -1.57e+04
district_Khamovniki                       2.911e+05   2329.102    124.993      0.000    2.87e+05    2.96e+05
district_Khoroshyovo-Mnyovniki            2.247e+04   2400.250      9.360      0.000    1.78e+04    2.72e+04
district_Khoroshyovsky                    4.075e+04   2313.757     17.610      0.000    3.62e+04    4.53e+04
district_Khovrino                         -4.06e+04   2907.925    -13.963      0.000   -4.63e+04   -3.49e+04
district_Kievsky                          1.769e+04   3171.142      5.577      0.000    1.15e+04    2.39e+04
district_Klyonovskoye                    -2.389e+04   4748.291     -5.031      0.000   -3.32e+04   -1.46e+04
district_Kokoshkino                       -6.37e+04   2553.502    -24.947      0.000   -6.87e+04   -5.87e+04
district_Konkovo                          2599.6284   2268.723      1.146      0.252   -1847.124    7046.381
district_Koptevo                         -2.813e+04   2634.383    -10.678      0.000   -3.33e+04    -2.3e+04
district_Kosino-Ukhtomsky                -5.482e+04   3642.897    -15.048      0.000    -6.2e+04   -4.77e+04
district_Kotlovka                         1.204e+04   2400.093      5.015      0.000    7333.232    1.67e+04
district_Krasnopakhorskoye               -5.901e+04   2548.147    -23.158      0.000    -6.4e+04    -5.4e+04
district_Krasnoselsky                     1.265e+05   2421.749     52.233      0.000    1.22e+05    1.31e+05
district_Krylatskoye                      5.413e+04   2464.942     21.959      0.000    4.93e+04     5.9e+04
district_Kuntsevo                         1.664e+04   2372.765      7.015      0.000     1.2e+04    2.13e+04
district_Kurkino                          2.119e+04   3372.324      6.282      0.000    1.46e+04    2.78e+04
district_Levoberezhny                    -2.291e+04   2829.824     -8.097      0.000   -2.85e+04   -1.74e+04
district_Lianozovo                       -3.734e+04   3223.058    -11.585      0.000   -4.37e+04    -3.1e+04
district_Lomonosovsky                     7.406e+04   2318.545     31.942      0.000    6.95e+04    7.86e+04
district_Losinoostrovsky                 -3.166e+04   3183.428     -9.945      0.000   -3.79e+04   -2.54e+04
district_Marfino                         -3.578e+04   2522.358    -14.183      0.000   -4.07e+04   -3.08e+04
district_Marushkinskoye                  -6.392e+04   2258.808    -28.300      0.000   -6.84e+04   -5.95e+04
district_Meshchansky                      1.561e+05   2285.673     68.312      0.000    1.52e+05    1.61e+05
district_Metrogorodok                     -4.64e+04   3059.853    -15.163      0.000   -5.24e+04   -4.04e+04
district_Mikhaylovo-Yartsevskoye         -4.631e+04   2454.470    -18.866      0.000   -5.11e+04   -4.15e+04
district_Mitino                          -1.313e+04   3297.877     -3.982      0.000   -1.96e+04   -6666.990
district_Molzhaninovsky                  -3.094e+04   4155.481     -7.445      0.000   -3.91e+04   -2.28e+04
district_Moskovsky                       -5.734e+04   2297.975    -24.954      0.000   -6.18e+04   -5.28e+04
district_Moskvorechye-Saburovo           -4.312e+04   2690.260    -16.029      0.000   -4.84e+04   -3.78e+04
district_Mosrentgen                      -7.011e+04   2515.619    -27.869      0.000    -7.5e+04   -6.52e+04
district_Mozhaysky                        1678.9735   2394.495      0.701      0.483   -3014.294    6372.241
district_Nagatino-Sadovniki              -2.652e+04   2595.257    -10.217      0.000   -3.16e+04   -2.14e+04
district_Nagatinsky Zaton                -2.112e+04   2640.087     -8.002      0.000   -2.63e+04    -1.6e+04
district_Nagorny                         -1.794e+04   2561.983     -7.003      0.000    -2.3e+04   -1.29e+04
district_Novo-Peredelkino                -2.619e+04   2330.497    -11.236      0.000   -3.08e+04   -2.16e+04
district_Novogireyevo                    -3.966e+04   3224.022    -12.302      0.000    -4.6e+04   -3.33e+04
district_Novokosino                      -4.041e+04   3773.505    -10.709      0.000   -4.78e+04    -3.3e+04
district_Obruchevsky                      2.189e+04   2385.889      9.177      0.000    1.72e+04    2.66e+04
district_Ochakovo-Matveyevskoye            683.8084   2282.601      0.300      0.765   -3790.145    5157.762
district_Orekhovo-Borisovo Severnoye     -5.438e+04   3062.191    -17.758      0.000   -6.04e+04   -4.84e+04
district_Orekhovo-Borisovo Yuzhnoye      -5.246e+04   3116.472    -16.834      0.000   -5.86e+04   -4.64e+04
district_Ostankinsky                     -1749.2489   2466.727     -0.709      0.478   -6584.093    3085.595
district_Otradnoye                       -3.245e+04   2757.986    -11.767      0.000   -3.79e+04    -2.7e+04
district_Perovo                          -2.629e+04   3252.324     -8.082      0.000   -3.27e+04   -1.99e+04
district_Pervomayskoye                   -3.818e+04   2477.356    -15.410      0.000    -4.3e+04   -3.33e+04
district_Pokrovskoye-Streshnevo           -832.7197   2552.013     -0.326      0.744   -5834.728    4169.288
district_Preobrazhenskoye                -1.084e+04   2778.331     -3.903      0.000   -1.63e+04   -5398.620
district_Presnensky                       2.448e+05   2371.848    103.215      0.000     2.4e+05    2.49e+05
district_Prospekt Vernadskogo             7.415e+04   2297.891     32.268      0.000    6.96e+04    7.87e+04
district_Ramenki                          7.422e+04   2273.667     32.645      0.000    6.98e+04    7.87e+04
district_Rogovskoye                       4869.7292   3002.537      1.622      0.105   -1015.316    1.08e+04
district_Rostokino                       -3.727e+04   2567.644    -14.517      0.000   -4.23e+04   -3.22e+04
district_Ryazanovskoye                   -6.061e+04   3065.411    -19.773      0.000   -6.66e+04   -5.46e+04
district_Savyolovsky                      1.599e+04   2303.687      6.943      0.000    1.15e+04    2.05e+04
district_Severnoye Butovo                -2.425e+04   2735.382     -8.864      0.000   -2.96e+04   -1.89e+04
district_Severnoye Izmaylovo             -3.247e+04   3454.040     -9.399      0.000   -3.92e+04   -2.57e+04
district_Severnoye Medvedkovo            -2.921e+04   3077.551     -9.493      0.000   -3.52e+04   -2.32e+04
district_Severnoye Tushino               -1.548e+04   2813.169     -5.502      0.000    -2.1e+04   -9963.396
district_Severny                         -3.784e+04   3641.700    -10.392      0.000    -4.5e+04   -3.07e+04
district_Shchapovskoye                   -5.908e+04   3909.568    -15.111      0.000   -6.67e+04   -5.14e+04
district_Shcherbinka                     -5.839e+04   3176.258    -18.384      0.000   -6.46e+04   -5.22e+04
district_Shchukino                        4.227e+04   2628.825     16.078      0.000    3.71e+04    4.74e+04
district_Sokol                            3.125e+04   2406.310     12.988      0.000    2.65e+04     3.6e+04
district_Sokolinaya Gora                 -4.301e+04   2679.470    -16.052      0.000   -4.83e+04   -3.78e+04
district_Sokolniki                        1665.3134   2569.495      0.648      0.517   -3370.959    6701.586
district_Solntsevo                       -2.037e+04   2188.357     -9.310      0.000   -2.47e+04   -1.61e+04
district_Sosenskoye                      -5.619e+04   2349.776    -23.912      0.000   -6.08e+04   -5.16e+04
district_Strogino                         6.237e+04   3067.883     20.330      0.000    5.64e+04    6.84e+04
district_Sviblovo                        -3.149e+04   2782.340    -11.319      0.000   -3.69e+04    -2.6e+04
district_Tagansky                         1.269e+05   2427.339     52.283      0.000    1.22e+05    1.32e+05
district_Timiryazevsky                   -3634.4038   2300.645     -1.580      0.114   -8143.724     874.917
district_Troitsk                         -5.857e+04   2412.175    -24.282      0.000   -6.33e+04   -5.38e+04
district_Troparyovo-Nikulino              5.281e+04   2364.082     22.338      0.000    4.82e+04    5.74e+04
district_Tsaritsyno                      -5.253e+04   2891.024    -18.171      0.000   -5.82e+04   -4.69e+04
district_Tverskoy                          2.69e+05   2295.804    117.156      0.000    2.64e+05    2.73e+05
district_Tyoply Stan                     -5542.8849   2300.753     -2.409      0.016   -1.01e+04   -1033.354
district_Veshnyaki                       -6.216e+04   3315.632    -18.747      0.000   -6.87e+04   -5.57e+04
district_Vnukovo                          -2.17e+04   2367.401     -9.168      0.000   -2.63e+04   -1.71e+04
district_Vnukovskoye                     -5.859e+04   2328.515    -25.163      0.000   -6.32e+04    -5.4e+04
district_Voronovskoye                    -1.813e+04   3084.966     -5.878      0.000   -2.42e+04   -1.21e+04
district_Voskresenskoye                  -6.757e+04   2342.740    -28.843      0.000   -7.22e+04    -6.3e+04
district_Vostochnoye Izmaylovo           -3.941e+04   3471.515    -11.351      0.000   -4.62e+04   -3.26e+04
district_Vostochny                       -5.439e+04   3974.796    -13.684      0.000   -6.22e+04   -4.66e+04
district_Voykovsky                       -1.365e+04   2505.878     -5.446      0.000   -1.86e+04   -8735.326
district_Yakimanka                        2.429e+05   2406.354    100.948      0.000    2.38e+05    2.48e+05
district_Yaroslavsky                       -3.5e+04   3278.543    -10.675      0.000   -4.14e+04   -2.86e+04
district_Yasenevo                         2.968e+04   2687.051     11.045      0.000    2.44e+04    3.49e+04
district_Yuzhnoye Butovo                 -2.422e+04   2806.497     -8.630      0.000   -2.97e+04   -1.87e+04
district_Yuzhnoye Medvedkovo             -3.874e+04   2996.053    -12.929      0.000   -4.46e+04   -3.29e+04
district_Yuzhnoye Tushino                -6471.7108   2722.251     -2.377      0.017   -1.18e+04   -1136.034
district_Zamoskvorechye                    1.83e+05   2335.197     78.367      0.000    1.78e+05    1.88e+05
district_Zapadnoye Degunino              -4.455e+04   2747.490    -16.216      0.000   -4.99e+04   -3.92e+04
district_Zelenograd                      -2.087e+04   5376.757     -3.882      0.000   -3.14e+04   -1.03e+04
district_Zyablikovo                      -5.175e+04   3327.897    -15.550      0.000   -5.83e+04   -4.52e+04
district_Zyuzino                          2125.8417   2448.330      0.868      0.385   -2672.944    6924.627
building_type_khrushchev                 -3.796e+04    647.078    -58.663      0.000   -3.92e+04   -3.67e+04
building_type_modern_panel               -9204.7297    781.264    -11.782      0.000   -1.07e+04   -7673.434
building_type_monolith                    9674.6474    780.654     12.393      0.000    8144.547    1.12e+04
building_type_panel                      -2.449e+04    550.613    -44.486      0.000   -2.56e+04   -2.34e+04
building_type_stalin                      3.099e+04   1044.397     29.668      0.000    2.89e+04     3.3e+04
has_balcony_True                          5333.4301    391.292     13.630      0.000    4566.489    6100.372
renovation_designer                         6.4e+04    602.469    106.237      0.000    6.28e+04    6.52e+04
renovation_euro                            2.78e+04    408.758     68.014      0.000     2.7e+04    2.86e+04
renovation_no_renovation                 -1.881e+04    464.034    -40.540      0.000   -1.97e+04   -1.79e+04
metro_station_Arbatskaya (F)              4749.2745   2092.989      2.269      0.023     646.965    8851.584
metro_station_Bagrationovskaya           -1203.8574   2016.880     -0.597      0.551   -5156.991    2749.276
metro_station_Begovaya                    8572.4570   1976.226      4.338      0.000    4699.007    1.24e+04
metro_station_Belorusskaya                 930.3823   2020.776      0.460      0.645   -3030.388    4891.152
metro_station_Borovitskaya                 642.4721   2105.220      0.305      0.760   -3483.810    4768.754
metro_station_Chekhovskaya                8824.5898   2068.932      4.265      0.000    4769.433    1.29e+04
metro_station_Chistye Prudy               1804.8696   2014.689      0.896      0.370   -2143.970    5753.709
metro_station_Chkalovskaya                3761.7160   2120.451      1.774      0.076    -394.420    7917.851
metro_station_Delovoy Tsentr              2543.4211   2096.733      1.213      0.225   -1566.226    6653.068
metro_station_Dinamo                      5734.5264   1779.389      3.223      0.001    2246.882    9222.171
metro_station_Dostoevskaya                1496.3419   1978.969      0.756      0.450   -2382.486    5375.170
metro_station_Dubrovka                    2296.7553   2153.284      1.067      0.286   -1923.734    6517.244
metro_station_Elektrozavodskaya           1276.2539   2047.154      0.623      0.533   -2736.218    5288.726
metro_station_Fili                       -1263.5539   1993.571     -0.634      0.526   -5171.001    2643.893
metro_station_Filyovsky Park              4723.8913   1853.105      2.549      0.011    1091.760    8356.023
metro_station_Frunzenskaya                1.152e+04   2056.151      5.600      0.000    7485.170    1.55e+04
metro_station_Kakhovskaya                 -905.5818   1717.953     -0.527      0.598   -4272.812    2461.648
metro_station_Kantemirovskaya            -2818.3257   1719.511     -1.639      0.101   -6188.608     551.957
metro_station_Kievskaya                   3247.6808   2034.460      1.596      0.110    -739.911    7235.272
metro_station_Kitay-Gorod                 1314.7534   2293.586      0.573      0.566   -3180.731    5810.238
metro_station_Komsomolskaya               2.147e+04   2018.353     10.638      0.000    1.75e+04    2.54e+04
metro_station_Kozhukhovskaya              -720.4734   2130.862     -0.338      0.735   -4897.015    3456.068
metro_station_Krasnopresnenskaya          2.261e+04   1952.889     11.579      0.000    1.88e+04    2.64e+04
metro_station_Kropotkinskaya              7892.4226   2075.881      3.802      0.000    3823.645     1.2e+04

🏃 View run ols_temporal_sin_living_area at: http://127.0.0.1:5000/#/experiments/4/runs/f0682766f6094c9b86a6e78392c0dd78
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Archivo sin living_area guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_090_sin_living_area.csv
OLS sin living_area registrado en MLflow para comparación

### Interpretación

La comparación debe centrarse en las métricas temporales de prueba y en el número de condición. Si quitar `living_area` reduce la colinealidad sin empeorar de forma relevante MAE, RMSE, R² y MAPE, puede ser una simplificación razonable del modelo.

## 10. OLS sin `lon`

Partimos del último dataset sin `living_area` y eliminamos `lon`. `lat` se conserva para evaluar si la coordenada longitudinal aporta información adicional junto con las variables geográficas categóricas.

In [10]:
VARIABLE_ELIMINADA_LON = "lon"
RUTA_SALIDA_SIN_LON = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_090_sin_living_area_sin_lon.csv")
df_ols_sin_living_para_lon = pd.read_csv(RUTA_SALIDA_SIN_LIVING)
if VARIABLE_ELIMINADA_LON not in df_ols_sin_living_para_lon.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_LON!r} no está disponible")
df_ols_sin_lon = df_ols_sin_living_para_lon.drop(columns=[VARIABLE_ELIMINADA_LON]).copy()
df_ols_sin_lon.to_csv(RUTA_SALIDA_SIN_LON, index=False)
df_train_sin_lon = df_ols_sin_lon[df_ols_sin_lon["periodo"] < CORTE_TEMPORAL].copy()
df_test_sin_lon = df_ols_sin_lon[df_ols_sin_lon["periodo"] >= CORTE_TEMPORAL].copy()
X_train_sin_lon = df_train_sin_lon.drop(columns=["price_per_sqm", "periodo"])
X_test_sin_lon = df_test_sin_lon.drop(columns=["price_per_sqm", "periodo"])
y_train_sin_lon = df_train_sin_lon["price_per_sqm"]
y_test_sin_lon = df_test_sin_lon["price_per_sqm"]
X_train_sin_lon_sm = sm.add_constant(X_train_sin_lon, has_constant="add")
X_test_sin_lon_sm = sm.add_constant(X_test_sin_lon, has_constant="add")
resultados_ols_sin_lon = sm.OLS(y_train_sin_lon, X_train_sin_lon_sm).fit()
predicciones_train_sin_lon = resultados_ols_sin_lon.predict(X_train_sin_lon_sm)
predicciones_test_sin_lon = resultados_ols_sin_lon.predict(X_test_sin_lon_sm)
metricas_ols_sin_lon = {
    **calcular_metricas_regresion(y_train_sin_lon, predicciones_train_sin_lon, "train"),
    **calcular_metricas_regresion(y_test_sin_lon, predicciones_test_sin_lon, "test"),
    "r2_ols": float(resultados_ols_sin_lon.rsquared),
    "r2_ajustado_ols": float(resultados_ols_sin_lon.rsquared_adj),
    "aic_ols": float(resultados_ols_sin_lon.aic),
    "bic_ols": float(resultados_ols_sin_lon.bic),
    "f_statistic_ols": float(resultados_ols_sin_lon.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_sin_lon.f_pvalue),
    "condition_number_ols": float(resultados_ols_sin_lon.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_sin_lon.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_sin_lon.pvalues > 0.05).sum())
}
omnibus_sin_lon, prob_omnibus_sin_lon = omni_normtest(resultados_ols_sin_lon.resid)
jarque_bera_sin_lon, prob_jb_sin_lon, skew_sin_lon, kurtosis_sin_lon = jarque_bera(resultados_ols_sin_lon.resid)
metricas_ols_sin_lon.update({
    "omnibus_ols": float(omnibus_sin_lon),
    "prob_omnibus_ols": float(prob_omnibus_sin_lon),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_sin_lon.resid)),
    "jarque_bera_ols": float(jarque_bera_sin_lon),
    "prob_jb_ols": float(prob_jb_sin_lon),
    "skew_ols": float(skew_sin_lon),
    "kurtosis_ols": float(kurtosis_sin_lon)
})
coeficientes_ols_sin_lon = pd.DataFrame({"variable": resultados_ols_sin_lon.params.index, "coeficiente": resultados_ols_sin_lon.params.to_numpy(), "p_value": resultados_ols_sin_lon.pvalues.to_numpy(), "significativa_0_05": resultados_ols_sin_lon.pvalues.to_numpy() <= 0.05})
residuos_test_sin_lon = pd.DataFrame({"periodo": df_test_sin_lon["periodo"].to_numpy(), "real": y_test_sin_lon.to_numpy(), "prediccion": predicciones_test_sin_lon.to_numpy(), "residuo": y_test_sin_lon.to_numpy() - predicciones_test_sin_lon.to_numpy()})
comparacion_ols_sin_lon = pd.DataFrame([{"modelo": "OLS sin living_area", **metricas_ols_sin_living}, {"modelo": "OLS sin living_area ni lon", **metricas_ols_sin_lon}])
delta_metricas_sin_lon = {f"delta_{metrica}": metricas_ols_sin_lon[metrica] - metricas_ols_sin_living[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_sin_lon[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_sin_living_area_sin_lon"):
    mlflow.set_tag("run_anterior_id", "3e5b2762c30f42df8b4805ec3d3c5f3e")
    mlflow.log_params({"dataset": str(RUTA_SALIDA_SIN_LON), "dataset_origen": str(RUTA_SALIDA_SIN_LIVING), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_LON, "n_predictores": X_train_sin_lon.shape[1], "filas_entrenamiento": len(df_train_sin_lon), "filas_prueba": len(df_test_sin_lon), "tipo_modelo": "statsmodels_OLS_sin_living_area_sin_lon"})
    mlflow.log_metrics({**metricas_ols_sin_lon, **delta_metricas_sin_lon})
    mlflow.log_table(comparacion_ols_sin_lon, artifact_file="comparacion/comparacion_ols_sin_living_area_sin_lon.json")
    mlflow.log_table(coeficientes_ols_sin_lon, artifact_file="modelo/coeficientes_ols_sin_living_area_sin_lon.json")
    mlflow.log_table(residuos_test_sin_lon, artifact_file="diagnostico/residuos_test_sin_living_area_sin_lon.json")
    mlflow.log_text(resultados_ols_sin_lon.summary().as_text(), "modelo/resumen_ols_sin_living_area_sin_lon.txt")
print(f"Archivo sin living_area ni lon guardado en: {RUTA_SALIDA_SIN_LON}")
print("OLS sin living_area ni lon registrado en MLflow para comparación")

                       modelo      mae_test     rmse_test   r2_test  mape_test
0         OLS sin living_area  37084.571782  45132.405888  0.859829  23.173753
1  OLS sin living_area ni lon  37084.667719  45131.738718  0.859834  23.172933

🏃 View run ols_temporal_sin_living_area_sin_lon at: http://127.0.0.1:5000/#/experiments/4/runs/73a2ec1cafaf4e78b6784f79494d2bf7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Archivo sin living_area ni lon guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_090_sin_living_area_sin_lon.csv
OLS sin living_area ni lon registrado en MLflow para comparación

### Interpretación

La eliminación de `lon` se evalúa comparando las métricas temporales y el número de condición contra el modelo anterior. La tabla de p-values de la sección 8 refleja esta variante sin `living_area` ni `lon`.

## 11. OLS sin `district_Pokrovskoye-Streshnevo`

Partimos del modelo sin `living_area` ni `lon` y eliminamos únicamente la dummy `district_Pokrovskoye-Streshnevo`. Se conserva el resto de las variables de distrito y estación de metro.

In [11]:
VARIABLE_ELIMINADA_DISTRICT = "district_Pokrovskoye-Streshnevo"
RUTA_SALIDA_SIN_DISTRICT = Path("data_sets_transformados/secondary_market_modelado_one_hot_pvalue_090_sin_living_area_sin_lon_sin_district_pokrovskoye_streshnevo.csv")
df_ols_sin_lon_para_district = pd.read_csv(RUTA_SALIDA_SIN_LON)
if VARIABLE_ELIMINADA_DISTRICT not in df_ols_sin_lon_para_district.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_DISTRICT!r} no está disponible")
df_ols_sin_district = df_ols_sin_lon_para_district.drop(columns=[VARIABLE_ELIMINADA_DISTRICT]).copy()
df_ols_sin_district.to_csv(RUTA_SALIDA_SIN_DISTRICT, index=False)
df_train_sin_district = df_ols_sin_district[df_ols_sin_district["periodo"] < CORTE_TEMPORAL].copy()
df_test_sin_district = df_ols_sin_district[df_ols_sin_district["periodo"] >= CORTE_TEMPORAL].copy()
X_train_sin_district = df_train_sin_district.drop(columns=["price_per_sqm", "periodo"])
X_test_sin_district = df_test_sin_district.drop(columns=["price_per_sqm", "periodo"])
y_train_sin_district = df_train_sin_district["price_per_sqm"]
y_test_sin_district = df_test_sin_district["price_per_sqm"]
X_train_sin_district_sm = sm.add_constant(X_train_sin_district, has_constant="add")
X_test_sin_district_sm = sm.add_constant(X_test_sin_district, has_constant="add")
resultados_ols_sin_district = sm.OLS(y_train_sin_district, X_train_sin_district_sm).fit()
predicciones_train_sin_district = resultados_ols_sin_district.predict(X_train_sin_district_sm)
predicciones_test_sin_district = resultados_ols_sin_district.predict(X_test_sin_district_sm)
metricas_ols_sin_district = {
    **calcular_metricas_regresion(y_train_sin_district, predicciones_train_sin_district, "train"),
    **calcular_metricas_regresion(y_test_sin_district, predicciones_test_sin_district, "test"),
    "r2_ols": float(resultados_ols_sin_district.rsquared),
    "r2_ajustado_ols": float(resultados_ols_sin_district.rsquared_adj),
    "aic_ols": float(resultados_ols_sin_district.aic),
    "bic_ols": float(resultados_ols_sin_district.bic),
    "f_statistic_ols": float(resultados_ols_sin_district.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_sin_district.f_pvalue),
    "condition_number_ols": float(resultados_ols_sin_district.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_sin_district.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_sin_district.pvalues > 0.05).sum())
}
omnibus_sin_district, prob_omnibus_sin_district = omni_normtest(resultados_ols_sin_district.resid)
jarque_bera_sin_district, prob_jb_sin_district, skew_sin_district, kurtosis_sin_district = jarque_bera(resultados_ols_sin_district.resid)
metricas_ols_sin_district.update({
    "omnibus_ols": float(omnibus_sin_district),
    "prob_omnibus_ols": float(prob_omnibus_sin_district),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_sin_district.resid)),
    "jarque_bera_ols": float(jarque_bera_sin_district),
    "prob_jb_ols": float(prob_jb_sin_district),
    "skew_ols": float(skew_sin_district),
    "kurtosis_ols": float(kurtosis_sin_district)
})
coeficientes_ols_sin_district = pd.DataFrame({"variable": resultados_ols_sin_district.params.index, "coeficiente": resultados_ols_sin_district.params.to_numpy(), "p_value": resultados_ols_sin_district.pvalues.to_numpy(), "significativa_0_05": resultados_ols_sin_district.pvalues.to_numpy() <= 0.05})
residuos_test_sin_district = pd.DataFrame({"periodo": df_test_sin_district["periodo"].to_numpy(), "real": y_test_sin_district.to_numpy(), "prediccion": predicciones_test_sin_district.to_numpy(), "residuo": y_test_sin_district.to_numpy() - predicciones_test_sin_district.to_numpy()})
comparacion_ols_sin_district = pd.DataFrame([{"modelo": "OLS sin living_area ni lon", **metricas_ols_sin_lon}, {"modelo": "OLS sin living_area, lon ni district_Pokrovskoye-Streshnevo", **metricas_ols_sin_district}])
delta_metricas_sin_district = {f"delta_{metrica}": metricas_ols_sin_district[metrica] - metricas_ols_sin_lon[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_sin_district[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_sin_living_area_sin_lon_sin_district_pokrovskoye"):
    mlflow.set_tag("run_anterior_id", "d5feb1cdd6db4f2a884b26c4ecfe3fef")
    mlflow.log_params({"dataset": str(RUTA_SALIDA_SIN_DISTRICT), "dataset_origen": str(RUTA_SALIDA_SIN_LON), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_DISTRICT, "n_predictores": X_train_sin_district.shape[1], "filas_entrenamiento": len(df_train_sin_district), "filas_prueba": len(df_test_sin_district), "tipo_modelo": "statsmodels_OLS_sin_living_area_sin_lon_sin_district"})
    mlflow.log_metrics({**metricas_ols_sin_district, **delta_metricas_sin_district})
    mlflow.log_table(comparacion_ols_sin_district, artifact_file="comparacion/comparacion_ols_sin_living_area_sin_lon_sin_district.json")
    mlflow.log_table(coeficientes_ols_sin_district, artifact_file="modelo/coeficientes_ols_sin_living_area_sin_lon_sin_district.json")
    mlflow.log_table(residuos_test_sin_district, artifact_file="diagnostico/residuos_test_sin_living_area_sin_lon_sin_district.json")
    mlflow.log_text(resultados_ols_sin_district.summary().as_text(), "modelo/resumen_ols_sin_living_area_sin_lon_sin_district.txt")
print(f"Archivo sin living_area, lon ni district_Pokrovskoye-Streshnevo guardado en: {RUTA_SALIDA_SIN_DISTRICT}")
print("OLS sin la dummy de distrito registrado en MLflow para comparación")

,modelo,mae_test,rmse_test,r2_test,mape_test
0,OLS sin living_area ni lon,37084.667719,45131.738718,0.859834,23.172933
1,"OLS sin living_area, lon ni district_Pokrovsko...",37084.746277,45131.606415,0.859834,23.172829

🏃 View run ols_temporal_sin_living_area_sin_lon_sin_district_pokrovskoye at: http://127.0.0.1:5000/#/experiments/4/runs/d6beaaeb974c40009471707897db75e7
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Archivo sin living_area, lon ni district_Pokrovskoye-Streshnevo guardado en: data_sets_transformados\secondary_market_modelado_one_hot_pvalue_090_sin_living_area_sin_lon_sin_district_pokrovskoye_streshnevo.csv
OLS sin la dummy de distrito registrado en MLflow para comparación

### Interpretación

La eliminación de la dummy de distrito se evalúa comparando las métricas temporales y el número de condición contra el modelo sin `living_area` ni `lon`.

## 12. OLS con eliminación agrupada de dummies de `metro_station`

Partimos del dataset de la sección 11 y eliminamos simultáneamente `metro_station_Borovitskaya`, `metro_station_Kozhukhovskaya` y `metro_station_Sretensky Bulvar`. El nuevo dataset usa el número de sección en su nombre.

In [12]:
VARIABLES_ELIMINADAS_SECCION_12 = [
    "metro_station_Borovitskaya",
    "metro_station_Kozhukhovskaya",
    "metro_station_Sretensky Bulvar"
]
RUTA_SALIDA_SECCION_12 = Path("data_sets_transformados/secondary_market_modelado_seccion_12.csv")
df_ols_seccion_12_origen = pd.read_csv(RUTA_SALIDA_SIN_DISTRICT)
columnas_faltantes_seccion_12 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_12 if columna not in df_ols_seccion_12_origen.columns]
if columnas_faltantes_seccion_12:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_12}")
df_ols_seccion_12 = df_ols_seccion_12_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_12).copy()
df_ols_seccion_12.to_csv(RUTA_SALIDA_SECCION_12, index=False)
df_train_seccion_12 = df_ols_seccion_12[df_ols_seccion_12["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_12 = df_ols_seccion_12[df_ols_seccion_12["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_12 = df_train_seccion_12.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_12 = df_test_seccion_12.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_12 = df_train_seccion_12["price_per_sqm"]
y_test_seccion_12 = df_test_seccion_12["price_per_sqm"]
X_train_seccion_12_sm = sm.add_constant(X_train_seccion_12, has_constant="add")
X_test_seccion_12_sm = sm.add_constant(X_test_seccion_12, has_constant="add")
resultados_ols_seccion_12 = sm.OLS(y_train_seccion_12, X_train_seccion_12_sm).fit()
predicciones_train_seccion_12 = resultados_ols_seccion_12.predict(X_train_seccion_12_sm)
predicciones_test_seccion_12 = resultados_ols_seccion_12.predict(X_test_seccion_12_sm)
metricas_ols_seccion_12 = {
    **calcular_metricas_regresion(y_train_seccion_12, predicciones_train_seccion_12, "train"),
    **calcular_metricas_regresion(y_test_seccion_12, predicciones_test_seccion_12, "test"),
    "r2_ols": float(resultados_ols_seccion_12.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_12.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_12.aic),
    "bic_ols": float(resultados_ols_seccion_12.bic),
    "f_statistic_ols": float(resultados_ols_seccion_12.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_12.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_12.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_12.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_12.pvalues > 0.05).sum())
}
omnibus_seccion_12, prob_omnibus_seccion_12 = omni_normtest(resultados_ols_seccion_12.resid)
jarque_bera_seccion_12, prob_jb_seccion_12, skew_seccion_12, kurtosis_seccion_12 = jarque_bera(resultados_ols_seccion_12.resid)
metricas_ols_seccion_12.update({
    "omnibus_ols": float(omnibus_seccion_12),
    "prob_omnibus_ols": float(prob_omnibus_seccion_12),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_12.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_12),
    "prob_jb_ols": float(prob_jb_seccion_12),
    "skew_ols": float(skew_seccion_12),
    "kurtosis_ols": float(kurtosis_seccion_12)
})
coeficientes_ols_seccion_12 = pd.DataFrame({"variable": resultados_ols_seccion_12.params.index, "coeficiente": resultados_ols_seccion_12.params.to_numpy(), "p_value": resultados_ols_seccion_12.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_12.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_12 = pd.DataFrame({"periodo": df_test_seccion_12["periodo"].to_numpy(), "real": y_test_seccion_12.to_numpy(), "prediccion": predicciones_test_seccion_12.to_numpy(), "residuo": y_test_seccion_12.to_numpy() - predicciones_test_seccion_12.to_numpy()})
comparacion_ols_seccion_12 = pd.DataFrame([{"modelo": "OLS sección 11", **metricas_ols_sin_district}, {"modelo": "OLS sección 12", **metricas_ols_seccion_12}])
delta_metricas_seccion_12 = {f"delta_{metrica}": metricas_ols_seccion_12[metrica] - metricas_ols_sin_district[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_12[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_12"):
    mlflow.set_tag("run_anterior_id", "6b350dfdd37548998fbf34db587091b2")
    mlflow.log_params({"seccion": 12, "dataset": str(RUTA_SALIDA_SECCION_12), "dataset_origen": str(RUTA_SALIDA_SIN_DISTRICT), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_12), "n_predictores": X_train_seccion_12.shape[1], "filas_entrenamiento": len(df_train_seccion_12), "filas_prueba": len(df_test_seccion_12), "tipo_modelo": "statsmodels_OLS_seccion_12"})
    mlflow.log_metrics({**metricas_ols_seccion_12, **delta_metricas_seccion_12})
    mlflow.log_table(comparacion_ols_seccion_12, artifact_file="comparacion/comparacion_ols_seccion_12.json")
    mlflow.log_table(coeficientes_ols_seccion_12, artifact_file="modelo/coeficientes_ols_seccion_12.json")
    mlflow.log_table(residuos_test_seccion_12, artifact_file="diagnostico/residuos_test_seccion_12.json")
    mlflow.log_text(resultados_ols_seccion_12.summary().as_text(), "modelo/resumen_ols_seccion_12.txt")
print(f"Dataset de la sección 12 guardado en: {RUTA_SALIDA_SECCION_12}")
print("OLS de la sección 12 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 11  37084.746277  45131.606415  0.859834  23.172829
1  OLS sección 12  37086.131497  45133.296465  0.859824  23.173331

🏃 View run ols_temporal_seccion_12 at: http://127.0.0.1:5000/#/experiments/4/runs/24d38fdbde904f5d9cf31170e5595980
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 12 guardado en: data_sets_transformados\secondary_market_modelado_seccion_12.csv
OLS de la sección 12 registrado en MLflow para comparación

### Interpretación

La eliminación agrupada se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 11.

## 13. OLS sin `metro_station_Borovitskaya`

Partimos del dataset de la sección 11 y eliminamos únicamente `metro_station_Borovitskaya`. El nuevo dataset usa el número de sección en su nombre.

In [13]:
VARIABLE_ELIMINADA_SECCION_13 = "metro_station_Borovitskaya"
RUTA_SALIDA_SECCION_13 = Path("data_sets_transformados/secondary_market_modelado_seccion_13.csv")
df_ols_seccion_13_origen = pd.read_csv(RUTA_SALIDA_SIN_DISTRICT)
if VARIABLE_ELIMINADA_SECCION_13 not in df_ols_seccion_13_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_13!r} no está disponible")
df_ols_seccion_13 = df_ols_seccion_13_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_13]).copy()
df_ols_seccion_13.to_csv(RUTA_SALIDA_SECCION_13, index=False)
df_train_seccion_13 = df_ols_seccion_13[df_ols_seccion_13["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_13 = df_ols_seccion_13[df_ols_seccion_13["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_13 = df_train_seccion_13.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_13 = df_test_seccion_13.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_13 = df_train_seccion_13["price_per_sqm"]
y_test_seccion_13 = df_test_seccion_13["price_per_sqm"]
X_train_seccion_13_sm = sm.add_constant(X_train_seccion_13, has_constant="add")
X_test_seccion_13_sm = sm.add_constant(X_test_seccion_13, has_constant="add")
resultados_ols_seccion_13 = sm.OLS(y_train_seccion_13, X_train_seccion_13_sm).fit()
predicciones_train_seccion_13 = resultados_ols_seccion_13.predict(X_train_seccion_13_sm)
predicciones_test_seccion_13 = resultados_ols_seccion_13.predict(X_test_seccion_13_sm)
metricas_ols_seccion_13 = {
    **calcular_metricas_regresion(y_train_seccion_13, predicciones_train_seccion_13, "train"),
    **calcular_metricas_regresion(y_test_seccion_13, predicciones_test_seccion_13, "test"),
    "r2_ols": float(resultados_ols_seccion_13.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_13.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_13.aic),
    "bic_ols": float(resultados_ols_seccion_13.bic),
    "f_statistic_ols": float(resultados_ols_seccion_13.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_13.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_13.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_13.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_13.pvalues > 0.05).sum())
}
omnibus_seccion_13, prob_omnibus_seccion_13 = omni_normtest(resultados_ols_seccion_13.resid)
jarque_bera_seccion_13, prob_jb_seccion_13, skew_seccion_13, kurtosis_seccion_13 = jarque_bera(resultados_ols_seccion_13.resid)
metricas_ols_seccion_13.update({
    "omnibus_ols": float(omnibus_seccion_13),
    "prob_omnibus_ols": float(prob_omnibus_seccion_13),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_13.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_13),
    "prob_jb_ols": float(prob_jb_seccion_13),
    "skew_ols": float(skew_seccion_13),
    "kurtosis_ols": float(kurtosis_seccion_13)
})
coeficientes_ols_seccion_13 = pd.DataFrame({"variable": resultados_ols_seccion_13.params.index, "coeficiente": resultados_ols_seccion_13.params.to_numpy(), "p_value": resultados_ols_seccion_13.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_13.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_13 = pd.DataFrame({"periodo": df_test_seccion_13["periodo"].to_numpy(), "real": y_test_seccion_13.to_numpy(), "prediccion": predicciones_test_seccion_13.to_numpy(), "residuo": y_test_seccion_13.to_numpy() - predicciones_test_seccion_13.to_numpy()})
comparacion_ols_seccion_13 = pd.DataFrame([{"modelo": "OLS sección 11", **metricas_ols_sin_district}, {"modelo": "OLS sección 13", **metricas_ols_seccion_13}])
delta_metricas_seccion_13 = {f"delta_{metrica}": metricas_ols_seccion_13[metrica] - metricas_ols_sin_district[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_13[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_13"):
    mlflow.set_tag("run_anterior_id", "6b350dfdd37548998fbf34db587091b2")
    mlflow.log_params({"seccion": 13, "dataset": str(RUTA_SALIDA_SECCION_13), "dataset_origen": str(RUTA_SALIDA_SIN_DISTRICT), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_13, "n_predictores": X_train_seccion_13.shape[1], "filas_entrenamiento": len(df_train_seccion_13), "filas_prueba": len(df_test_seccion_13), "tipo_modelo": "statsmodels_OLS_seccion_13"})
    mlflow.log_metrics({**metricas_ols_seccion_13, **delta_metricas_seccion_13})
    mlflow.log_table(comparacion_ols_seccion_13, artifact_file="comparacion/comparacion_ols_seccion_13.json")
    mlflow.log_table(coeficientes_ols_seccion_13, artifact_file="modelo/coeficientes_ols_seccion_13.json")
    mlflow.log_table(residuos_test_seccion_13, artifact_file="diagnostico/residuos_test_seccion_13.json")
    mlflow.log_text(resultados_ols_seccion_13.summary().as_text(), "modelo/resumen_ols_seccion_13.txt")
print(f"Dataset de la sección 13 guardado en: {RUTA_SALIDA_SECCION_13}")
print("OLS de la sección 13 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 11  37084.746277  45131.606415  0.859834  23.172829
1  OLS sección 13  37084.817321  45132.177475  0.859831  23.172807

🏃 View run ols_temporal_seccion_13 at: http://127.0.0.1:5000/#/experiments/4/runs/51649632e4ed4b24a9c51f4911d6fc50
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 13 guardado en: data_sets_transformados\secondary_market_modelado_seccion_13.csv
OLS de la sección 13 registrado en MLflow para comparación

### Interpretación

La eliminación individual se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 11.

## 14. OLS sin `metro_station_Sretensky Bulvar`

Partimos del dataset de la sección 11 y eliminamos únicamente `metro_station_Sretensky Bulvar`. El nuevo dataset usa el número de sección en su nombre.

In [14]:
VARIABLE_ELIMINADA_SECCION_14 = "metro_station_Sretensky Bulvar"
RUTA_SALIDA_SECCION_14 = Path("data_sets_transformados/secondary_market_modelado_seccion_14.csv")
df_ols_seccion_14_origen = pd.read_csv(RUTA_SALIDA_SIN_DISTRICT)
if VARIABLE_ELIMINADA_SECCION_14 not in df_ols_seccion_14_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_14!r} no está disponible")
df_ols_seccion_14 = df_ols_seccion_14_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_14]).copy()
df_ols_seccion_14.to_csv(RUTA_SALIDA_SECCION_14, index=False)
df_train_seccion_14 = df_ols_seccion_14[df_ols_seccion_14["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_14 = df_ols_seccion_14[df_ols_seccion_14["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_14 = df_train_seccion_14.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_14 = df_test_seccion_14.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_14 = df_train_seccion_14["price_per_sqm"]
y_test_seccion_14 = df_test_seccion_14["price_per_sqm"]
X_train_seccion_14_sm = sm.add_constant(X_train_seccion_14, has_constant="add")
X_test_seccion_14_sm = sm.add_constant(X_test_seccion_14, has_constant="add")
resultados_ols_seccion_14 = sm.OLS(y_train_seccion_14, X_train_seccion_14_sm).fit()
predicciones_train_seccion_14 = resultados_ols_seccion_14.predict(X_train_seccion_14_sm)
predicciones_test_seccion_14 = resultados_ols_seccion_14.predict(X_test_seccion_14_sm)
metricas_ols_seccion_14 = {
    **calcular_metricas_regresion(y_train_seccion_14, predicciones_train_seccion_14, "train"),
    **calcular_metricas_regresion(y_test_seccion_14, predicciones_test_seccion_14, "test"),
    "r2_ols": float(resultados_ols_seccion_14.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_14.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_14.aic),
    "bic_ols": float(resultados_ols_seccion_14.bic),
    "f_statistic_ols": float(resultados_ols_seccion_14.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_14.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_14.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_14.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_14.pvalues > 0.05).sum())
}
omnibus_seccion_14, prob_omnibus_seccion_14 = omni_normtest(resultados_ols_seccion_14.resid)
jarque_bera_seccion_14, prob_jb_seccion_14, skew_seccion_14, kurtosis_seccion_14 = jarque_bera(resultados_ols_seccion_14.resid)
metricas_ols_seccion_14.update({
    "omnibus_ols": float(omnibus_seccion_14),
    "prob_omnibus_ols": float(prob_omnibus_seccion_14),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_14.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_14),
    "prob_jb_ols": float(prob_jb_seccion_14),
    "skew_ols": float(skew_seccion_14),
    "kurtosis_ols": float(kurtosis_seccion_14)
})
coeficientes_ols_seccion_14 = pd.DataFrame({"variable": resultados_ols_seccion_14.params.index, "coeficiente": resultados_ols_seccion_14.params.to_numpy(), "p_value": resultados_ols_seccion_14.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_14.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_14 = pd.DataFrame({"periodo": df_test_seccion_14["periodo"].to_numpy(), "real": y_test_seccion_14.to_numpy(), "prediccion": predicciones_test_seccion_14.to_numpy(), "residuo": y_test_seccion_14.to_numpy() - predicciones_test_seccion_14.to_numpy()})
comparacion_ols_seccion_14 = pd.DataFrame([{"modelo": "OLS sección 11", **metricas_ols_sin_district}, {"modelo": "OLS sección 14", **metricas_ols_seccion_14}])
delta_metricas_seccion_14 = {f"delta_{metrica}": metricas_ols_seccion_14[metrica] - metricas_ols_sin_district[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_14[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_14"):
    mlflow.set_tag("run_anterior_id", "6b350dfdd37548998fbf34db587091b2")
    mlflow.log_params({"seccion": 14, "dataset": str(RUTA_SALIDA_SECCION_14), "dataset_origen": str(RUTA_SALIDA_SIN_DISTRICT), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_14, "n_predictores": X_train_seccion_14.shape[1], "filas_entrenamiento": len(df_train_seccion_14), "filas_prueba": len(df_test_seccion_14), "tipo_modelo": "statsmodels_OLS_seccion_14"})
    mlflow.log_metrics({**metricas_ols_seccion_14, **delta_metricas_seccion_14})
    mlflow.log_table(comparacion_ols_seccion_14, artifact_file="comparacion/comparacion_ols_seccion_14.json")
    mlflow.log_table(coeficientes_ols_seccion_14, artifact_file="modelo/coeficientes_ols_seccion_14.json")
    mlflow.log_table(residuos_test_seccion_14, artifact_file="diagnostico/residuos_test_seccion_14.json")
    mlflow.log_text(resultados_ols_seccion_14.summary().as_text(), "modelo/resumen_ols_seccion_14.txt")
print(f"Dataset de la sección 14 guardado en: {RUTA_SALIDA_SECCION_14}")
print("OLS de la sección 14 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 11  37084.746277  45131.606415  0.859834  23.172829
1  OLS sección 14  37083.704336  45130.953077  0.859838  23.171620

🏃 View run ols_temporal_seccion_14 at: http://127.0.0.1:5000/#/experiments/4/runs/fbfc9ab040a340be8acbedebe7832d74
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 14 guardado en: data_sets_transformados\secondary_market_modelado_seccion_14.csv
OLS de la sección 14 registrado en MLflow para comparación

### Interpretación

La eliminación individual se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 11.

## 15. OLS sin `metro_station_Novoslobodskaya`

Partimos del dataset de la sección 14 y eliminamos `metro_station_Novoslobodskaya` como segundo paso acumulativo. El nuevo dataset usa el número de sección en su nombre.

In [15]:
VARIABLE_ELIMINADA_SECCION_15 = "metro_station_Novoslobodskaya"
RUTA_SALIDA_SECCION_15 = Path("data_sets_transformados/secondary_market_modelado_seccion_15.csv")
RUTA_ORIGEN_SECCION_15 = Path("data_sets_transformados/secondary_market_modelado_seccion_14.csv")
df_ols_seccion_15_origen = pd.read_csv(RUTA_ORIGEN_SECCION_15)
if VARIABLE_ELIMINADA_SECCION_15 not in df_ols_seccion_15_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_15!r} no está disponible")
df_ols_seccion_15 = df_ols_seccion_15_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_15]).copy()
df_ols_seccion_15.to_csv(RUTA_SALIDA_SECCION_15, index=False)
df_train_seccion_15 = df_ols_seccion_15[df_ols_seccion_15["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_15 = df_ols_seccion_15[df_ols_seccion_15["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_15 = df_train_seccion_15.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_15 = df_test_seccion_15.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_15 = df_train_seccion_15["price_per_sqm"]
y_test_seccion_15 = df_test_seccion_15["price_per_sqm"]
X_train_seccion_15_sm = sm.add_constant(X_train_seccion_15, has_constant="add")
X_test_seccion_15_sm = sm.add_constant(X_test_seccion_15, has_constant="add")
resultados_ols_seccion_15 = sm.OLS(y_train_seccion_15, X_train_seccion_15_sm).fit()
predicciones_train_seccion_15 = resultados_ols_seccion_15.predict(X_train_seccion_15_sm)
predicciones_test_seccion_15 = resultados_ols_seccion_15.predict(X_test_seccion_15_sm)
metricas_ols_seccion_15 = {
    **calcular_metricas_regresion(y_train_seccion_15, predicciones_train_seccion_15, "train"),
    **calcular_metricas_regresion(y_test_seccion_15, predicciones_test_seccion_15, "test"),
    "r2_ols": float(resultados_ols_seccion_15.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_15.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_15.aic),
    "bic_ols": float(resultados_ols_seccion_15.bic),
    "f_statistic_ols": float(resultados_ols_seccion_15.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_15.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_15.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_15.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_15.pvalues > 0.05).sum())
}
omnibus_seccion_15, prob_omnibus_seccion_15 = omni_normtest(resultados_ols_seccion_15.resid)
jarque_bera_seccion_15, prob_jb_seccion_15, skew_seccion_15, kurtosis_seccion_15 = jarque_bera(resultados_ols_seccion_15.resid)
metricas_ols_seccion_15.update({
    "omnibus_ols": float(omnibus_seccion_15),
    "prob_omnibus_ols": float(prob_omnibus_seccion_15),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_15.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_15),
    "prob_jb_ols": float(prob_jb_seccion_15),
    "skew_ols": float(skew_seccion_15),
    "kurtosis_ols": float(kurtosis_seccion_15)
})
coeficientes_ols_seccion_15 = pd.DataFrame({"variable": resultados_ols_seccion_15.params.index, "coeficiente": resultados_ols_seccion_15.params.to_numpy(), "p_value": resultados_ols_seccion_15.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_15.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_15 = pd.DataFrame({"periodo": df_test_seccion_15["periodo"].to_numpy(), "real": y_test_seccion_15.to_numpy(), "prediccion": predicciones_test_seccion_15.to_numpy(), "residuo": y_test_seccion_15.to_numpy() - predicciones_test_seccion_15.to_numpy()})
comparacion_ols_seccion_15 = pd.DataFrame([{"modelo": "OLS sección 14", **metricas_ols_seccion_14}, {"modelo": "OLS sección 15", **metricas_ols_seccion_15}])
delta_metricas_seccion_15 = {f"delta_{metrica}": metricas_ols_seccion_15[metrica] - metricas_ols_seccion_14[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_15[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_15"):
    mlflow.set_tag("run_anterior_id", "5a6927ef54e64c77aa3a01b8b32c8713")
    mlflow.log_params({"seccion": 15, "dataset": str(RUTA_SALIDA_SECCION_15), "dataset_origen": str(RUTA_ORIGEN_SECCION_15), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_15, "n_predictores": X_train_seccion_15.shape[1], "filas_entrenamiento": len(df_train_seccion_15), "filas_prueba": len(df_test_seccion_15), "tipo_modelo": "statsmodels_OLS_seccion_15_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_15, **delta_metricas_seccion_15})
    mlflow.log_table(comparacion_ols_seccion_15, artifact_file="comparacion/comparacion_ols_seccion_15.json")
    mlflow.log_table(coeficientes_ols_seccion_15, artifact_file="modelo/coeficientes_ols_seccion_15.json")
    mlflow.log_table(residuos_test_seccion_15, artifact_file="diagnostico/residuos_test_seccion_15.json")
    mlflow.log_text(resultados_ols_seccion_15.summary().as_text(), "modelo/resumen_ols_seccion_15.txt")
print(f"Dataset de la sección 15 guardado en: {RUTA_SALIDA_SECCION_15}")
print("OLS de la sección 15 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 14  37083.704336  45130.953077  0.859838  23.171620
1  OLS sección 15  37082.913534  45130.296893  0.859843  23.171044

🏃 View run ols_temporal_seccion_15 at: http://127.0.0.1:5000/#/experiments/4/runs/f362b35b2b4a4c46882d43ec9e730a95
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 15 guardado en: data_sets_transformados\secondary_market_modelado_seccion_15.csv
OLS de la sección 15 registrado en MLflow para comparación

### Interpretación

La eliminación individual se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 11.

## 16. OLS sin `metro_station_Borovitskaya`

Partimos del dataset acumulativo de la sección 15 y eliminamos `metro_station_Borovitskaya`. El nuevo dataset usa el número de sección en su nombre.

In [16]:
VARIABLE_ELIMINADA_SECCION_16 = "metro_station_Borovitskaya"
RUTA_ORIGEN_SECCION_16 = Path("data_sets_transformados/secondary_market_modelado_seccion_15.csv")
RUTA_SALIDA_SECCION_16 = Path("data_sets_transformados/secondary_market_modelado_seccion_16.csv")
df_ols_seccion_16_origen = pd.read_csv(RUTA_ORIGEN_SECCION_16)
if VARIABLE_ELIMINADA_SECCION_16 not in df_ols_seccion_16_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_16!r} no está disponible")
df_ols_seccion_16 = df_ols_seccion_16_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_16]).copy()
df_ols_seccion_16.to_csv(RUTA_SALIDA_SECCION_16, index=False)
df_train_seccion_16 = df_ols_seccion_16[df_ols_seccion_16["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_16 = df_ols_seccion_16[df_ols_seccion_16["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_16 = df_train_seccion_16.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_16 = df_test_seccion_16.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_16 = df_train_seccion_16["price_per_sqm"]
y_test_seccion_16 = df_test_seccion_16["price_per_sqm"]
X_train_seccion_16_sm = sm.add_constant(X_train_seccion_16, has_constant="add")
X_test_seccion_16_sm = sm.add_constant(X_test_seccion_16, has_constant="add")
resultados_ols_seccion_16 = sm.OLS(y_train_seccion_16, X_train_seccion_16_sm).fit()
predicciones_train_seccion_16 = resultados_ols_seccion_16.predict(X_train_seccion_16_sm)
predicciones_test_seccion_16 = resultados_ols_seccion_16.predict(X_test_seccion_16_sm)
metricas_ols_seccion_16 = {
    **calcular_metricas_regresion(y_train_seccion_16, predicciones_train_seccion_16, "train"),
    **calcular_metricas_regresion(y_test_seccion_16, predicciones_test_seccion_16, "test"),
    "r2_ols": float(resultados_ols_seccion_16.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_16.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_16.aic),
    "bic_ols": float(resultados_ols_seccion_16.bic),
    "f_statistic_ols": float(resultados_ols_seccion_16.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_16.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_16.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_16.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_16.pvalues > 0.05).sum())
}
omnibus_seccion_16, prob_omnibus_seccion_16 = omni_normtest(resultados_ols_seccion_16.resid)
jarque_bera_seccion_16, prob_jb_seccion_16, skew_seccion_16, kurtosis_seccion_16 = jarque_bera(resultados_ols_seccion_16.resid)
metricas_ols_seccion_16.update({
    "omnibus_ols": float(omnibus_seccion_16),
    "prob_omnibus_ols": float(prob_omnibus_seccion_16),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_16.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_16),
    "prob_jb_ols": float(prob_jb_seccion_16),
    "skew_ols": float(skew_seccion_16),
    "kurtosis_ols": float(kurtosis_seccion_16)
})
coeficientes_ols_seccion_16 = pd.DataFrame({"variable": resultados_ols_seccion_16.params.index, "coeficiente": resultados_ols_seccion_16.params.to_numpy(), "p_value": resultados_ols_seccion_16.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_16.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_16 = pd.DataFrame({"periodo": df_test_seccion_16["periodo"].to_numpy(), "real": y_test_seccion_16.to_numpy(), "prediccion": predicciones_test_seccion_16.to_numpy(), "residuo": y_test_seccion_16.to_numpy() - predicciones_test_seccion_16.to_numpy()})
comparacion_ols_seccion_16 = pd.DataFrame([{"modelo": "OLS sección 15", **metricas_ols_seccion_15}, {"modelo": "OLS sección 16", **metricas_ols_seccion_16}])
delta_metricas_seccion_16 = {f"delta_{metrica}": metricas_ols_seccion_16[metrica] - metricas_ols_seccion_15[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_16[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_16"):
    mlflow.set_tag("run_anterior_id", "7841515ae07b4790843dadec44ce01a2")
    mlflow.log_params({"seccion": 16, "dataset": str(RUTA_SALIDA_SECCION_16), "dataset_origen": str(RUTA_ORIGEN_SECCION_16), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_16, "n_predictores": X_train_seccion_16.shape[1], "filas_entrenamiento": len(df_train_seccion_16), "filas_prueba": len(df_test_seccion_16), "tipo_modelo": "statsmodels_OLS_seccion_16_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_16, **delta_metricas_seccion_16})
    mlflow.log_table(comparacion_ols_seccion_16, artifact_file="comparacion/comparacion_ols_seccion_16.json")
    mlflow.log_table(coeficientes_ols_seccion_16, artifact_file="modelo/coeficientes_ols_seccion_16.json")
    mlflow.log_table(residuos_test_seccion_16, artifact_file="diagnostico/residuos_test_seccion_16.json")
    mlflow.log_text(resultados_ols_seccion_16.summary().as_text(), "modelo/resumen_ols_seccion_16.txt")
print(f"Dataset de la sección 16 guardado en: {RUTA_SALIDA_SECCION_16}")
print("OLS de la sección 16 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 15  37082.913534  45130.296893  0.859843  23.171044
1  OLS sección 16  37083.088468  45130.828457  0.859839  23.171151

🏃 View run ols_temporal_seccion_16 at: http://127.0.0.1:5000/#/experiments/4/runs/3c7f44cc30654985ba27c02a0ec9da7e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 16 guardado en: data_sets_transformados\secondary_market_modelado_seccion_16.csv
OLS de la sección 16 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 15.

## 17. OLS sin `metro_station_Belorusskaya`

Partimos del dataset acumulativo de la sección 16 y eliminamos `metro_station_Belorusskaya`. El nuevo dataset usa el número de sección en su nombre.

In [17]:
VARIABLE_ELIMINADA_SECCION_17 = "metro_station_Belorusskaya"
RUTA_ORIGEN_SECCION_17 = Path("data_sets_transformados/secondary_market_modelado_seccion_16.csv")
RUTA_SALIDA_SECCION_17 = Path("data_sets_transformados/secondary_market_modelado_seccion_17.csv")
df_ols_seccion_17_origen = pd.read_csv(RUTA_ORIGEN_SECCION_17)
if VARIABLE_ELIMINADA_SECCION_17 not in df_ols_seccion_17_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_17!r} no está disponible")
df_ols_seccion_17 = df_ols_seccion_17_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_17]).copy()
df_ols_seccion_17.to_csv(RUTA_SALIDA_SECCION_17, index=False)
df_train_seccion_17 = df_ols_seccion_17[df_ols_seccion_17["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_17 = df_ols_seccion_17[df_ols_seccion_17["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_17 = df_train_seccion_17.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_17 = df_test_seccion_17.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_17 = df_train_seccion_17["price_per_sqm"]
y_test_seccion_17 = df_test_seccion_17["price_per_sqm"]
X_train_seccion_17_sm = sm.add_constant(X_train_seccion_17, has_constant="add")
X_test_seccion_17_sm = sm.add_constant(X_test_seccion_17, has_constant="add")
resultados_ols_seccion_17 = sm.OLS(y_train_seccion_17, X_train_seccion_17_sm).fit()
predicciones_train_seccion_17 = resultados_ols_seccion_17.predict(X_train_seccion_17_sm)
predicciones_test_seccion_17 = resultados_ols_seccion_17.predict(X_test_seccion_17_sm)
metricas_ols_seccion_17 = {
    **calcular_metricas_regresion(y_train_seccion_17, predicciones_train_seccion_17, "train"),
    **calcular_metricas_regresion(y_test_seccion_17, predicciones_test_seccion_17, "test"),
    "r2_ols": float(resultados_ols_seccion_17.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_17.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_17.aic),
    "bic_ols": float(resultados_ols_seccion_17.bic),
    "f_statistic_ols": float(resultados_ols_seccion_17.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_17.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_17.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_17.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_17.pvalues > 0.05).sum())
}
omnibus_seccion_17, prob_omnibus_seccion_17 = omni_normtest(resultados_ols_seccion_17.resid)
jarque_bera_seccion_17, prob_jb_seccion_17, skew_seccion_17, kurtosis_seccion_17 = jarque_bera(resultados_ols_seccion_17.resid)
metricas_ols_seccion_17.update({
    "omnibus_ols": float(omnibus_seccion_17),
    "prob_omnibus_ols": float(prob_omnibus_seccion_17),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_17.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_17),
    "prob_jb_ols": float(prob_jb_seccion_17),
    "skew_ols": float(skew_seccion_17),
    "kurtosis_ols": float(kurtosis_seccion_17)
})
coeficientes_ols_seccion_17 = pd.DataFrame({"variable": resultados_ols_seccion_17.params.index, "coeficiente": resultados_ols_seccion_17.params.to_numpy(), "p_value": resultados_ols_seccion_17.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_17.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_17 = pd.DataFrame({"periodo": df_test_seccion_17["periodo"].to_numpy(), "real": y_test_seccion_17.to_numpy(), "prediccion": predicciones_test_seccion_17.to_numpy(), "residuo": y_test_seccion_17.to_numpy() - predicciones_test_seccion_17.to_numpy()})
comparacion_ols_seccion_17 = pd.DataFrame([{"modelo": "OLS sección 16", **metricas_ols_seccion_16}, {"modelo": "OLS sección 17", **metricas_ols_seccion_17}])
delta_metricas_seccion_17 = {f"delta_{metrica}": metricas_ols_seccion_17[metrica] - metricas_ols_seccion_16[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_17[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_17"):
    mlflow.set_tag("run_anterior_id", "386e759d672e4f07a2bce9f7800564a8")
    mlflow.log_params({"seccion": 17, "dataset": str(RUTA_SALIDA_SECCION_17), "dataset_origen": str(RUTA_ORIGEN_SECCION_17), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_17, "n_predictores": X_train_seccion_17.shape[1], "filas_entrenamiento": len(df_train_seccion_17), "filas_prueba": len(df_test_seccion_17), "tipo_modelo": "statsmodels_OLS_seccion_17_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_17, **delta_metricas_seccion_17})
    mlflow.log_table(comparacion_ols_seccion_17, artifact_file="comparacion/comparacion_ols_seccion_17.json")
    mlflow.log_table(coeficientes_ols_seccion_17, artifact_file="modelo/coeficientes_ols_seccion_17.json")
    mlflow.log_table(residuos_test_seccion_17, artifact_file="diagnostico/residuos_test_seccion_17.json")
    mlflow.log_text(resultados_ols_seccion_17.summary().as_text(), "modelo/resumen_ols_seccion_17.txt")
print(f"Dataset de la sección 17 guardado en: {RUTA_SALIDA_SECCION_17}")
print("OLS de la sección 17 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 16  37083.088468  45130.828457  0.859839  23.171151
1  OLS sección 17  37081.504127  45129.477642  0.859848  23.169997

🏃 View run ols_temporal_seccion_17 at: http://127.0.0.1:5000/#/experiments/4/runs/5989b6d2ab134941a73d3abb1e3f30b1
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 17 guardado en: data_sets_transformados\secondary_market_modelado_seccion_17.csv
OLS de la sección 17 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 16.

## 18. OLS sin `metro_station_Sevastopolskaya`

Partimos del dataset acumulativo de la sección 17 y eliminamos `metro_station_Sevastopolskaya`. El nuevo dataset usa el número de sección en su nombre.

In [18]:
VARIABLE_ELIMINADA_SECCION_18 = "metro_station_Sevastopolskaya"
RUTA_ORIGEN_SECCION_18 = Path("data_sets_transformados/secondary_market_modelado_seccion_17.csv")
RUTA_SALIDA_SECCION_18 = Path("data_sets_transformados/secondary_market_modelado_seccion_18.csv")
df_ols_seccion_18_origen = pd.read_csv(RUTA_ORIGEN_SECCION_18)
if VARIABLE_ELIMINADA_SECCION_18 not in df_ols_seccion_18_origen.columns:
    raise KeyError(f"La columna {VARIABLE_ELIMINADA_SECCION_18!r} no está disponible")
df_ols_seccion_18 = df_ols_seccion_18_origen.drop(columns=[VARIABLE_ELIMINADA_SECCION_18]).copy()
df_ols_seccion_18.to_csv(RUTA_SALIDA_SECCION_18, index=False)
df_train_seccion_18 = df_ols_seccion_18[df_ols_seccion_18["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_18 = df_ols_seccion_18[df_ols_seccion_18["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_18 = df_train_seccion_18.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_18 = df_test_seccion_18.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_18 = df_train_seccion_18["price_per_sqm"]
y_test_seccion_18 = df_test_seccion_18["price_per_sqm"]
X_train_seccion_18_sm = sm.add_constant(X_train_seccion_18, has_constant="add")
X_test_seccion_18_sm = sm.add_constant(X_test_seccion_18, has_constant="add")
resultados_ols_seccion_18 = sm.OLS(y_train_seccion_18, X_train_seccion_18_sm).fit()
predicciones_train_seccion_18 = resultados_ols_seccion_18.predict(X_train_seccion_18_sm)
predicciones_test_seccion_18 = resultados_ols_seccion_18.predict(X_test_seccion_18_sm)
metricas_ols_seccion_18 = {
    **calcular_metricas_regresion(y_train_seccion_18, predicciones_train_seccion_18, "train"),
    **calcular_metricas_regresion(y_test_seccion_18, predicciones_test_seccion_18, "test"),
    "r2_ols": float(resultados_ols_seccion_18.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_18.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_18.aic),
    "bic_ols": float(resultados_ols_seccion_18.bic),
    "f_statistic_ols": float(resultados_ols_seccion_18.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_18.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_18.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_18.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_18.pvalues > 0.05).sum())
}
omnibus_seccion_18, prob_omnibus_seccion_18 = omni_normtest(resultados_ols_seccion_18.resid)
jarque_bera_seccion_18, prob_jb_seccion_18, skew_seccion_18, kurtosis_seccion_18 = jarque_bera(resultados_ols_seccion_18.resid)
metricas_ols_seccion_18.update({
    "omnibus_ols": float(omnibus_seccion_18),
    "prob_omnibus_ols": float(prob_omnibus_seccion_18),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_18.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_18),
    "prob_jb_ols": float(prob_jb_seccion_18),
    "skew_ols": float(skew_seccion_18),
    "kurtosis_ols": float(kurtosis_seccion_18)
})
coeficientes_ols_seccion_18 = pd.DataFrame({"variable": resultados_ols_seccion_18.params.index, "coeficiente": resultados_ols_seccion_18.params.to_numpy(), "p_value": resultados_ols_seccion_18.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_18.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_18 = pd.DataFrame({"periodo": df_test_seccion_18["periodo"].to_numpy(), "real": y_test_seccion_18.to_numpy(), "prediccion": predicciones_test_seccion_18.to_numpy(), "residuo": y_test_seccion_18.to_numpy() - predicciones_test_seccion_18.to_numpy()})
comparacion_ols_seccion_18 = pd.DataFrame([{"modelo": "OLS sección 17", **metricas_ols_seccion_17}, {"modelo": "OLS sección 18", **metricas_ols_seccion_18}])
delta_metricas_seccion_18 = {f"delta_{metrica}": metricas_ols_seccion_18[metrica] - metricas_ols_seccion_17[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_18[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_18"):
    mlflow.set_tag("run_anterior_id", "27110ebe9f424d31a10ec9ba41d5a74a")
    mlflow.log_params({"seccion": 18, "dataset": str(RUTA_SALIDA_SECCION_18), "dataset_origen": str(RUTA_ORIGEN_SECCION_18), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variable_eliminada": VARIABLE_ELIMINADA_SECCION_18, "n_predictores": X_train_seccion_18.shape[1], "filas_entrenamiento": len(df_train_seccion_18), "filas_prueba": len(df_test_seccion_18), "tipo_modelo": "statsmodels_OLS_seccion_18_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_18, **delta_metricas_seccion_18})
    mlflow.log_table(comparacion_ols_seccion_18, artifact_file="comparacion/comparacion_ols_seccion_18.json")
    mlflow.log_table(coeficientes_ols_seccion_18, artifact_file="modelo/coeficientes_ols_seccion_18.json")
    mlflow.log_table(residuos_test_seccion_18, artifact_file="diagnostico/residuos_test_seccion_18.json")
    mlflow.log_text(resultados_ols_seccion_18.summary().as_text(), "modelo/resumen_ols_seccion_18.txt")
print(f"Dataset de la sección 18 guardado en: {RUTA_SALIDA_SECCION_18}")
print("OLS de la sección 18 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 17  37081.504127  45129.477642  0.859848  23.169997
1  OLS sección 18  37081.053061  45129.098683  0.859850  23.169435

🏃 View run ols_temporal_seccion_18 at: http://127.0.0.1:5000/#/experiments/4/runs/007c83a834694761a651b573027ccb37
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 18 guardado en: data_sets_transformados\secondary_market_modelado_seccion_18.csv
OLS de la sección 18 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 17.

## 19. OLS sin tres candidatas de la sección 8

Partimos del dataset acumulativo de la sección 18 y eliminamos `district_Ochakovo-Matveyevskoye`, `metro_station_Kitay-Gorod` y `metro_station_Smolenskaya (F)`. El nuevo dataset usa el número de sección en su nombre.

In [19]:
VARIABLES_ELIMINADAS_SECCION_19 = [
    "district_Ochakovo-Matveyevskoye",
    "metro_station_Kitay-Gorod",
    "metro_station_Smolenskaya (F)"
]
RUTA_ORIGEN_SECCION_19 = Path("data_sets_transformados/secondary_market_modelado_seccion_18.csv")
RUTA_SALIDA_SECCION_19 = Path("data_sets_transformados/secondary_market_modelado_seccion_19.csv")
df_ols_seccion_19_origen = pd.read_csv(RUTA_ORIGEN_SECCION_19)
columnas_faltantes_seccion_19 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_19 if columna not in df_ols_seccion_19_origen.columns]
if columnas_faltantes_seccion_19:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_19}")
df_ols_seccion_19 = df_ols_seccion_19_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_19).copy()
df_ols_seccion_19.to_csv(RUTA_SALIDA_SECCION_19, index=False)
df_train_seccion_19 = df_ols_seccion_19[df_ols_seccion_19["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_19 = df_ols_seccion_19[df_ols_seccion_19["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_19 = df_train_seccion_19.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_19 = df_test_seccion_19.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_19 = df_train_seccion_19["price_per_sqm"]
y_test_seccion_19 = df_test_seccion_19["price_per_sqm"]
X_train_seccion_19_sm = sm.add_constant(X_train_seccion_19, has_constant="add")
X_test_seccion_19_sm = sm.add_constant(X_test_seccion_19, has_constant="add")
resultados_ols_seccion_19 = sm.OLS(y_train_seccion_19, X_train_seccion_19_sm).fit()
predicciones_train_seccion_19 = resultados_ols_seccion_19.predict(X_train_seccion_19_sm)
predicciones_test_seccion_19 = resultados_ols_seccion_19.predict(X_test_seccion_19_sm)
metricas_ols_seccion_19 = {
    **calcular_metricas_regresion(y_train_seccion_19, predicciones_train_seccion_19, "train"),
    **calcular_metricas_regresion(y_test_seccion_19, predicciones_test_seccion_19, "test"),
    "r2_ols": float(resultados_ols_seccion_19.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_19.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_19.aic),
    "bic_ols": float(resultados_ols_seccion_19.bic),
    "f_statistic_ols": float(resultados_ols_seccion_19.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_19.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_19.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_19.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_19.pvalues > 0.05).sum())
}
omnibus_seccion_19, prob_omnibus_seccion_19 = omni_normtest(resultados_ols_seccion_19.resid)
jarque_bera_seccion_19, prob_jb_seccion_19, skew_seccion_19, kurtosis_seccion_19 = jarque_bera(resultados_ols_seccion_19.resid)
metricas_ols_seccion_19.update({
    "omnibus_ols": float(omnibus_seccion_19),
    "prob_omnibus_ols": float(prob_omnibus_seccion_19),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_19.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_19),
    "prob_jb_ols": float(prob_jb_seccion_19),
    "skew_ols": float(skew_seccion_19),
    "kurtosis_ols": float(kurtosis_seccion_19)
})
coeficientes_ols_seccion_19 = pd.DataFrame({"variable": resultados_ols_seccion_19.params.index, "coeficiente": resultados_ols_seccion_19.params.to_numpy(), "p_value": resultados_ols_seccion_19.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_19.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_19 = pd.DataFrame({"periodo": df_test_seccion_19["periodo"].to_numpy(), "real": y_test_seccion_19.to_numpy(), "prediccion": predicciones_test_seccion_19.to_numpy(), "residuo": y_test_seccion_19.to_numpy() - predicciones_test_seccion_19.to_numpy()})
comparacion_ols_seccion_19 = pd.DataFrame([{"modelo": "OLS sección 18", **metricas_ols_seccion_18}, {"modelo": "OLS sección 19", **metricas_ols_seccion_19}])
delta_metricas_seccion_19 = {f"delta_{metrica}": metricas_ols_seccion_19[metrica] - metricas_ols_seccion_18[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_19[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_19"):
    mlflow.set_tag("run_anterior_id", "32c10618074e4a35bb627541e766e934")
    mlflow.log_params({"seccion": 19, "dataset": str(RUTA_SALIDA_SECCION_19), "dataset_origen": str(RUTA_ORIGEN_SECCION_19), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_19), "n_predictores": X_train_seccion_19.shape[1], "filas_entrenamiento": len(df_train_seccion_19), "filas_prueba": len(df_test_seccion_19), "tipo_modelo": "statsmodels_OLS_seccion_19_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_19, **delta_metricas_seccion_19})
    mlflow.log_table(comparacion_ols_seccion_19, artifact_file="comparacion/comparacion_ols_seccion_19.json")
    mlflow.log_table(coeficientes_ols_seccion_19, artifact_file="modelo/coeficientes_ols_seccion_19.json")
    mlflow.log_table(residuos_test_seccion_19, artifact_file="diagnostico/residuos_test_seccion_19.json")
    mlflow.log_text(resultados_ols_seccion_19.summary().as_text(), "modelo/resumen_ols_seccion_19.txt")
print(f"Dataset de la sección 19 guardado en: {RUTA_SALIDA_SECCION_19}")
print("OLS de la sección 19 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 18  37081.053061  45129.098683  0.859850  23.169435
1  OLS sección 19  37079.847236  45129.182624  0.859849  23.169380

🏃 View run ols_temporal_seccion_19 at: http://127.0.0.1:5000/#/experiments/4/runs/8bfe94adfe4e45659ea3f9e25e03f479
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 19 guardado en: data_sets_transformados\secondary_market_modelado_seccion_19.csv
OLS de la sección 19 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 18.

## 20. OLS sin tres candidatas de la sección 8

Partimos del dataset acumulativo de la sección 19 y eliminamos `metro_station_Elektrozavodskaya`, `metro_station_Pechatniki` y `metro_station_Dostoevskaya`. El nuevo dataset usa el número de sección en su nombre.

In [20]:
VARIABLES_ELIMINADAS_SECCION_20 = [
    "metro_station_Elektrozavodskaya",
    "metro_station_Pechatniki",
    "metro_station_Dostoevskaya"
]
RUTA_ORIGEN_SECCION_20 = Path("data_sets_transformados/secondary_market_modelado_seccion_19.csv")
RUTA_SALIDA_SECCION_20 = Path("data_sets_transformados/secondary_market_modelado_seccion_20.csv")
df_ols_seccion_20_origen = pd.read_csv(RUTA_ORIGEN_SECCION_20)
columnas_faltantes_seccion_20 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_20 if columna not in df_ols_seccion_20_origen.columns]
if columnas_faltantes_seccion_20:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_20}")
df_ols_seccion_20 = df_ols_seccion_20_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_20).copy()
df_ols_seccion_20.to_csv(RUTA_SALIDA_SECCION_20, index=False)
df_train_seccion_20 = df_ols_seccion_20[df_ols_seccion_20["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_20 = df_ols_seccion_20[df_ols_seccion_20["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_20 = df_train_seccion_20.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_20 = df_test_seccion_20.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_20 = df_train_seccion_20["price_per_sqm"]
y_test_seccion_20 = df_test_seccion_20["price_per_sqm"]
X_train_seccion_20_sm = sm.add_constant(X_train_seccion_20, has_constant="add")
X_test_seccion_20_sm = sm.add_constant(X_test_seccion_20, has_constant="add")
resultados_ols_seccion_20 = sm.OLS(y_train_seccion_20, X_train_seccion_20_sm).fit()
predicciones_train_seccion_20 = resultados_ols_seccion_20.predict(X_train_seccion_20_sm)
predicciones_test_seccion_20 = resultados_ols_seccion_20.predict(X_test_seccion_20_sm)
metricas_ols_seccion_20 = {
    **calcular_metricas_regresion(y_train_seccion_20, predicciones_train_seccion_20, "train"),
    **calcular_metricas_regresion(y_test_seccion_20, predicciones_test_seccion_20, "test"),
    "r2_ols": float(resultados_ols_seccion_20.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_20.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_20.aic),
    "bic_ols": float(resultados_ols_seccion_20.bic),
    "f_statistic_ols": float(resultados_ols_seccion_20.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_20.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_20.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_20.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_20.pvalues > 0.05).sum())
}
omnibus_seccion_20, prob_omnibus_seccion_20 = omni_normtest(resultados_ols_seccion_20.resid)
jarque_bera_seccion_20, prob_jb_seccion_20, skew_seccion_20, kurtosis_seccion_20 = jarque_bera(resultados_ols_seccion_20.resid)
metricas_ols_seccion_20.update({
    "omnibus_ols": float(omnibus_seccion_20),
    "prob_omnibus_ols": float(prob_omnibus_seccion_20),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_20.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_20),
    "prob_jb_ols": float(prob_jb_seccion_20),
    "skew_ols": float(skew_seccion_20),
    "kurtosis_ols": float(kurtosis_seccion_20)
})
coeficientes_ols_seccion_20 = pd.DataFrame({"variable": resultados_ols_seccion_20.params.index, "coeficiente": resultados_ols_seccion_20.params.to_numpy(), "p_value": resultados_ols_seccion_20.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_20.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_20 = pd.DataFrame({"periodo": df_test_seccion_20["periodo"].to_numpy(), "real": y_test_seccion_20.to_numpy(), "prediccion": predicciones_test_seccion_20.to_numpy(), "residuo": y_test_seccion_20.to_numpy() - predicciones_test_seccion_20.to_numpy()})
comparacion_ols_seccion_20 = pd.DataFrame([{"modelo": "OLS sección 19", **metricas_ols_seccion_19}, {"modelo": "OLS sección 20", **metricas_ols_seccion_20}])
delta_metricas_seccion_20 = {f"delta_{metrica}": metricas_ols_seccion_20[metrica] - metricas_ols_seccion_19[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_20[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_20"):
    mlflow.set_tag("run_anterior_id", "cdef663475e34e24bae61bb7fc353318")
    mlflow.log_params({"seccion": 20, "dataset": str(RUTA_SALIDA_SECCION_20), "dataset_origen": str(RUTA_ORIGEN_SECCION_20), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_20), "n_predictores": X_train_seccion_20.shape[1], "filas_entrenamiento": len(df_train_seccion_20), "filas_prueba": len(df_test_seccion_20), "tipo_modelo": "statsmodels_OLS_seccion_20_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_20, **delta_metricas_seccion_20})
    mlflow.log_table(comparacion_ols_seccion_20, artifact_file="comparacion/comparacion_ols_seccion_20.json")
    mlflow.log_table(coeficientes_ols_seccion_20, artifact_file="modelo/coeficientes_ols_seccion_20.json")
    mlflow.log_table(residuos_test_seccion_20, artifact_file="diagnostico/residuos_test_seccion_20.json")
    mlflow.log_text(resultados_ols_seccion_20.summary().as_text(), "modelo/resumen_ols_seccion_20.txt")
print(f"Dataset de la sección 20 guardado en: {RUTA_SALIDA_SECCION_20}")
print("OLS de la sección 20 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 19  37079.847236  45129.182624  0.859849  23.169380
1  OLS sección 20  37076.824980  45126.757949  0.859864  23.166935

🏃 View run ols_temporal_seccion_20 at: http://127.0.0.1:5000/#/experiments/4/runs/997b1ed48d944e488d1d7cb5375c8dc8
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 20 guardado en: data_sets_transformados\secondary_market_modelado_seccion_20.csv
OLS de la sección 20 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 19.

## 21. OLS sin tres candidatas de la sección 8

Partimos del dataset acumulativo de la sección 20 y eliminamos `metro_station_Lubyanka`, `district_Sokolniki` y `metro_station_Chistye Prudy`. El nuevo dataset usa el número de sección en su nombre.

In [21]:
VARIABLES_ELIMINADAS_SECCION_21 = [
    "metro_station_Lubyanka",
    "district_Sokolniki",
    "metro_station_Chistye Prudy"
]
RUTA_ORIGEN_SECCION_21 = Path("data_sets_transformados/secondary_market_modelado_seccion_20.csv")
RUTA_SALIDA_SECCION_21 = Path("data_sets_transformados/secondary_market_modelado_seccion_21.csv")
df_ols_seccion_21_origen = pd.read_csv(RUTA_ORIGEN_SECCION_21)
columnas_faltantes_seccion_21 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_21 if columna not in df_ols_seccion_21_origen.columns]
if columnas_faltantes_seccion_21:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_21}")
df_ols_seccion_21 = df_ols_seccion_21_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_21).copy()
df_ols_seccion_21.to_csv(RUTA_SALIDA_SECCION_21, index=False)
df_train_seccion_21 = df_ols_seccion_21[df_ols_seccion_21["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_21 = df_ols_seccion_21[df_ols_seccion_21["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_21 = df_train_seccion_21.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_21 = df_test_seccion_21.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_21 = df_train_seccion_21["price_per_sqm"]
y_test_seccion_21 = df_test_seccion_21["price_per_sqm"]
X_train_seccion_21_sm = sm.add_constant(X_train_seccion_21, has_constant="add")
X_test_seccion_21_sm = sm.add_constant(X_test_seccion_21, has_constant="add")
resultados_ols_seccion_21 = sm.OLS(y_train_seccion_21, X_train_seccion_21_sm).fit()
predicciones_train_seccion_21 = resultados_ols_seccion_21.predict(X_train_seccion_21_sm)
predicciones_test_seccion_21 = resultados_ols_seccion_21.predict(X_test_seccion_21_sm)
metricas_ols_seccion_21 = {
    **calcular_metricas_regresion(y_train_seccion_21, predicciones_train_seccion_21, "train"),
    **calcular_metricas_regresion(y_test_seccion_21, predicciones_test_seccion_21, "test"),
    "r2_ols": float(resultados_ols_seccion_21.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_21.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_21.aic),
    "bic_ols": float(resultados_ols_seccion_21.bic),
    "f_statistic_ols": float(resultados_ols_seccion_21.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_21.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_21.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_21.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_21.pvalues > 0.05).sum())
}
omnibus_seccion_21, prob_omnibus_seccion_21 = omni_normtest(resultados_ols_seccion_21.resid)
jarque_bera_seccion_21, prob_jb_seccion_21, skew_seccion_21, kurtosis_seccion_21 = jarque_bera(resultados_ols_seccion_21.resid)
metricas_ols_seccion_21.update({
    "omnibus_ols": float(omnibus_seccion_21),
    "prob_omnibus_ols": float(prob_omnibus_seccion_21),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_21.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_21),
    "prob_jb_ols": float(prob_jb_seccion_21),
    "skew_ols": float(skew_seccion_21),
    "kurtosis_ols": float(kurtosis_seccion_21)
})
coeficientes_ols_seccion_21 = pd.DataFrame({"variable": resultados_ols_seccion_21.params.index, "coeficiente": resultados_ols_seccion_21.params.to_numpy(), "p_value": resultados_ols_seccion_21.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_21.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_21 = pd.DataFrame({"periodo": df_test_seccion_21["periodo"].to_numpy(), "real": y_test_seccion_21.to_numpy(), "prediccion": predicciones_test_seccion_21.to_numpy(), "residuo": y_test_seccion_21.to_numpy() - predicciones_test_seccion_21.to_numpy()})
comparacion_ols_seccion_21 = pd.DataFrame([{"modelo": "OLS sección 20", **metricas_ols_seccion_20}, {"modelo": "OLS sección 21", **metricas_ols_seccion_21}])
delta_metricas_seccion_21 = {f"delta_{metrica}": metricas_ols_seccion_21[metrica] - metricas_ols_seccion_20[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_21[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_21"):
    mlflow.set_tag("run_anterior_id", "79d57bfdd7254954a9639304df0e39c3")
    mlflow.log_params({"seccion": 21, "dataset": str(RUTA_SALIDA_SECCION_21), "dataset_origen": str(RUTA_ORIGEN_SECCION_21), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_21), "n_predictores": X_train_seccion_21.shape[1], "filas_entrenamiento": len(df_train_seccion_21), "filas_prueba": len(df_test_seccion_21), "tipo_modelo": "statsmodels_OLS_seccion_21_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_21, **delta_metricas_seccion_21})
    mlflow.log_table(comparacion_ols_seccion_21, artifact_file="comparacion/comparacion_ols_seccion_21.json")
    mlflow.log_table(coeficientes_ols_seccion_21, artifact_file="modelo/coeficientes_ols_seccion_21.json")
    mlflow.log_table(residuos_test_seccion_21, artifact_file="diagnostico/residuos_test_seccion_21.json")
    mlflow.log_text(resultados_ols_seccion_21.summary().as_text(), "modelo/resumen_ols_seccion_21.txt")
print(f"Dataset de la sección 21 guardado en: {RUTA_SALIDA_SECCION_21}")
print("OLS de la sección 21 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 20  37076.824980  45126.757949  0.859864  23.166935
1  OLS sección 21  37075.255959  45125.466604  0.859873  23.166044

🏃 View run ols_temporal_seccion_21 at: http://127.0.0.1:5000/#/experiments/4/runs/d8f58fb11b2a48bc9cada57b65055a87
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 21 guardado en: data_sets_transformados\secondary_market_modelado_seccion_21.csv
OLS de la sección 21 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 20.

## 22. OLS sin tres candidatas de la sección 8

Partimos del dataset acumulativo de la sección 21 y eliminamos `building_age`, `district_Zyuzino` y `metro_station_Molodyozhnaya`.

In [22]:
VARIABLES_ELIMINADAS_SECCION_22 = [
    "building_age",
    "district_Zyuzino",
    "metro_station_Molodyozhnaya"
]
RUTA_ORIGEN_SECCION_22 = Path("data_sets_transformados/secondary_market_modelado_seccion_21.csv")
RUTA_SALIDA_SECCION_22 = Path("data_sets_transformados/secondary_market_modelado_seccion_22.csv")
df_ols_seccion_22_origen = pd.read_csv(RUTA_ORIGEN_SECCION_22)
columnas_faltantes_seccion_22 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_22 if columna not in df_ols_seccion_22_origen.columns]
if columnas_faltantes_seccion_22:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_22}")
df_ols_seccion_22 = df_ols_seccion_22_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_22).copy()
df_ols_seccion_22.to_csv(RUTA_SALIDA_SECCION_22, index=False)
df_train_seccion_22 = df_ols_seccion_22[df_ols_seccion_22["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_22 = df_ols_seccion_22[df_ols_seccion_22["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_22 = df_train_seccion_22.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_22 = df_test_seccion_22.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_22 = df_train_seccion_22["price_per_sqm"]
y_test_seccion_22 = df_test_seccion_22["price_per_sqm"]
X_train_seccion_22_sm = sm.add_constant(X_train_seccion_22, has_constant="add")
X_test_seccion_22_sm = sm.add_constant(X_test_seccion_22, has_constant="add")
resultados_ols_seccion_22 = sm.OLS(y_train_seccion_22, X_train_seccion_22_sm).fit()
predicciones_train_seccion_22 = resultados_ols_seccion_22.predict(X_train_seccion_22_sm)
predicciones_test_seccion_22 = resultados_ols_seccion_22.predict(X_test_seccion_22_sm)
metricas_ols_seccion_22 = {
    **calcular_metricas_regresion(y_train_seccion_22, predicciones_train_seccion_22, "train"),
    **calcular_metricas_regresion(y_test_seccion_22, predicciones_test_seccion_22, "test"),
    "r2_ols": float(resultados_ols_seccion_22.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_22.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_22.aic),
    "bic_ols": float(resultados_ols_seccion_22.bic),
    "f_statistic_ols": float(resultados_ols_seccion_22.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_22.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_22.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_22.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_22.pvalues > 0.05).sum())
}
omnibus_seccion_22, prob_omnibus_seccion_22 = omni_normtest(resultados_ols_seccion_22.resid)
jarque_bera_seccion_22, prob_jb_seccion_22, skew_seccion_22, kurtosis_seccion_22 = jarque_bera(resultados_ols_seccion_22.resid)
metricas_ols_seccion_22.update({
    "omnibus_ols": float(omnibus_seccion_22),
    "prob_omnibus_ols": float(prob_omnibus_seccion_22),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_22.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_22),
    "prob_jb_ols": float(prob_jb_seccion_22),
    "skew_ols": float(skew_seccion_22),
    "kurtosis_ols": float(kurtosis_seccion_22)
})
coeficientes_ols_seccion_22 = pd.DataFrame({"variable": resultados_ols_seccion_22.params.index, "coeficiente": resultados_ols_seccion_22.params.to_numpy(), "p_value": resultados_ols_seccion_22.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_22.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_22 = pd.DataFrame({"periodo": df_test_seccion_22["periodo"].to_numpy(), "real": y_test_seccion_22.to_numpy(), "prediccion": predicciones_test_seccion_22.to_numpy(), "residuo": y_test_seccion_22.to_numpy() - predicciones_test_seccion_22.to_numpy()})
comparacion_ols_seccion_22 = pd.DataFrame([{"modelo": "OLS sección 21", **metricas_ols_seccion_21}, {"modelo": "OLS sección 22", **metricas_ols_seccion_22}])
delta_metricas_seccion_22 = {f"delta_{metrica}": metricas_ols_seccion_22[metrica] - metricas_ols_seccion_21[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_22[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_22"):
    mlflow.set_tag("run_anterior_id", "123db2e67e9c4bcfb7c8736776d6ff57")
    mlflow.log_params({"seccion": 22, "dataset": str(RUTA_SALIDA_SECCION_22), "dataset_origen": str(RUTA_ORIGEN_SECCION_22), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_22), "n_predictores": X_train_seccion_22.shape[1], "filas_entrenamiento": len(df_train_seccion_22), "filas_prueba": len(df_test_seccion_22), "tipo_modelo": "statsmodels_OLS_seccion_22_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_22, **delta_metricas_seccion_22})
    mlflow.log_table(comparacion_ols_seccion_22, artifact_file="comparacion/comparacion_ols_seccion_22.json")
    mlflow.log_table(coeficientes_ols_seccion_22, artifact_file="modelo/coeficientes_ols_seccion_22.json")
    mlflow.log_table(residuos_test_seccion_22, artifact_file="diagnostico/residuos_test_seccion_22.json")
    mlflow.log_text(resultados_ols_seccion_22.summary().as_text(), "modelo/resumen_ols_seccion_22.txt")
print(f"Dataset de la sección 22 guardado en: {RUTA_SALIDA_SECCION_22}")
print("OLS de la sección 22 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 21  37075.255959  45125.466604  0.859873  23.166044
1  OLS sección 22  37073.634354  45123.905470  0.859882  23.165532

🏃 View run ols_temporal_seccion_22 at: http://127.0.0.1:5000/#/experiments/4/runs/65eec57ee34c4c1eb966c495cce3eafd
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 22 guardado en: data_sets_transformados\secondary_market_modelado_seccion_22.csv
OLS de la sección 22 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 21.

## 23. OLS sin dos candidatas de la sección 8

Partimos del dataset acumulativo de la sección 22 y eliminamos `metro_station_Teatralnaya` y `metro_station_Smolenskaya (AP)`.

In [23]:
VARIABLES_ELIMINADAS_SECCION_23 = [
    "metro_station_Teatralnaya",
    "metro_station_Smolenskaya (AP)"
]
RUTA_ORIGEN_SECCION_23 = Path("data_sets_transformados/secondary_market_modelado_seccion_22.csv")
RUTA_SALIDA_SECCION_23 = Path("data_sets_transformados/secondary_market_modelado_seccion_23.csv")
df_ols_seccion_23_origen = pd.read_csv(RUTA_ORIGEN_SECCION_23)
columnas_faltantes_seccion_23 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_23 if columna not in df_ols_seccion_23_origen.columns]
if columnas_faltantes_seccion_23:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_23}")
df_ols_seccion_23 = df_ols_seccion_23_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_23).copy()
df_ols_seccion_23.to_csv(RUTA_SALIDA_SECCION_23, index=False)
df_train_seccion_23 = df_ols_seccion_23[df_ols_seccion_23["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_23 = df_ols_seccion_23[df_ols_seccion_23["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_23 = df_train_seccion_23.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_23 = df_test_seccion_23.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_23 = df_train_seccion_23["price_per_sqm"]
y_test_seccion_23 = df_test_seccion_23["price_per_sqm"]
X_train_seccion_23_sm = sm.add_constant(X_train_seccion_23, has_constant="add")
X_test_seccion_23_sm = sm.add_constant(X_test_seccion_23, has_constant="add")
resultados_ols_seccion_23 = sm.OLS(y_train_seccion_23, X_train_seccion_23_sm).fit()
predicciones_train_seccion_23 = resultados_ols_seccion_23.predict(X_train_seccion_23_sm)
predicciones_test_seccion_23 = resultados_ols_seccion_23.predict(X_test_seccion_23_sm)
metricas_ols_seccion_23 = {
    **calcular_metricas_regresion(y_train_seccion_23, predicciones_train_seccion_23, "train"),
    **calcular_metricas_regresion(y_test_seccion_23, predicciones_test_seccion_23, "test"),
    "r2_ols": float(resultados_ols_seccion_23.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_23.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_23.aic),
    "bic_ols": float(resultados_ols_seccion_23.bic),
    "f_statistic_ols": float(resultados_ols_seccion_23.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_23.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_23.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_23.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_23.pvalues > 0.05).sum())
}
omnibus_seccion_23, prob_omnibus_seccion_23 = omni_normtest(resultados_ols_seccion_23.resid)
jarque_bera_seccion_23, prob_jb_seccion_23, skew_seccion_23, kurtosis_seccion_23 = jarque_bera(resultados_ols_seccion_23.resid)
metricas_ols_seccion_23.update({
    "omnibus_ols": float(omnibus_seccion_23),
    "prob_omnibus_ols": float(prob_omnibus_seccion_23),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_23.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_23),
    "prob_jb_ols": float(prob_jb_seccion_23),
    "skew_ols": float(skew_seccion_23),
    "kurtosis_ols": float(kurtosis_seccion_23)
})
coeficientes_ols_seccion_23 = pd.DataFrame({"variable": resultados_ols_seccion_23.params.index, "coeficiente": resultados_ols_seccion_23.params.to_numpy(), "p_value": resultados_ols_seccion_23.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_23.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_23 = pd.DataFrame({"periodo": df_test_seccion_23["periodo"].to_numpy(), "real": y_test_seccion_23.to_numpy(), "prediccion": predicciones_test_seccion_23.to_numpy(), "residuo": y_test_seccion_23.to_numpy() - predicciones_test_seccion_23.to_numpy()})
comparacion_ols_seccion_23 = pd.DataFrame([{"modelo": "OLS sección 22", **metricas_ols_seccion_22}, {"modelo": "OLS sección 23", **metricas_ols_seccion_23}])
delta_metricas_seccion_23 = {f"delta_{metrica}": metricas_ols_seccion_23[metrica] - metricas_ols_seccion_22[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_23[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_23"):
    mlflow.set_tag("run_anterior_id", "12dea48cdde64f178bfd00a2e111760e")
    mlflow.log_params({"seccion": 23, "dataset": str(RUTA_SALIDA_SECCION_23), "dataset_origen": str(RUTA_ORIGEN_SECCION_23), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_23), "n_predictores": X_train_seccion_23.shape[1], "filas_entrenamiento": len(df_train_seccion_23), "filas_prueba": len(df_test_seccion_23), "tipo_modelo": "statsmodels_OLS_seccion_23_acumulativo"})
    mlflow.log_metrics({**metricas_ols_seccion_23, **delta_metricas_seccion_23})
    mlflow.log_table(comparacion_ols_seccion_23, artifact_file="comparacion/comparacion_ols_seccion_23.json")
    mlflow.log_table(coeficientes_ols_seccion_23, artifact_file="modelo/coeficientes_ols_seccion_23.json")
    mlflow.log_table(residuos_test_seccion_23, artifact_file="diagnostico/residuos_test_seccion_23.json")
    mlflow.log_text(resultados_ols_seccion_23.summary().as_text(), "modelo/resumen_ols_seccion_23.txt")
print(f"Dataset de la sección 23 guardado en: {RUTA_SALIDA_SECCION_23}")
print("OLS de la sección 23 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 22  37073.634354  45123.905470  0.859882  23.165532
1  OLS sección 23  37074.438694  45126.590672  0.859866  23.166574

🏃 View run ols_temporal_seccion_23 at: http://127.0.0.1:5000/#/experiments/4/runs/c7a8ad9a33b24428be3f616686cec0ab
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 23 guardado en: data_sets_transformados\secondary_market_modelado_seccion_23.csv
OLS de la sección 23 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las dos candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 22.

## 24. OLS sin `metro_station_Teatralnaya` desde la sección 22

Partimos directamente del dataset acumulativo de la sección 22 y eliminamos únicamente `metro_station_Teatralnaya`.

In [24]:
VARIABLES_ELIMINADAS_SECCION_24 = ["metro_station_Teatralnaya"]
RUTA_ORIGEN_SECCION_24 = Path("data_sets_transformados/secondary_market_modelado_seccion_22.csv")
RUTA_SALIDA_SECCION_24 = Path("data_sets_transformados/secondary_market_modelado_seccion_24.csv")
df_ols_seccion_24_origen = pd.read_csv(RUTA_ORIGEN_SECCION_24)
columnas_faltantes_seccion_24 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_24 if columna not in df_ols_seccion_24_origen.columns]
if columnas_faltantes_seccion_24:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_24}")
df_ols_seccion_24 = df_ols_seccion_24_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_24).copy()
df_ols_seccion_24.to_csv(RUTA_SALIDA_SECCION_24, index=False)
df_train_seccion_24 = df_ols_seccion_24[df_ols_seccion_24["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_24 = df_ols_seccion_24[df_ols_seccion_24["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_24 = df_train_seccion_24.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_24 = df_test_seccion_24.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_24 = df_train_seccion_24["price_per_sqm"]
y_test_seccion_24 = df_test_seccion_24["price_per_sqm"]
X_train_seccion_24_sm = sm.add_constant(X_train_seccion_24, has_constant="add")
X_test_seccion_24_sm = sm.add_constant(X_test_seccion_24, has_constant="add")
resultados_ols_seccion_24 = sm.OLS(y_train_seccion_24, X_train_seccion_24_sm).fit()
predicciones_train_seccion_24 = resultados_ols_seccion_24.predict(X_train_seccion_24_sm)
predicciones_test_seccion_24 = resultados_ols_seccion_24.predict(X_test_seccion_24_sm)
metricas_ols_seccion_24 = {
    **calcular_metricas_regresion(y_train_seccion_24, predicciones_train_seccion_24, "train"),
    **calcular_metricas_regresion(y_test_seccion_24, predicciones_test_seccion_24, "test"),
    "r2_ols": float(resultados_ols_seccion_24.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_24.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_24.aic),
    "bic_ols": float(resultados_ols_seccion_24.bic),
    "f_statistic_ols": float(resultados_ols_seccion_24.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_24.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_24.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_24.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_24.pvalues > 0.05).sum())
}
omnibus_seccion_24, prob_omnibus_seccion_24 = omni_normtest(resultados_ols_seccion_24.resid)
jarque_bera_seccion_24, prob_jb_seccion_24, skew_seccion_24, kurtosis_seccion_24 = jarque_bera(resultados_ols_seccion_24.resid)
metricas_ols_seccion_24.update({
    "omnibus_ols": float(omnibus_seccion_24),
    "prob_omnibus_ols": float(prob_omnibus_seccion_24),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_24.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_24),
    "prob_jb_ols": float(prob_jb_seccion_24),
    "skew_ols": float(skew_seccion_24),
    "kurtosis_ols": float(kurtosis_seccion_24)
})
coeficientes_ols_seccion_24 = pd.DataFrame({"variable": resultados_ols_seccion_24.params.index, "coeficiente": resultados_ols_seccion_24.params.to_numpy(), "p_value": resultados_ols_seccion_24.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_24.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_24 = pd.DataFrame({"periodo": df_test_seccion_24["periodo"].to_numpy(), "real": y_test_seccion_24.to_numpy(), "prediccion": predicciones_test_seccion_24.to_numpy(), "residuo": y_test_seccion_24.to_numpy() - predicciones_test_seccion_24.to_numpy()})
comparacion_ols_seccion_24 = pd.DataFrame([{"modelo": "OLS sección 22", **metricas_ols_seccion_22}, {"modelo": "OLS sección 24", **metricas_ols_seccion_24}])
delta_metricas_seccion_24 = {f"delta_{metrica}": metricas_ols_seccion_24[metrica] - metricas_ols_seccion_22[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_24[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_24"):
    mlflow.set_tag("run_anterior_id", "12dea48cdde64f178bfd00a2e111760e")
    mlflow.log_params({"seccion": 24, "dataset": str(RUTA_SALIDA_SECCION_24), "dataset_origen": str(RUTA_ORIGEN_SECCION_24), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_24), "n_predictores": X_train_seccion_24.shape[1], "filas_entrenamiento": len(df_train_seccion_24), "filas_prueba": len(df_test_seccion_24), "tipo_modelo": "statsmodels_OLS_seccion_24_desde_seccion_22"})
    mlflow.log_metrics({**metricas_ols_seccion_24, **delta_metricas_seccion_24})
    mlflow.log_table(comparacion_ols_seccion_24, artifact_file="comparacion/comparacion_ols_seccion_24.json")
    mlflow.log_table(coeficientes_ols_seccion_24, artifact_file="modelo/coeficientes_ols_seccion_24.json")
    mlflow.log_table(residuos_test_seccion_24, artifact_file="diagnostico/residuos_test_seccion_24.json")
    mlflow.log_text(resultados_ols_seccion_24.summary().as_text(), "modelo/resumen_ols_seccion_24.txt")
print(f"Dataset de la sección 24 guardado en: {RUTA_SALIDA_SECCION_24}")
print("OLS de la sección 24 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 22  37073.634354  45123.905470  0.859882  23.165532
1  OLS sección 24  37075.470169  45125.892866  0.859870  23.167252

🏃 View run ols_temporal_seccion_24 at: http://127.0.0.1:5000/#/experiments/4/runs/aa5cbfa6cc1c4b20a5d0fda50c064b01
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 24 guardado en: data_sets_transformados\secondary_market_modelado_seccion_24.csv
OLS de la sección 24 registrado en MLflow para comparación

### Interpretación

La eliminación de `metro_station_Teatralnaya` se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 22.

## 25. OLS sin tres candidatas de la sección 8

Partimos del dataset acumulativo de la sección 24 y eliminamos `metro_station_Smolenskaya (AP)`, `metro_station_Mayakovskaya` y `metro_station_Dubrovka`.

In [25]:
VARIABLES_ELIMINADAS_SECCION_25 = [
    "metro_station_Smolenskaya (AP)",
    "metro_station_Mayakovskaya",
    "metro_station_Dubrovka"
]
RUTA_ORIGEN_SECCION_25 = Path("data_sets_transformados/secondary_market_modelado_seccion_24.csv")
RUTA_SALIDA_SECCION_25 = Path("data_sets_transformados/secondary_market_modelado_seccion_25.csv")
df_ols_seccion_25_origen = pd.read_csv(RUTA_ORIGEN_SECCION_25)
columnas_faltantes_seccion_25 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_25 if columna not in df_ols_seccion_25_origen.columns]
if columnas_faltantes_seccion_25:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_25}")
df_ols_seccion_25 = df_ols_seccion_25_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_25).copy()
df_ols_seccion_25.to_csv(RUTA_SALIDA_SECCION_25, index=False)
df_train_seccion_25 = df_ols_seccion_25[df_ols_seccion_25["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_25 = df_ols_seccion_25[df_ols_seccion_25["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_25 = df_train_seccion_25.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_25 = df_test_seccion_25.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_25 = df_train_seccion_25["price_per_sqm"]
y_test_seccion_25 = df_test_seccion_25["price_per_sqm"]
X_train_seccion_25_sm = sm.add_constant(X_train_seccion_25, has_constant="add")
X_test_seccion_25_sm = sm.add_constant(X_test_seccion_25, has_constant="add")
resultados_ols_seccion_25 = sm.OLS(y_train_seccion_25, X_train_seccion_25_sm).fit()
predicciones_train_seccion_25 = resultados_ols_seccion_25.predict(X_train_seccion_25_sm)
predicciones_test_seccion_25 = resultados_ols_seccion_25.predict(X_test_seccion_25_sm)
metricas_ols_seccion_25 = {
    **calcular_metricas_regresion(y_train_seccion_25, predicciones_train_seccion_25, "train"),
    **calcular_metricas_regresion(y_test_seccion_25, predicciones_test_seccion_25, "test"),
    "r2_ols": float(resultados_ols_seccion_25.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_25.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_25.aic),
    "bic_ols": float(resultados_ols_seccion_25.bic),
    "f_statistic_ols": float(resultados_ols_seccion_25.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_25.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_25.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_25.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_25.pvalues > 0.05).sum())
}
omnibus_seccion_25, prob_omnibus_seccion_25 = omni_normtest(resultados_ols_seccion_25.resid)
jarque_bera_seccion_25, prob_jb_seccion_25, skew_seccion_25, kurtosis_seccion_25 = jarque_bera(resultados_ols_seccion_25.resid)
metricas_ols_seccion_25.update({
    "omnibus_ols": float(omnibus_seccion_25),
    "prob_omnibus_ols": float(prob_omnibus_seccion_25),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_25.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_25),
    "prob_jb_ols": float(prob_jb_seccion_25),
    "skew_ols": float(skew_seccion_25),
    "kurtosis_ols": float(kurtosis_seccion_25)
})
coeficientes_ols_seccion_25 = pd.DataFrame({"variable": resultados_ols_seccion_25.params.index, "coeficiente": resultados_ols_seccion_25.params.to_numpy(), "p_value": resultados_ols_seccion_25.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_25.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_25 = pd.DataFrame({"periodo": df_test_seccion_25["periodo"].to_numpy(), "real": y_test_seccion_25.to_numpy(), "prediccion": predicciones_test_seccion_25.to_numpy(), "residuo": y_test_seccion_25.to_numpy() - predicciones_test_seccion_25.to_numpy()})
comparacion_ols_seccion_25 = pd.DataFrame([{"modelo": "OLS sección 24", **metricas_ols_seccion_24}, {"modelo": "OLS sección 25", **metricas_ols_seccion_25}])
delta_metricas_seccion_25 = {f"delta_{metrica}": metricas_ols_seccion_25[metrica] - metricas_ols_seccion_24[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_25[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_25"):
    mlflow.set_tag("run_anterior_id", "0233e7b41eb24bbebbe1802409ffa833")
    mlflow.log_params({"seccion": 25, "dataset": str(RUTA_SALIDA_SECCION_25), "dataset_origen": str(RUTA_ORIGEN_SECCION_25), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_25), "n_predictores": X_train_seccion_25.shape[1], "filas_entrenamiento": len(df_train_seccion_25), "filas_prueba": len(df_test_seccion_25), "tipo_modelo": "statsmodels_OLS_seccion_25_desde_seccion_24"})
    mlflow.log_metrics({**metricas_ols_seccion_25, **delta_metricas_seccion_25})
    mlflow.log_table(comparacion_ols_seccion_25, artifact_file="comparacion/comparacion_ols_seccion_25.json")
    mlflow.log_table(coeficientes_ols_seccion_25, artifact_file="modelo/coeficientes_ols_seccion_25.json")
    mlflow.log_table(residuos_test_seccion_25, artifact_file="diagnostico/residuos_test_seccion_25.json")
    mlflow.log_text(resultados_ols_seccion_25.summary().as_text(), "modelo/resumen_ols_seccion_25.txt")
print(f"Dataset de la sección 25 guardado en: {RUTA_SALIDA_SECCION_25}")
print("OLS de la sección 25 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 24  37075.470169  45125.892866  0.859870  23.167252
1  OLS sección 25  37072.694776  45125.764307  0.859871  23.165666

🏃 View run ols_temporal_seccion_25 at: http://127.0.0.1:5000/#/experiments/4/runs/e405b69c92dd4ec69dfab06e62ef7071
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 25 guardado en: data_sets_transformados\secondary_market_modelado_seccion_25.csv
OLS de la sección 25 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres candidatas se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 24.

## 26. OLS sin `total_area` desde la sección 25

Partimos del dataset acumulativo de la sección 25 y eliminamos únicamente `total_area`.

In [26]:
VARIABLES_ELIMINADAS_SECCION_26 = ["total_area"]
RUTA_ORIGEN_SECCION_26 = Path("data_sets_transformados/secondary_market_modelado_seccion_25.csv")
RUTA_SALIDA_SECCION_26 = Path("data_sets_transformados/secondary_market_modelado_seccion_26.csv")
df_ols_seccion_26_origen = pd.read_csv(RUTA_ORIGEN_SECCION_26)
columnas_faltantes_seccion_26 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_26 if columna not in df_ols_seccion_26_origen.columns]
if columnas_faltantes_seccion_26:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_26}")
df_ols_seccion_26 = df_ols_seccion_26_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_26).copy()
df_ols_seccion_26.to_csv(RUTA_SALIDA_SECCION_26, index=False)
df_train_seccion_26 = df_ols_seccion_26[df_ols_seccion_26["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_26 = df_ols_seccion_26[df_ols_seccion_26["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_26 = df_train_seccion_26.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_26 = df_test_seccion_26.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_26 = df_train_seccion_26["price_per_sqm"]
y_test_seccion_26 = df_test_seccion_26["price_per_sqm"]
X_train_seccion_26_sm = sm.add_constant(X_train_seccion_26, has_constant="add")
X_test_seccion_26_sm = sm.add_constant(X_test_seccion_26, has_constant="add")
resultados_ols_seccion_26 = sm.OLS(y_train_seccion_26, X_train_seccion_26_sm).fit()
predicciones_train_seccion_26 = resultados_ols_seccion_26.predict(X_train_seccion_26_sm)
predicciones_test_seccion_26 = resultados_ols_seccion_26.predict(X_test_seccion_26_sm)
metricas_ols_seccion_26 = {
    **calcular_metricas_regresion(y_train_seccion_26, predicciones_train_seccion_26, "train"),
    **calcular_metricas_regresion(y_test_seccion_26, predicciones_test_seccion_26, "test"),
    "r2_ols": float(resultados_ols_seccion_26.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_26.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_26.aic),
    "bic_ols": float(resultados_ols_seccion_26.bic),
    "f_statistic_ols": float(resultados_ols_seccion_26.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_26.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_26.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_26.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_26.pvalues > 0.05).sum())
}
omnibus_seccion_26, prob_omnibus_seccion_26 = omni_normtest(resultados_ols_seccion_26.resid)
jarque_bera_seccion_26, prob_jb_seccion_26, skew_seccion_26, kurtosis_seccion_26 = jarque_bera(resultados_ols_seccion_26.resid)
metricas_ols_seccion_26.update({
    "omnibus_ols": float(omnibus_seccion_26),
    "prob_omnibus_ols": float(prob_omnibus_seccion_26),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_26.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_26),
    "prob_jb_ols": float(prob_jb_seccion_26),
    "skew_ols": float(skew_seccion_26),
    "kurtosis_ols": float(kurtosis_seccion_26)
})
coeficientes_ols_seccion_26 = pd.DataFrame({"variable": resultados_ols_seccion_26.params.index, "coeficiente": resultados_ols_seccion_26.params.to_numpy(), "p_value": resultados_ols_seccion_26.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_26.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_26 = pd.DataFrame({"periodo": df_test_seccion_26["periodo"].to_numpy(), "real": y_test_seccion_26.to_numpy(), "prediccion": predicciones_test_seccion_26.to_numpy(), "residuo": y_test_seccion_26.to_numpy() - predicciones_test_seccion_26.to_numpy()})
comparacion_ols_seccion_26 = pd.DataFrame([{"modelo": "OLS sección 25", **metricas_ols_seccion_25}, {"modelo": "OLS sección 26", **metricas_ols_seccion_26}])
delta_metricas_seccion_26 = {f"delta_{metrica}": metricas_ols_seccion_26[metrica] - metricas_ols_seccion_25[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_26[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_26"):
    mlflow.set_tag("run_anterior_id", "b9816ee7a5ed4b628d6dddb768a4cfec")
    mlflow.log_params({"seccion": 26, "dataset": str(RUTA_SALIDA_SECCION_26), "dataset_origen": str(RUTA_ORIGEN_SECCION_26), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_26), "n_predictores": X_train_seccion_26.shape[1], "filas_entrenamiento": len(df_train_seccion_26), "filas_prueba": len(df_test_seccion_26), "tipo_modelo": "statsmodels_OLS_seccion_26_desde_seccion_25"})
    mlflow.log_metrics({**metricas_ols_seccion_26, **delta_metricas_seccion_26})
    mlflow.log_table(comparacion_ols_seccion_26, artifact_file="comparacion/comparacion_ols_seccion_26.json")
    mlflow.log_table(coeficientes_ols_seccion_26, artifact_file="modelo/coeficientes_ols_seccion_26.json")
    mlflow.log_table(residuos_test_seccion_26, artifact_file="diagnostico/residuos_test_seccion_26.json")
    mlflow.log_text(resultados_ols_seccion_26.summary().as_text(), "modelo/resumen_ols_seccion_26.txt")
print(f"Dataset de la sección 26 guardado en: {RUTA_SALIDA_SECCION_26}")
print("OLS de la sección 26 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 25  37072.694776  45125.764307  0.859871  23.165666
1  OLS sección 26  37072.523484  45125.073874  0.859875  23.165776

🏃 View run ols_temporal_seccion_26 at: http://127.0.0.1:5000/#/experiments/4/runs/8997b0e5202949df9aad478e0fb9ef27
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 26 guardado en: data_sets_transformados\secondary_market_modelado_seccion_26.csv
OLS de la sección 26 registrado en MLflow para comparación

### Interpretación

La eliminación de `total_area` se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 25.

## 27. OLS sin `total_area` desde la sección 22

Partimos directamente del dataset acumulativo de la sección 22 y eliminamos únicamente `total_area`.

In [27]:
VARIABLES_ELIMINADAS_SECCION_27 = ["total_area"]
RUTA_ORIGEN_SECCION_27 = Path("data_sets_transformados/secondary_market_modelado_seccion_22.csv")
RUTA_SALIDA_SECCION_27 = Path("data_sets_transformados/secondary_market_modelado_seccion_27.csv")
df_ols_seccion_27_origen = pd.read_csv(RUTA_ORIGEN_SECCION_27)
columnas_faltantes_seccion_27 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_27 if columna not in df_ols_seccion_27_origen.columns]
if columnas_faltantes_seccion_27:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_27}")
df_ols_seccion_27 = df_ols_seccion_27_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_27).copy()
df_ols_seccion_27.to_csv(RUTA_SALIDA_SECCION_27, index=False)
df_train_seccion_27 = df_ols_seccion_27[df_ols_seccion_27["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_27 = df_ols_seccion_27[df_ols_seccion_27["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_27 = df_train_seccion_27.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_27 = df_test_seccion_27.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_27 = df_train_seccion_27["price_per_sqm"]
y_test_seccion_27 = df_test_seccion_27["price_per_sqm"]
X_train_seccion_27_sm = sm.add_constant(X_train_seccion_27, has_constant="add")
X_test_seccion_27_sm = sm.add_constant(X_test_seccion_27, has_constant="add")
resultados_ols_seccion_27 = sm.OLS(y_train_seccion_27, X_train_seccion_27_sm).fit()
predicciones_train_seccion_27 = resultados_ols_seccion_27.predict(X_train_seccion_27_sm)
predicciones_test_seccion_27 = resultados_ols_seccion_27.predict(X_test_seccion_27_sm)
metricas_ols_seccion_27 = {
    **calcular_metricas_regresion(y_train_seccion_27, predicciones_train_seccion_27, "train"),
    **calcular_metricas_regresion(y_test_seccion_27, predicciones_test_seccion_27, "test"),
    "r2_ols": float(resultados_ols_seccion_27.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_27.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_27.aic),
    "bic_ols": float(resultados_ols_seccion_27.bic),
    "f_statistic_ols": float(resultados_ols_seccion_27.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_27.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_27.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_27.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_27.pvalues > 0.05).sum())
}
omnibus_seccion_27, prob_omnibus_seccion_27 = omni_normtest(resultados_ols_seccion_27.resid)
jarque_bera_seccion_27, prob_jb_seccion_27, skew_seccion_27, kurtosis_seccion_27 = jarque_bera(resultados_ols_seccion_27.resid)
metricas_ols_seccion_27.update({
    "omnibus_ols": float(omnibus_seccion_27),
    "prob_omnibus_ols": float(prob_omnibus_seccion_27),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_27.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_27),
    "prob_jb_ols": float(prob_jb_seccion_27),
    "skew_ols": float(skew_seccion_27),
    "kurtosis_ols": float(kurtosis_seccion_27)
})
coeficientes_ols_seccion_27 = pd.DataFrame({"variable": resultados_ols_seccion_27.params.index, "coeficiente": resultados_ols_seccion_27.params.to_numpy(), "p_value": resultados_ols_seccion_27.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_27.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_27 = pd.DataFrame({"periodo": df_test_seccion_27["periodo"].to_numpy(), "real": y_test_seccion_27.to_numpy(), "prediccion": predicciones_test_seccion_27.to_numpy(), "residuo": y_test_seccion_27.to_numpy() - predicciones_test_seccion_27.to_numpy()})
comparacion_ols_seccion_27 = pd.DataFrame([{"modelo": "OLS sección 22", **metricas_ols_seccion_22}, {"modelo": "OLS sección 27", **metricas_ols_seccion_27}])
delta_metricas_seccion_27 = {f"delta_{metrica}": metricas_ols_seccion_27[metrica] - metricas_ols_seccion_22[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_27[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_27"):
    mlflow.set_tag("run_anterior_id", "12dea48cdde64f178bfd00a2e111760e")
    mlflow.log_params({"seccion": 27, "dataset": str(RUTA_SALIDA_SECCION_27), "dataset_origen": str(RUTA_ORIGEN_SECCION_27), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_27), "n_predictores": X_train_seccion_27.shape[1], "filas_entrenamiento": len(df_train_seccion_27), "filas_prueba": len(df_test_seccion_27), "tipo_modelo": "statsmodels_OLS_seccion_27_desde_seccion_22"})
    mlflow.log_metrics({**metricas_ols_seccion_27, **delta_metricas_seccion_27})
    mlflow.log_table(comparacion_ols_seccion_27, artifact_file="comparacion/comparacion_ols_seccion_27.json")
    mlflow.log_table(coeficientes_ols_seccion_27, artifact_file="modelo/coeficientes_ols_seccion_27.json")
    mlflow.log_table(residuos_test_seccion_27, artifact_file="diagnostico/residuos_test_seccion_27.json")
    mlflow.log_text(resultados_ols_seccion_27.summary().as_text(), "modelo/resumen_ols_seccion_27.txt")
print(f"Dataset de la sección 27 guardado en: {RUTA_SALIDA_SECCION_27}")
print("OLS de la sección 27 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 22  37073.634354  45123.905470  0.859882  23.165532
1  OLS sección 27  37073.461485  45123.234408  0.859886  23.165613

🏃 View run ols_temporal_seccion_27 at: http://127.0.0.1:5000/#/experiments/4/runs/7bbe48e4ece84fb4be52eb8731dd8c20
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 27 guardado en: data_sets_transformados\secondary_market_modelado_seccion_27.csv
OLS de la sección 27 registrado en MLflow para comparación

### Interpretación

La eliminación de `total_area` se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 22.

## 28. OLS sin `rooms` desde la sección 27

Partimos del dataset acumulativo de la sección 27 y eliminamos únicamente `rooms`.

In [28]:
VARIABLES_ELIMINADAS_SECCION_28 = ["rooms"]
RUTA_ORIGEN_SECCION_28 = Path("data_sets_transformados/secondary_market_modelado_seccion_27.csv")
RUTA_SALIDA_SECCION_28 = Path("data_sets_transformados/secondary_market_modelado_seccion_28.csv")
df_ols_seccion_28_origen = pd.read_csv(RUTA_ORIGEN_SECCION_28)
columnas_faltantes_seccion_28 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_28 if columna not in df_ols_seccion_28_origen.columns]
if columnas_faltantes_seccion_28:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_28}")
df_ols_seccion_28 = df_ols_seccion_28_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_28).copy()
df_ols_seccion_28.to_csv(RUTA_SALIDA_SECCION_28, index=False)
df_train_seccion_28 = df_ols_seccion_28[df_ols_seccion_28["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_28 = df_ols_seccion_28[df_ols_seccion_28["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_28 = df_train_seccion_28.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_28 = df_test_seccion_28.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_28 = df_train_seccion_28["price_per_sqm"]
y_test_seccion_28 = df_test_seccion_28["price_per_sqm"]
X_train_seccion_28_sm = sm.add_constant(X_train_seccion_28, has_constant="add")
X_test_seccion_28_sm = sm.add_constant(X_test_seccion_28, has_constant="add")
resultados_ols_seccion_28 = sm.OLS(y_train_seccion_28, X_train_seccion_28_sm).fit()
predicciones_train_seccion_28 = resultados_ols_seccion_28.predict(X_train_seccion_28_sm)
predicciones_test_seccion_28 = resultados_ols_seccion_28.predict(X_test_seccion_28_sm)
metricas_ols_seccion_28 = {
    **calcular_metricas_regresion(y_train_seccion_28, predicciones_train_seccion_28, "train"),
    **calcular_metricas_regresion(y_test_seccion_28, predicciones_test_seccion_28, "test"),
    "r2_ols": float(resultados_ols_seccion_28.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_28.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_28.aic),
    "bic_ols": float(resultados_ols_seccion_28.bic),
    "f_statistic_ols": float(resultados_ols_seccion_28.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_28.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_28.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_28.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_28.pvalues > 0.05).sum())
}
omnibus_seccion_28, prob_omnibus_seccion_28 = omni_normtest(resultados_ols_seccion_28.resid)
jarque_bera_seccion_28, prob_jb_seccion_28, skew_seccion_28, kurtosis_seccion_28 = jarque_bera(resultados_ols_seccion_28.resid)
metricas_ols_seccion_28.update({
    "omnibus_ols": float(omnibus_seccion_28),
    "prob_omnibus_ols": float(prob_omnibus_seccion_28),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_28.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_28),
    "prob_jb_ols": float(prob_jb_seccion_28),
    "skew_ols": float(skew_seccion_28),
    "kurtosis_ols": float(kurtosis_seccion_28)
})
coeficientes_ols_seccion_28 = pd.DataFrame({"variable": resultados_ols_seccion_28.params.index, "coeficiente": resultados_ols_seccion_28.params.to_numpy(), "p_value": resultados_ols_seccion_28.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_28.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_28 = pd.DataFrame({"periodo": df_test_seccion_28["periodo"].to_numpy(), "real": y_test_seccion_28.to_numpy(), "prediccion": predicciones_test_seccion_28.to_numpy(), "residuo": y_test_seccion_28.to_numpy() - predicciones_test_seccion_28.to_numpy()})
comparacion_ols_seccion_28 = pd.DataFrame([{"modelo": "OLS sección 27", **metricas_ols_seccion_27}, {"modelo": "OLS sección 28", **metricas_ols_seccion_28}])
delta_metricas_seccion_28 = {f"delta_{metrica}": metricas_ols_seccion_28[metrica] - metricas_ols_seccion_27[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_28[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_28"):
    mlflow.set_tag("run_anterior_id", "d41a0b6a1c4d4de6ac75794edec5e4ce")
    mlflow.log_params({"seccion": 28, "dataset": str(RUTA_SALIDA_SECCION_28), "dataset_origen": str(RUTA_ORIGEN_SECCION_28), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_28), "n_predictores": X_train_seccion_28.shape[1], "filas_entrenamiento": len(df_train_seccion_28), "filas_prueba": len(df_test_seccion_28), "tipo_modelo": "statsmodels_OLS_seccion_28_desde_seccion_27"})
    mlflow.log_metrics({**metricas_ols_seccion_28, **delta_metricas_seccion_28})
    mlflow.log_table(comparacion_ols_seccion_28, artifact_file="comparacion/comparacion_ols_seccion_28.json")
    mlflow.log_table(coeficientes_ols_seccion_28, artifact_file="modelo/coeficientes_ols_seccion_28.json")
    mlflow.log_table(residuos_test_seccion_28, artifact_file="diagnostico/residuos_test_seccion_28.json")
    mlflow.log_text(resultados_ols_seccion_28.summary().as_text(), "modelo/resumen_ols_seccion_28.txt")
print(f"Dataset de la sección 28 guardado en: {RUTA_SALIDA_SECCION_28}")
print("OLS de la sección 28 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 27  37073.461485  45123.234408  0.859886  23.165613
1  OLS sección 28  37073.955260  45123.774721  0.859883  23.165970

🏃 View run ols_temporal_seccion_28 at: http://127.0.0.1:5000/#/experiments/4/runs/6a06fac38c97464cac61871e1fc0809e
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 28 guardado en: data_sets_transformados\secondary_market_modelado_seccion_28.csv
OLS de la sección 28 registrado en MLflow para comparación

### Interpretación

La eliminación de `rooms` se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 27.

## 29. OLS sin tres estaciones desde la sección 27

Partimos del dataset acumulativo de la sección 27 y eliminamos `metro_station_Teatralnaya`, `metro_station_Smolenskaya (AP)` y `metro_station_Mayakovskaya`.

In [29]:
VARIABLES_ELIMINADAS_SECCION_29 = [
    "metro_station_Teatralnaya",
    "metro_station_Smolenskaya (AP)",
    "metro_station_Mayakovskaya"
]
RUTA_ORIGEN_SECCION_29 = Path("data_sets_transformados/secondary_market_modelado_seccion_27.csv")
RUTA_SALIDA_SECCION_29 = Path("data_sets_transformados/secondary_market_modelado_seccion_29.csv")
df_ols_seccion_29_origen = pd.read_csv(RUTA_ORIGEN_SECCION_29)
columnas_faltantes_seccion_29 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_29 if columna not in df_ols_seccion_29_origen.columns]
if columnas_faltantes_seccion_29:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_29}")
df_ols_seccion_29 = df_ols_seccion_29_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_29).copy()
df_ols_seccion_29.to_csv(RUTA_SALIDA_SECCION_29, index=False)
df_train_seccion_29 = df_ols_seccion_29[df_ols_seccion_29["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_29 = df_ols_seccion_29[df_ols_seccion_29["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_29 = df_train_seccion_29.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_29 = df_test_seccion_29.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_29 = df_train_seccion_29["price_per_sqm"]
y_test_seccion_29 = df_test_seccion_29["price_per_sqm"]
X_train_seccion_29_sm = sm.add_constant(X_train_seccion_29, has_constant="add")
X_test_seccion_29_sm = sm.add_constant(X_test_seccion_29, has_constant="add")
resultados_ols_seccion_29 = sm.OLS(y_train_seccion_29, X_train_seccion_29_sm).fit()
predicciones_train_seccion_29 = resultados_ols_seccion_29.predict(X_train_seccion_29_sm)
predicciones_test_seccion_29 = resultados_ols_seccion_29.predict(X_test_seccion_29_sm)
metricas_ols_seccion_29 = {
    **calcular_metricas_regresion(y_train_seccion_29, predicciones_train_seccion_29, "train"),
    **calcular_metricas_regresion(y_test_seccion_29, predicciones_test_seccion_29, "test"),
    "r2_ols": float(resultados_ols_seccion_29.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_29.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_29.aic),
    "bic_ols": float(resultados_ols_seccion_29.bic),
    "f_statistic_ols": float(resultados_ols_seccion_29.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_29.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_29.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_29.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_29.pvalues > 0.05).sum())
}
omnibus_seccion_29, prob_omnibus_seccion_29 = omni_normtest(resultados_ols_seccion_29.resid)
jarque_bera_seccion_29, prob_jb_seccion_29, skew_seccion_29, kurtosis_seccion_29 = jarque_bera(resultados_ols_seccion_29.resid)
metricas_ols_seccion_29.update({
    "omnibus_ols": float(omnibus_seccion_29),
    "prob_omnibus_ols": float(prob_omnibus_seccion_29),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_29.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_29),
    "prob_jb_ols": float(prob_jb_seccion_29),
    "skew_ols": float(skew_seccion_29),
    "kurtosis_ols": float(kurtosis_seccion_29)
})
coeficientes_ols_seccion_29 = pd.DataFrame({"variable": resultados_ols_seccion_29.params.index, "coeficiente": resultados_ols_seccion_29.params.to_numpy(), "p_value": resultados_ols_seccion_29.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_29.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_29 = pd.DataFrame({"periodo": df_test_seccion_29["periodo"].to_numpy(), "real": y_test_seccion_29.to_numpy(), "prediccion": predicciones_test_seccion_29.to_numpy(), "residuo": y_test_seccion_29.to_numpy() - predicciones_test_seccion_29.to_numpy()})
comparacion_ols_seccion_29 = pd.DataFrame([{"modelo": "OLS sección 27", **metricas_ols_seccion_27}, {"modelo": "OLS sección 29", **metricas_ols_seccion_29}])
delta_metricas_seccion_29 = {f"delta_{metrica}": metricas_ols_seccion_29[metrica] - metricas_ols_seccion_27[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_29[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_29"):
    mlflow.set_tag("run_anterior_id", "d41a0b6a1c4d4de6ac75794edec5e4ce")
    mlflow.log_params({"seccion": 29, "dataset": str(RUTA_SALIDA_SECCION_29), "dataset_origen": str(RUTA_ORIGEN_SECCION_29), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_29), "n_predictores": X_train_seccion_29.shape[1], "filas_entrenamiento": len(df_train_seccion_29), "filas_prueba": len(df_test_seccion_29), "tipo_modelo": "statsmodels_OLS_seccion_29_desde_seccion_27"})
    mlflow.log_metrics({**metricas_ols_seccion_29, **delta_metricas_seccion_29})
    mlflow.log_table(comparacion_ols_seccion_29, artifact_file="comparacion/comparacion_ols_seccion_29.json")
    mlflow.log_table(coeficientes_ols_seccion_29, artifact_file="modelo/coeficientes_ols_seccion_29.json")
    mlflow.log_table(residuos_test_seccion_29, artifact_file="diagnostico/residuos_test_seccion_29.json")
    mlflow.log_text(resultados_ols_seccion_29.summary().as_text(), "modelo/resumen_ols_seccion_29.txt")
print(f"Dataset de la sección 29 guardado en: {RUTA_SALIDA_SECCION_29}")
print("OLS de la sección 29 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 27  37073.461485  45123.234408  0.859886  23.165613
1  OLS sección 29  37072.766055  45125.261894  0.859874  23.165723

🏃 View run ols_temporal_seccion_29 at: http://127.0.0.1:5000/#/experiments/4/runs/50301279727e4940b163ddcb052f319c
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 29 guardado en: data_sets_transformados\secondary_market_modelado_seccion_29.csv
OLS de la sección 29 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las tres estaciones se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad o el número de condición frente a la sección 27.

## 30. OLS sin variables `metro_station_` desde la sección 27

Partimos del dataset acumulativo de la sección 27 y eliminamos todas las columnas cuyo nombre comienza con `metro_station_`, sin considerar su p-value individual.

In [30]:
RUTA_ORIGEN_SECCION_30 = Path("data_sets_transformados/secondary_market_modelado_seccion_27.csv")
RUTA_SALIDA_SECCION_30 = Path("data_sets_transformados/secondary_market_modelado_seccion_30.csv")
df_ols_seccion_30_origen = pd.read_csv(RUTA_ORIGEN_SECCION_30)
VARIABLES_ELIMINADAS_SECCION_30 = [columna for columna in df_ols_seccion_30_origen.columns if columna.startswith("metro_station_")]
if not VARIABLES_ELIMINADAS_SECCION_30:
    raise ValueError("No se encontraron variables metro_station_ para eliminar")
df_ols_seccion_30 = df_ols_seccion_30_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_30).copy()
df_ols_seccion_30.to_csv(RUTA_SALIDA_SECCION_30, index=False)
df_train_seccion_30 = df_ols_seccion_30[df_ols_seccion_30["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_30 = df_ols_seccion_30[df_ols_seccion_30["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_30 = df_train_seccion_30.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_30 = df_test_seccion_30.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_30 = df_train_seccion_30["price_per_sqm"]
y_test_seccion_30 = df_test_seccion_30["price_per_sqm"]
X_train_seccion_30_sm = sm.add_constant(X_train_seccion_30, has_constant="add")
X_test_seccion_30_sm = sm.add_constant(X_test_seccion_30, has_constant="add")
resultados_ols_seccion_30 = sm.OLS(y_train_seccion_30, X_train_seccion_30_sm).fit()
predicciones_train_seccion_30 = resultados_ols_seccion_30.predict(X_train_seccion_30_sm)
predicciones_test_seccion_30 = resultados_ols_seccion_30.predict(X_test_seccion_30_sm)
metricas_ols_seccion_30 = {
    **calcular_metricas_regresion(y_train_seccion_30, predicciones_train_seccion_30, "train"),
    **calcular_metricas_regresion(y_test_seccion_30, predicciones_test_seccion_30, "test"),
    "r2_ols": float(resultados_ols_seccion_30.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_30.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_30.aic),
    "bic_ols": float(resultados_ols_seccion_30.bic),
    "f_statistic_ols": float(resultados_ols_seccion_30.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_30.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_30.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_30.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_30.pvalues > 0.05).sum())
}
omnibus_seccion_30, prob_omnibus_seccion_30 = omni_normtest(resultados_ols_seccion_30.resid)
jarque_bera_seccion_30, prob_jb_seccion_30, skew_seccion_30, kurtosis_seccion_30 = jarque_bera(resultados_ols_seccion_30.resid)
metricas_ols_seccion_30.update({
    "omnibus_ols": float(omnibus_seccion_30),
    "prob_omnibus_ols": float(prob_omnibus_seccion_30),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_30.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_30),
    "prob_jb_ols": float(prob_jb_seccion_30),
    "skew_ols": float(skew_seccion_30),
    "kurtosis_ols": float(kurtosis_seccion_30)
})
coeficientes_ols_seccion_30 = pd.DataFrame({"variable": resultados_ols_seccion_30.params.index, "coeficiente": resultados_ols_seccion_30.params.to_numpy(), "p_value": resultados_ols_seccion_30.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_30.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_30 = pd.DataFrame({"periodo": df_test_seccion_30["periodo"].to_numpy(), "real": y_test_seccion_30.to_numpy(), "prediccion": predicciones_test_seccion_30.to_numpy(), "residuo": y_test_seccion_30.to_numpy() - predicciones_test_seccion_30.to_numpy()})
comparacion_ols_seccion_30 = pd.DataFrame([{"modelo": "OLS sección 27", **metricas_ols_seccion_27}, {"modelo": "OLS sección 30", **metricas_ols_seccion_30}])
delta_metricas_seccion_30 = {f"delta_{metrica}": metricas_ols_seccion_30[metrica] - metricas_ols_seccion_27[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_30[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_30"):
    mlflow.set_tag("run_anterior_id", "d41a0b6a1c4d4de6ac75794edec5e4ce")
    mlflow.log_params({"seccion": 30, "dataset": str(RUTA_SALIDA_SECCION_30), "dataset_origen": str(RUTA_ORIGEN_SECCION_30), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_30), "n_predictores": X_train_seccion_30.shape[1], "filas_entrenamiento": len(df_train_seccion_30), "filas_prueba": len(df_test_seccion_30), "tipo_modelo": "statsmodels_OLS_seccion_30_sin_metro_station"})
    mlflow.log_metrics({**metricas_ols_seccion_30, **delta_metricas_seccion_30})
    mlflow.log_table(comparacion_ols_seccion_30, artifact_file="comparacion/comparacion_ols_seccion_30.json")
    mlflow.log_table(coeficientes_ols_seccion_30, artifact_file="modelo/coeficientes_ols_seccion_30.json")
    mlflow.log_table(residuos_test_seccion_30, artifact_file="diagnostico/residuos_test_seccion_30.json")
    mlflow.log_text(resultados_ols_seccion_30.summary().as_text(), "modelo/resumen_ols_seccion_30.txt")
print(f"Dataset de la sección 30 guardado en: {RUTA_SALIDA_SECCION_30}")
print(f"Variables metro_station_ eliminadas: {len(VARIABLES_ELIMINADAS_SECCION_30)}")
print("OLS de la sección 30 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 27  37073.461485  45123.234408  0.859886  23.165613
1  OLS sección 30  37146.928901  45256.240708  0.859059  23.144575

🏃 View run ols_temporal_seccion_30 at: http://127.0.0.1:5000/#/experiments/4/runs/4c6ec29964ed4fca9cf90c94f975d952
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 30 guardado en: data_sets_transformados\secondary_market_modelado_seccion_30.csv
Variables metro_station_ eliminadas: 84
OLS de la sección 30 registrado en MLflow para comparación

### Interpretación

La eliminación del grupo completo `metro_station_` se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad frente a la sección 27.

## 31. OLS sin cinco variables de distrito desde la sección 30

Partimos del dataset acumulativo de la sección 30 y eliminamos `district_Konkovo`, `district_Mozhaysky`, `district_Alekseevsky`, `district_Rogovskoye` y `district_Ostankinsky`.

In [2]:
VARIABLES_ELIMINADAS_SECCION_31 = [
    "district_Konkovo",
    "district_Mozhaysky",
    "district_Alekseevsky",
    "district_Rogovskoye",
    "district_Ostankinsky"
]
RUTA_ORIGEN_SECCION_31 = Path("data_sets_transformados/secondary_market_modelado_seccion_30.csv")
RUTA_SALIDA_SECCION_31 = Path("data_sets_transformados/secondary_market_modelado_seccion_31.csv")
df_ols_seccion_31_origen = pd.read_csv(RUTA_ORIGEN_SECCION_31)
columnas_faltantes_seccion_31 = [columna for columna in VARIABLES_ELIMINADAS_SECCION_31 if columna not in df_ols_seccion_31_origen.columns]
if columnas_faltantes_seccion_31:
    raise KeyError(f"Columnas no disponibles: {columnas_faltantes_seccion_31}")
df_ols_seccion_31 = df_ols_seccion_31_origen.drop(columns=VARIABLES_ELIMINADAS_SECCION_31).copy()
df_ols_seccion_31.to_csv(RUTA_SALIDA_SECCION_31, index=False)
df_train_seccion_31 = df_ols_seccion_31[df_ols_seccion_31["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_31 = df_ols_seccion_31[df_ols_seccion_31["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_31 = df_train_seccion_31.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_31 = df_test_seccion_31.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_31 = df_train_seccion_31["price_per_sqm"]
y_test_seccion_31 = df_test_seccion_31["price_per_sqm"]
X_train_seccion_31_sm = sm.add_constant(X_train_seccion_31, has_constant="add")
X_test_seccion_31_sm = sm.add_constant(X_test_seccion_31, has_constant="add")
resultados_ols_seccion_31 = sm.OLS(y_train_seccion_31, X_train_seccion_31_sm).fit()
predicciones_train_seccion_31 = resultados_ols_seccion_31.predict(X_train_seccion_31_sm)
predicciones_test_seccion_31 = resultados_ols_seccion_31.predict(X_test_seccion_31_sm)
metricas_ols_seccion_31 = {
    **calcular_metricas_regresion(y_train_seccion_31, predicciones_train_seccion_31, "train"),
    **calcular_metricas_regresion(y_test_seccion_31, predicciones_test_seccion_31, "test"),
    "r2_ols": float(resultados_ols_seccion_31.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_31.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_31.aic),
    "bic_ols": float(resultados_ols_seccion_31.bic),
    "f_statistic_ols": float(resultados_ols_seccion_31.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_31.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_31.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_31.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_31.pvalues > 0.05).sum())
}
omnibus_seccion_31, prob_omnibus_seccion_31 = omni_normtest(resultados_ols_seccion_31.resid)
jarque_bera_seccion_31, prob_jb_seccion_31, skew_seccion_31, kurtosis_seccion_31 = jarque_bera(resultados_ols_seccion_31.resid)
metricas_ols_seccion_31.update({
    "omnibus_ols": float(omnibus_seccion_31),
    "prob_omnibus_ols": float(prob_omnibus_seccion_31),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_31.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_31),
    "prob_jb_ols": float(prob_jb_seccion_31),
    "skew_ols": float(skew_seccion_31),
    "kurtosis_ols": float(kurtosis_seccion_31)
})
coeficientes_ols_seccion_31 = pd.DataFrame({"variable": resultados_ols_seccion_31.params.index, "coeficiente": resultados_ols_seccion_31.params.to_numpy(), "p_value": resultados_ols_seccion_31.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_31.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_31 = pd.DataFrame({"periodo": df_test_seccion_31["periodo"].to_numpy(), "real": y_test_seccion_31.to_numpy(), "prediccion": predicciones_test_seccion_31.to_numpy(), "residuo": y_test_seccion_31.to_numpy() - predicciones_test_seccion_31.to_numpy()})
comparacion_ols_seccion_31 = pd.DataFrame([{"modelo": "OLS sección 30", **metricas_ols_seccion_30}, {"modelo": "OLS sección 31", **metricas_ols_seccion_31}])
delta_metricas_seccion_31 = {f"delta_{metrica}": metricas_ols_seccion_31[metrica] - metricas_ols_seccion_30[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_31[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_31"):
    mlflow.set_tag("run_anterior_id", "4c6ec29964ed4fca9cf90c94f975d952")
    mlflow.log_params({"seccion": 31, "dataset": str(RUTA_SALIDA_SECCION_31), "dataset_origen": str(RUTA_ORIGEN_SECCION_31), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "variables_eliminadas": ",".join(VARIABLES_ELIMINADAS_SECCION_31), "n_predictores": X_train_seccion_31.shape[1], "filas_entrenamiento": len(df_train_seccion_31), "filas_prueba": len(df_test_seccion_31), "tipo_modelo": "statsmodels_OLS_seccion_31_desde_seccion_30"})
    mlflow.log_metrics({**metricas_ols_seccion_31, **delta_metricas_seccion_31})
    mlflow.log_table(comparacion_ols_seccion_31, artifact_file="comparacion/comparacion_ols_seccion_31.json")
    mlflow.log_table(coeficientes_ols_seccion_31, artifact_file="modelo/coeficientes_ols_seccion_31.json")
    mlflow.log_table(residuos_test_seccion_31, artifact_file="diagnostico/residuos_test_seccion_31.json")
    mlflow.log_text(resultados_ols_seccion_31.summary().as_text(), "modelo/resumen_ols_seccion_31.txt")
print(f"Dataset de la sección 31 guardado en: {RUTA_SALIDA_SECCION_31}")
print("OLS de la sección 31 registrado en MLflow para comparación")

           modelo      mae_test     rmse_test   r2_test  mape_test
0  OLS sección 30  37146.928901  45256.240708  0.859059  23.144575
1  OLS sección 31  37149.437615  45256.355993  0.859058  23.147238

🏃 View run ols_temporal_seccion_31 at: http://127.0.0.1:5000/#/experiments/4/runs/c23f82b46c20461798877412394fe438
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset de la sección 31 guardado en: data_sets_transformados\secondary_market_modelado_seccion_31.csv
OLS de la sección 31 registrado en MLflow para comparación

### Interpretación

La eliminación acumulativa de las cinco variables de distrito se acepta solo si conserva o mejora las métricas temporales y reduce la complejidad frente a la sección 30.

## 32. Mercado estandar con corte de 402600 RUB/m2

Partimos del dataset completo de la seccion 27. El corte de 402600 RUB/m2 fue calculado sobre el conjunto de entrenamiento con la regla Q3 + 1,5 IQR. Los registros superiores se conservan en un dataset premium separado.

In [1]:
CORTE_PRECIO_ESTANDAR_SECCION_32 = 402600
RUTA_ORIGEN_SECCION_32 = Path("data_sets_transformados/secondary_market_modelado_seccion_27.csv")
RUTA_SALIDA_SECCION_32 = Path("data_sets_transformados/secondary_market_modelado_seccion_32.csv")
RUTA_SALIDA_PREMIUM_SECCION_32 = Path("data_sets_transformados/secondary_market_modelado_seccion_32_premium.csv")
df_ols_seccion_32_origen = pd.read_csv(RUTA_ORIGEN_SECCION_32)
if df_ols_seccion_32_origen["price_per_sqm"].isna().any() or (df_ols_seccion_32_origen["price_per_sqm"] <= 0).any():
    raise ValueError("price_per_sqm contiene valores faltantes, cero o negativos")
df_ols_seccion_32 = df_ols_seccion_32_origen[df_ols_seccion_32_origen["price_per_sqm"] <= CORTE_PRECIO_ESTANDAR_SECCION_32].copy()
df_premium_seccion_32 = df_ols_seccion_32_origen[df_ols_seccion_32_origen["price_per_sqm"] > CORTE_PRECIO_ESTANDAR_SECCION_32].copy()
df_ols_seccion_32.to_csv(RUTA_SALIDA_SECCION_32, index=False)
df_premium_seccion_32.to_csv(RUTA_SALIDA_PREMIUM_SECCION_32, index=False)
df_train_seccion_32 = df_ols_seccion_32[df_ols_seccion_32["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_32 = df_ols_seccion_32[df_ols_seccion_32["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_32 = df_train_seccion_32.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_32 = df_test_seccion_32.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_32 = df_train_seccion_32["price_per_sqm"]
y_test_seccion_32 = df_test_seccion_32["price_per_sqm"]
if df_train_seccion_32.empty or df_test_seccion_32.empty:
    raise ValueError("El corte temporal no produjo train y test para el mercado estandar")
X_train_seccion_32_sm = sm.add_constant(X_train_seccion_32, has_constant="add")
X_test_seccion_32_sm = sm.add_constant(X_test_seccion_32, has_constant="add")
resultados_ols_seccion_32 = sm.OLS(y_train_seccion_32, X_train_seccion_32_sm).fit()
predicciones_train_seccion_32 = resultados_ols_seccion_32.predict(X_train_seccion_32_sm)
predicciones_test_seccion_32 = resultados_ols_seccion_32.predict(X_test_seccion_32_sm)
metricas_ols_seccion_32 = {
    **calcular_metricas_regresion(y_train_seccion_32, predicciones_train_seccion_32, "train"),
    **calcular_metricas_regresion(y_test_seccion_32, predicciones_test_seccion_32, "test"),
    "r2_ols": float(resultados_ols_seccion_32.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_32.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_32.aic),
    "bic_ols": float(resultados_ols_seccion_32.bic),
    "f_statistic_ols": float(resultados_ols_seccion_32.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_32.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_32.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_32.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_32.pvalues > 0.05).sum()),
    "filas_mercado_estandar": float(len(df_ols_seccion_32)),
    "filas_mercado_premium": float(len(df_premium_seccion_32)),
    "proporcion_mercado_estandar": float(len(df_ols_seccion_32) / len(df_ols_seccion_32_origen)),
    "proporcion_mercado_premium": float(len(df_premium_seccion_32) / len(df_ols_seccion_32_origen))
}
omnibus_seccion_32, prob_omnibus_seccion_32 = omni_normtest(resultados_ols_seccion_32.resid)
jarque_bera_seccion_32, prob_jb_seccion_32, skew_seccion_32, kurtosis_seccion_32 = jarque_bera(resultados_ols_seccion_32.resid)
metricas_ols_seccion_32.update({
    "omnibus_ols": float(omnibus_seccion_32),
    "prob_omnibus_ols": float(prob_omnibus_seccion_32),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_32.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_32),
    "prob_jb_ols": float(prob_jb_seccion_32),
    "skew_ols": float(skew_seccion_32),
    "kurtosis_ols": float(kurtosis_seccion_32)
})
coeficientes_ols_seccion_32 = pd.DataFrame({"variable": resultados_ols_seccion_32.params.index, "coeficiente": resultados_ols_seccion_32.params.to_numpy(), "p_value": resultados_ols_seccion_32.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_32.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_32 = pd.DataFrame({"periodo": df_test_seccion_32["periodo"].to_numpy(), "real": y_test_seccion_32.to_numpy(), "prediccion": predicciones_test_seccion_32.to_numpy(), "residuo": y_test_seccion_32.to_numpy() - predicciones_test_seccion_32.to_numpy()})
comparacion_ols_seccion_32 = pd.DataFrame([{"modelo": "OLS seccion 27 - mercado completo", **metricas_ols_seccion_27}, {"modelo": "OLS seccion 32 - mercado estandar", **metricas_ols_seccion_32}])
delta_metricas_seccion_32 = {f"delta_{metrica}": metricas_ols_seccion_32[metrica] - metricas_ols_seccion_27[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_32[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_32_mercado_estandar"):
    mlflow.set_tag("run_anterior_id", "d41a0b6a1c4d4de6ac75794edec5e4ce")
    mlflow.log_params({"seccion": 32, "dataset": str(RUTA_SALIDA_SECCION_32), "dataset_premium": str(RUTA_SALIDA_PREMIUM_SECCION_32), "dataset_origen": str(RUTA_ORIGEN_SECCION_32), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "corte_precio_estandar_rub_m2": CORTE_PRECIO_ESTANDAR_SECCION_32, "metodo_corte": "Q3_mas_1_5_IQR_entrenamiento", "n_predictores": X_train_seccion_32.shape[1], "filas_entrenamiento": len(df_train_seccion_32), "filas_prueba": len(df_test_seccion_32), "filas_mercado_estandar": len(df_ols_seccion_32), "filas_mercado_premium": len(df_premium_seccion_32), "tipo_modelo": "statsmodels_OLS_seccion_32_mercado_estandar"})
    mlflow.log_metrics({**metricas_ols_seccion_32, **delta_metricas_seccion_32})
    mlflow.log_table(comparacion_ols_seccion_32, artifact_file="comparacion/comparacion_ols_seccion_32.json")
    mlflow.log_table(coeficientes_ols_seccion_32, artifact_file="modelo/coeficientes_ols_seccion_32.json")
    mlflow.log_table(residuos_test_seccion_32, artifact_file="diagnostico/residuos_test_seccion_32.json")
    mlflow.log_text(resultados_ols_seccion_32.summary().as_text(), "modelo/resumen_ols_seccion_32.txt")
print(f"Dataset estandar de la seccion 32 guardado en: {RUTA_SALIDA_SECCION_32}")
print(f"Dataset premium de la seccion 32 guardado en: {RUTA_SALIDA_PREMIUM_SECCION_32}")
print(f"Filas estandar: {len(df_ols_seccion_32)} | Filas premium: {len(df_premium_seccion_32)}")
print("OLS de la seccion 32 registrado en MLflow para comparacion")

                           modelo     mae_test    rmse_test  r2_test  mape_test
OLS seccion 27 - mercado completo 37073.461485 45123.234408 0.859886  23.165613
OLS seccion 32 - mercado estandar 29086.281498 34129.077912 0.818523  20.276878

?? View run ols_temporal_seccion_32_mercado_estandar at: http://127.0.0.1:5000/#/experiments/4/runs/29ba44bd36e74b409e4c62400200402c
?? View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset estandar de la seccion 32 guardado en: data_sets_transformados\secondary_market_modelado_seccion_32.csv
Dataset premium de la seccion 32 guardado en: data_sets_transformados\secondary_market_modelado_seccion_32_premium.csv
Filas estandar: 47052 | Filas premium: 2948
OLS de la seccion 32 registrado en MLflow para comparacion

### Interpretacion

La seccion 32 representa el mercado estandar definido por `price_per_sqm <= 402600 RUB/m2`. Los registros superiores no se eliminan del proyecto: se conservan en el dataset premium para analizarlos por separado.

## 33. Mercado estandar con corte desde el dataset de la seccion 3

Partimos del dataset one-hot completo generado en la seccion 3 y aplicamos el corte de `402600 RUB/m2`. Los registros superiores se conservan en un dataset premium separado. La comparacion predictiva principal usa el mismo subconjunto estandar del periodo de prueba.

In [1]:
CORTE_PRECIO_ESTANDAR_SECCION_33 = 402600
RUTA_ORIGEN_SECCION_33 = Path("data_sets_transformados/secondary_market_modelado_one_hot.csv")
RUTA_SALIDA_SECCION_33 = Path("data_sets_transformados/secondary_market_modelado_seccion_33.csv")
RUTA_SALIDA_PREMIUM_SECCION_33 = Path("data_sets_transformados/secondary_market_modelado_seccion_33_premium.csv")
df_ols_seccion_33_origen = pd.read_csv(RUTA_ORIGEN_SECCION_33)
if df_ols_seccion_33_origen["price_per_sqm"].isna().any() or (df_ols_seccion_33_origen["price_per_sqm"] <= 0).any():
    raise ValueError("price_per_sqm contiene valores faltantes, cero o negativos")
df_ols_seccion_33 = df_ols_seccion_33_origen[df_ols_seccion_33_origen["price_per_sqm"] <= CORTE_PRECIO_ESTANDAR_SECCION_33].copy()
df_premium_seccion_33 = df_ols_seccion_33_origen[df_ols_seccion_33_origen["price_per_sqm"] > CORTE_PRECIO_ESTANDAR_SECCION_33].copy()
df_ols_seccion_33.to_csv(RUTA_SALIDA_SECCION_33, index=False)
df_premium_seccion_33.to_csv(RUTA_SALIDA_PREMIUM_SECCION_33, index=False)
df_train_seccion_33 = df_ols_seccion_33[df_ols_seccion_33["periodo"] < CORTE_TEMPORAL].copy()
df_test_seccion_33 = df_ols_seccion_33[df_ols_seccion_33["periodo"] >= CORTE_TEMPORAL].copy()
X_train_seccion_33 = df_train_seccion_33.drop(columns=["price_per_sqm", "periodo"])
X_test_seccion_33 = df_test_seccion_33.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_33 = df_train_seccion_33["price_per_sqm"]
y_test_seccion_33 = df_test_seccion_33["price_per_sqm"]
if df_train_seccion_33.empty or df_test_seccion_33.empty:
    raise ValueError("El corte temporal no produjo train y test para el mercado estandar")
X_train_seccion_33_sm = sm.add_constant(X_train_seccion_33, has_constant="add")
X_test_seccion_33_sm = sm.add_constant(X_test_seccion_33, has_constant="add")
resultados_ols_seccion_33 = sm.OLS(y_train_seccion_33, X_train_seccion_33_sm).fit()
predicciones_train_seccion_33 = resultados_ols_seccion_33.predict(X_train_seccion_33_sm)
predicciones_test_seccion_33 = resultados_ols_seccion_33.predict(X_test_seccion_33_sm)
metricas_ols_seccion_33 = {
    **calcular_metricas_regresion(y_train_seccion_33, predicciones_train_seccion_33, "train"),
    **calcular_metricas_regresion(y_test_seccion_33, predicciones_test_seccion_33, "test"),
    "r2_ols": float(resultados_ols_seccion_33.rsquared),
    "r2_ajustado_ols": float(resultados_ols_seccion_33.rsquared_adj),
    "aic_ols": float(resultados_ols_seccion_33.aic),
    "bic_ols": float(resultados_ols_seccion_33.bic),
    "f_statistic_ols": float(resultados_ols_seccion_33.fvalue),
    "prob_f_statistic_ols": float(resultados_ols_seccion_33.f_pvalue),
    "condition_number_ols": float(resultados_ols_seccion_33.condition_number),
    "coeficientes_significativos_005": float((resultados_ols_seccion_33.pvalues <= 0.05).sum()),
    "coeficientes_no_significativos_005": float((resultados_ols_seccion_33.pvalues > 0.05).sum()),
    "filas_mercado_estandar": float(len(df_ols_seccion_33)),
    "filas_mercado_premium": float(len(df_premium_seccion_33)),
    "proporcion_mercado_estandar": float(len(df_ols_seccion_33) / len(df_ols_seccion_33_origen)),
    "proporcion_mercado_premium": float(len(df_premium_seccion_33) / len(df_ols_seccion_33_origen))
}
omnibus_seccion_33, prob_omnibus_seccion_33 = omni_normtest(resultados_ols_seccion_33.resid)
jarque_bera_seccion_33, prob_jb_seccion_33, skew_seccion_33, kurtosis_seccion_33 = jarque_bera(resultados_ols_seccion_33.resid)
metricas_ols_seccion_33.update({
    "omnibus_ols": float(omnibus_seccion_33),
    "prob_omnibus_ols": float(prob_omnibus_seccion_33),
    "durbin_watson_ols": float(durbin_watson(resultados_ols_seccion_33.resid)),
    "jarque_bera_ols": float(jarque_bera_seccion_33),
    "prob_jb_ols": float(prob_jb_seccion_33),
    "skew_ols": float(skew_seccion_33),
    "kurtosis_ols": float(kurtosis_seccion_33)
})
coeficientes_ols_seccion_33 = pd.DataFrame({"variable": resultados_ols_seccion_33.params.index, "coeficiente": resultados_ols_seccion_33.params.to_numpy(), "p_value": resultados_ols_seccion_33.pvalues.to_numpy(), "significativa_0_05": resultados_ols_seccion_33.pvalues.to_numpy() <= 0.05})
residuos_test_seccion_33 = pd.DataFrame({"periodo": df_test_seccion_33["periodo"].to_numpy(), "real": y_test_seccion_33.to_numpy(), "prediccion": predicciones_test_seccion_33.to_numpy(), "residuo": y_test_seccion_33.to_numpy() - predicciones_test_seccion_33.to_numpy()})
# Baseline section 3 evaluated on the same standard test subset for a fair comparison.
df_train_seccion_3 = df_ols_seccion_33_origen[df_ols_seccion_33_origen["periodo"] < CORTE_TEMPORAL].copy()
X_train_seccion_3 = df_train_seccion_3.drop(columns=["price_per_sqm", "periodo"])
y_train_seccion_3 = df_train_seccion_3["price_per_sqm"]
resultados_ols_seccion_3_reajustado = sm.OLS(y_train_seccion_3, sm.add_constant(X_train_seccion_3, has_constant="add")).fit()
predicciones_test_seccion_3_sobre_estandar = resultados_ols_seccion_3_reajustado.predict(X_test_seccion_33_sm)
metricas_ols_seccion_3_sobre_estandar = calcular_metricas_regresion(y_test_seccion_33, predicciones_test_seccion_3_sobre_estandar, "test")
metricas_ols_seccion_3_sobre_estandar_mlflow = {f"seccion_3_{clave}": valor for clave, valor in metricas_ols_seccion_3_sobre_estandar.items()}
comparacion_ols_seccion_33 = pd.DataFrame([{"modelo": "OLS seccion 3 - test estandar", **metricas_ols_seccion_3_sobre_estandar}, {"modelo": "OLS seccion 33 - mercado estandar", **metricas_ols_seccion_33}])
delta_metricas_seccion_33 = {f"delta_{metrica}": metricas_ols_seccion_33[metrica] - metricas_ols_seccion_3_sobre_estandar[metrica] for metrica in ["mae_test", "rmse_test", "r2_test", "mape_test"]}
display(comparacion_ols_seccion_33[["modelo", "mae_test", "rmse_test", "r2_test", "mape_test"]])
mlflow.set_tracking_uri("http://127.0.0.1:5000")
mlflow.set_experiment("Inmobiliario - OLS Temporal")
with mlflow.start_run(run_name="ols_temporal_seccion_33_mercado_estandar_desde_seccion_3"):
    mlflow.set_tag("run_anterior_id", "8632cd73b7b84347bd6cd3ee0b2cfe4e")
    mlflow.log_params({"seccion": 33, "dataset": str(RUTA_SALIDA_SECCION_33), "dataset_premium": str(RUTA_SALIDA_PREMIUM_SECCION_33), "dataset_origen": str(RUTA_ORIGEN_SECCION_33), "objetivo": "price_per_sqm", "corte_temporal": CORTE_TEMPORAL, "corte_precio_estandar_rub_m2": CORTE_PRECIO_ESTANDAR_SECCION_33, "n_predictores": X_train_seccion_33.shape[1], "filas_entrenamiento": len(df_train_seccion_33), "filas_prueba": len(df_test_seccion_33), "filas_mercado_estandar": len(df_ols_seccion_33), "filas_mercado_premium": len(df_premium_seccion_33), "tipo_modelo": "statsmodels_OLS_seccion_33_mercado_estandar_desde_seccion_3"})
    mlflow.log_metrics({**metricas_ols_seccion_33, **metricas_ols_seccion_3_sobre_estandar_mlflow, **delta_metricas_seccion_33})
    mlflow.log_table(comparacion_ols_seccion_33, artifact_file="comparacion/comparacion_ols_seccion_33.json")
    mlflow.log_table(coeficientes_ols_seccion_33, artifact_file="modelo/coeficientes_ols_seccion_33.json")
    mlflow.log_table(residuos_test_seccion_33, artifact_file="diagnostico/residuos_test_seccion_33.json")
    mlflow.log_text(resultados_ols_seccion_33.summary().as_text(), "modelo/resumen_ols_seccion_33.txt")
print(f"Dataset estandar de la seccion 33 guardado en: {RUTA_SALIDA_SECCION_33}")
print(f"Dataset premium de la seccion 33 guardado en: {RUTA_SALIDA_PREMIUM_SECCION_33}")
print(f"Filas estandar: {len(df_ols_seccion_33)} | Filas premium: {len(df_premium_seccion_33)}")
print("OLS de la seccion 33 registrado en MLflow para comparacion")

                           modelo     mae_test    rmse_test  r2_test  mape_test
    OLS seccion 3 - test estandar 35093.255771 41121.289063 0.736545  24.164340
OLS seccion 33 - mercado estandar 29090.763965 34121.403972 0.818604  20.273794

                              modelo      mae_test  ...   r2_test  mape_test
0      OLS seccion 3 - test estandar  35093.255771  ...  0.736545  24.164340
1  OLS seccion 33 - mercado estandar  29090.763965  ...  0.818604  20.273794

[2 rows x 5 columns]
🏃 View run ols_temporal_seccion_33_mercado_estandar_desde_seccion_3 at: http://127.0.0.1:5000/#/experiments/4/runs/36fb53d6a8024b7b9701c9f55e28e514
🧪 View experiment at: http://127.0.0.1:5000/#/experiments/4
Dataset estandar de la seccion 33 guardado en: data_sets_transformados\secondary_market_modelado_seccion_33.csv
Dataset premium de la seccion 33 guardado en: data_sets_transformados\secondary_market_modelado_seccion_33_premium.csv
Filas estandar: 47052 | Filas premium: 2948
OLS de la seccion 33 registrado en MLflow para comparacion
                                     variable  p_value
0             metro_station_Elektrozavodskaya  0.99867
1                 metro_station_Profsoyuznaya  0.97709
2                 metro_station_Molodyozhnaya  0.93891
3                metro_station_Serpukhovskaya  0.92788
4                            district_Kievsky  0.90167
5                    metro_station_Pechatniki  0.88680
6                  metro_station_Borovitskaya  0.82076
7                 metro_station_Chistye Prudy  0.80874
8                  metro_station_Frunzenskaya  0.80734
9                metro_station_Delovoy Tsentr  0.79559
10                  metro_station_Ugreshskaya  0.77824
11                     metro_station_Yasenevo  0.77539
12                 metro_station_Belorusskaya  0.76965
13                                        lon  0.75667
14                metro_station_Sukharevskaya  0.72266
15             metro_station_Sretensky Bulvar  0.71512
16                     metro_station_Trubnaya  0.69976
17               metro_station_Kuznetsky Most  0.68205
18                  metro_station_Park Pobedy  0.67852
19                  metro_station_Kitay-Gorod  0.67560
20                  metro_station_Sportivnaya  0.65810
21                  metro_station_Kakhovskaya  0.65320
22                    metro_station_Rizhskaya  0.64139
23                 metro_station_Oktyabrskaya  0.61795
24    metro_station_Ulitsa Akademika Yangelya  0.60691
25                     metro_station_Kurskaya  0.60472
26             metro_station_Smolenskaya (AP)  0.57690
27                  metro_station_Teatralnaya  0.56376
28                                 total_area  0.55124
29        metro_station_Ploshchad Revolyutsii  0.54802
30                metro_station_Vystavochnaya  0.54198
31            district_Ochakovo-Matveyevskoye  0.54172
32                       district_Alekseevsky  0.54036
33            metro_station_Ploshchad Ilyicha  0.53251
34                   metro_station_Troparyovo  0.53130
35                     metro_station_Dubrovka  0.53119
36                         district_Mozhaysky  0.53027
37                                      rooms  0.52897
38             metro_station_Ulitsa 1905 Goda  0.51857
39                   district_Maryina Roshcha  0.51405
40                    metro_station_Kievskaya  0.51021
41              metro_station_Novoslobodskaya  0.50972
42               metro_station_Rechnoy Vokzal  0.49657
43                 metro_station_Chkalovskaya  0.48997
44                 metro_station_Kutuzovskaya  0.48211
45                     metro_station_Rimskaya  0.45252
46                     metro_station_Lubyanka  0.44921
47                 metro_station_Mayakovskaya  0.43402
48                                living_area  0.43269
49               metro_station_Arbatskaya (F)  0.40292
50                 metro_station_Dostoevskaya  0.40230
51              metro_station_Kantemirovskaya  0.39328
52               metro_station_Kozhukhovskaya  0.37886
53              metro_station_Smolenskaya (F)  0.35234
54                 metro_station_Park Kultury  0.34601
55                         metro_station_Fili  0.33843
56              metro_station_Novokuznetskaya  0.32812
57              metro_station_Sevastopolskaya  0.31891
58               metro_station_Studencheskaya  0.30667
59           metro_station_Krasnopresnenskaya  0.28268
60                 metro_station_Okhotny Ryad  0.24390
61             metro_station_Bagrationovskaya  0.21192
62                   metro_station_Taganskaya  0.20348
63                           district_Konkovo  0.20186
64            metro_station_Leninsky Prospekt  0.19591
65                    metro_station_Tverskaya  0.19216
66            district_Pokrovskoye-Streshnevo  0.18915
67                metro_station_Shabolovskaya  0.17775
68                        district_Rogovskoye  0.17369
69                     metro_station_Polyanka  0.15536
70                        district_Danilovsky  0.15433
71                metro_station_Turgenevskaya  0.15313
72                       district_Ostankinsky  0.13410
73           metro_station_Shosse Entuziastov  0.12135
74                           district_Zyuzino  0.11950
75                  metro_station_Universitet  0.11295
76                 metro_station_Chekhovskaya  0.11247
77              metro_station_Tsvetnoy Bulvar  0.10231
78                metro_station_Prospekt Mira  0.09367
79                         district_Sokolniki  0.08880
80               metro_station_Yugo-Zapadnaya  0.08768
81               metro_station_Kropotkinskaya  0.08285
82               metro_station_Tretyakovskaya  0.07604
83                metro_station_Proletarskaya  0.06945
84               metro_station_Filyovsky Park  0.06662
85                 metro_station_Novogireyevo  0.06579
86                metro_station_Pervomayskaya  0.05914
87                 district_Novofyodorovskoye  0.05575
88                     district_Timiryazevsky  0.05317
89                       district_Tyoply Stan  0.05213
90                               kitchen_area  0.04955
91                                        lat  0.04756
92                     metro_station_Yuzhnaya  0.04662
93                          seller_type_owner  0.04459
94                               building_age  0.03880
95                 metro_station_Pushkinskaya  0.03434
96           metro_station_Novye Cheryomushki  0.02700
97                       metro_station_Dinamo  0.02008
98         metro_station_Prospekt Vernadskogo  0.01861
99                        metro_station_VDNKh  0.01482
100              metro_station_Polezhaevskaya  0.01402
101                    metro_station_Begovaya  0.01247
102              metro_station_Mendeleevskaya  0.01181
103                 metro_station_Pionerskaya  0.00814
104                metro_station_Nagatinskaya  0.00719
105               metro_station_Semyonovskaya  0.00634
106                  mortgage_rate_at_listing  0.00605
107           metro_station_Slavyansky Bulvar  0.00544
108             metro_station_Timiryazevskaya  0.00515
109                    metro_station_Sviblovo  0.00402
110             metro_station_Sapyornoye Pole  0.00398
111              metro_station_Tekstilshchiki  0.00397
112         metro_station_Pyatnitskoye Shosse  0.00332
113                 district_Preobrazhenskoye  0.00170
114               metro_station_Komsomolskaya  0.00170
115                              total_floors  0.00145
116                 metro_station_Tyoply Stan  0.00132
117                    metro_station_Tulskaya  0.00129
118                 metro_station_Voykovskaya  0.00120
119               metro_station_Partizanskaya  0.00044
120                                     floor  0.00038
121          metro_station_Ulitsa Podbelskogo  0.00006
122                     district_Voronovskoye  0.00002
123                   metro_station_Sokolniki  0.00001
124                 district_Yuzhnoye Tushino  0.00001
125                           district_Mitino  0.00000
126             metro_station_Shchyolkovskaya  0.00000
127                    metro_station_Strogino  0.00000
128                          district_Kurkino  0.00000
129                   metro_station_Nagornaya  0.00000
130                     district_Klyonovskoye  0.00000
131                         district_Butyrsky  0.00000
132                      metro_station_Perovo  0.00000
133                          district_Nagorny  0.00000
134  metro_station_Preobrazhenskaya Ploshchad  0.00000
135               metro_station_Shchukinskaya  0.00000
136                        district_Voykovsky  0.00000
137                         district_Kotlovka  0.00000
138                       metro_station_Sokol  0.00000
139                          district_Vnukovo  0.00000
140                 district_Nagatinsky Zaton  0.00000
141                  district_Yuzhnoye Butovo  0.00000
142                 district_Severnoye Butovo  0.00000
143                      district_Savyolovsky  0.00000
144                        district_Solntsevo  0.00000
145                         district_Kuntsevo  0.00000
146                    district_Pervomayskoye  0.00000
147                           district_Perovo  0.00000
148                       district_Zelenograd  0.00000
149                          district_Donskoy  0.00000
150                district_Severnoye Tushino  0.00000
151                        district_Izmaylovo  0.00000
152                      district_Obruchevsky  0.00000
153          district_Mikhaylovo-Yartsevskoye  0.00000
154               district_Nagatino-Sadovniki  0.00000
155                 district_Novo-Peredelkino  0.00000
156            district_Khoroshyovo-Mnyovniki  0.00000
157                         district_Yasenevo  0.00000
158              district_Severnoye Izmaylovo  0.00000
159                     district_Levoberezhny  0.00000
160                            ceiling_height  0.00000
161                    district_Shchapovskoye  0.00000
162                district_Krasnopakhorskoye  0.00000
163                building_type_modern_panel  0.00000
164              district_Chertanovo Yuzhnoye  0.00000
165                   district_Molzhaninovsky  0.00000
166                              to_center_km  0.00000
167                          district_Troitsk  0.00000
168                     district_Novogireyevo  0.00000
169                       district_Novokosino  0.00000
170            district_Vostochnoye Izmaylovo  0.00000
171             district_Chertanovo Severnoye  0.00000
172                         district_Sviblovo  0.00000
173                    district_Ryazanovskoye  0.00000
174                    building_type_monolith  0.00000
175                      district_Shcherbinka  0.00000
176             district_Severnoye Medvedkovo  0.00000
177                  district_Losinoostrovsky  0.00000
178                          district_Koptevo  0.00000
179                     district_Babushkinsky  0.00000
180            district_Moskvorechye-Saburovo  0.00000
181                    district_Desyonovskoye  0.00000
182                            district_Sokol  0.00000
183                      district_Yaroslavsky  0.00000
184                          has_balcony_True  0.00000
185                       district_Sosenskoye  0.00000
186                     district_Bogorodskoye  0.00000
187                       district_Zyablikovo  0.00000
188                    district_Akademichesky  0.00000
189                   district_Marushkinskoye  0.00000
190                       district_Golovinsky  0.00000
191                          district_Begovoy  0.00000
192                      district_Ivanovskoye  0.00000
193                        district_Otradnoye  0.00000
194                  district_Sokolinaya Gora  0.00000
195                     district_Cheryomushki  0.00000
196       district_Orekhovo-Borisovo Yuzhnoye  0.00000
197                          district_Severny  0.00000
198                       district_Tsaritsyno  0.00000
199                        district_Moskovsky  0.00000
200           district_Biryulyovo Vostochnoye  0.00000
201             district_Biryulyovo Zapadnoye  0.00000
202                        district_Lianozovo  0.00000
203                        district_Rostokino  0.00000
204                       district_Kokoshkino  0.00000
205                         district_Bibirevo  0.00000
206      district_Orekhovo-Borisovo Severnoye  0.00000
207                        district_Vostochny  0.00000
208                 district_Kosino-Ukhtomsky  0.00000
209              district_Yuzhnoye Medvedkovo  0.00000
210                   district_Fili-Davydkovo  0.00000
211                        district_Shchukino  0.00000
212                          district_Marfino  0.00000
213          district_Chertanovo Tsentralnoye  0.00000
214                        district_Golyanovo  0.00000
215                        district_Brateyevo  0.00000
216                     district_Metrogorodok  0.00000
217                      district_Vnukovskoye  0.00000
218                   district_Beskudnikovsky  0.00000
219                    district_Khoroshyovsky  0.00000
220              district_Troparyovo-Nikulino  0.00000
221                      district_Altufyevsky  0.00000
222                         district_Khovrino  0.00000
223                   district_Voskresenskoye  0.00000
224                  district_Filimonkovskoye  0.00000
225                       district_Dmitrovsky  0.00000
226                        district_Veshnyaki  0.00000
227                       district_Mosrentgen  0.00000
228                      district_Krylatskoye  0.00000
229               district_Zapadnoye Degunino  0.00000
230                         district_Strogino  0.00000
231                   district_Filyovsky Park  0.00000
232             district_Prospekt Vernadskogo  0.00000
233                     district_Lomonosovsky  0.00000
234                      building_type_stalin  0.00000
235                         date_posted_month  0.00000
236                       district_Gagarinsky  0.00000
237                          district_Ramenki  0.00000
238                  metro_distance_type_walk  0.00000
239                          date_posted_year  0.00000
240                        metro_distance_min  0.00000
241                         district_Tagansky  0.00000
242                  renovation_no_renovation  0.00000
243                      district_Meshchansky  0.00000
244                       district_Presnensky  0.00000
245                       building_type_panel  0.00000
246                           renovation_euro  0.00000
247                  building_type_khrushchev  0.00000
248                   district_Zamoskvorechye  0.00000
249                        district_Yakimanka  0.00000
250                         district_Tverskoy  0.00000
251                       renovation_designer  0.00000
252                     district_Krasnoselsky  0.00000
253                     district_Dorogomilovo  0.00000
254                         district_Basmanny  0.00000
255                       district_Khamovniki  0.00000
256                            district_Arbat  0.00000
Dataset estandar de la seccion 33 guardado en: data_sets_transformados\secondary_market_modelado_seccion_33.csv
Dataset premium de la seccion 33 guardado en: data_sets_transformados\secondary_market_modelado_seccion_33_premium.csv
Filas estandar: 47052 | Filas premium: 2948
OLS de la seccion 33 registrado en MLflow para comparacion

### Interpretacion

La seccion 33 aplica el mismo corte de `402600 RUB/m2` sobre el dataset one-hot completo de la seccion 3. Su comparacion principal contra la seccion 3 usa exclusivamente el subconjunto estandar del periodo de prueba.